### PR TITLE
{2023.06}[2022b] R-bundle-Bioconductor v3.16

### PR DESCRIPTION
**Pull request by bedroge**
```
9 out of 172 required modules missing:

* intltool/0.51.0-GCCcore-12.2.0 (intltool-0.51.0-GCCcore-12.2.0.eb)
* RapidJSON/1.1.0-GCCcore-12.2.0 (RapidJSON-1.1.0-GCCcore-12.2.0.eb)
* gperf/3.1-GCCcore-12.2.0 (gperf-3.1-GCCcore-12.2.0.eb)
* RE2/2023-03-01-GCCcore-12.2.0 (RE2-2023-03-01-GCCcore-12.2.0.eb)
* utf8proc/2.8.0-GCCcore-12.2.0 (utf8proc-2.8.0-GCCcore-12.2.0.eb)
* Arrow/11.0.0-gfbf-2022b (Arrow-11.0.0-gfbf-2022b.eb)
* DBus/1.15.2-GCCcore-12.2.0 (DBus-1.15.2-GCCcore-12.2.0.eb)
* arrow-R/11.0.0.3-foss-2022b-R-4.2.2 (arrow-R-11.0.0.3-foss-2022b-R-4.2.2.eb)
* R-bundle-Bioconductor/3.16-foss-2022b-R-4.2.2 (R-bundle-Bioconductor-3.16-foss-2022b-R-4.2.2.eb)
```

### CODE REVIEW

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512

**Comment by bedroge** [comment]
The `neoverse_v1` build worked fine, but all x86_64 builds failed due to:

```
make[3]: Entering directory '/tmp/bot/easybuild/build/RbundleBioconductor/3.16/foss-2022b-R-4.2.2/Rhdf5lib/Rhdf5lib/src/hdf5/src'
  CC       H5.lo
In file included from H5.c:22:
H5private.h:1793:2: error: #error "We need __func__ or __FUNCTION__ to test function names!"
 1793 | #error "We need __func__ or __FUNCTION__ to test function names!"
      |  ^~~~~
In file included from H5VMprivate.h:23,
                 from H5Fprivate.h:35,
                 from H5Cprivate.h:35,
                 from H5ACprivate.h:33,
                 from H5.c:23:
H5.c: In function H5_init_library:
H5Eprivate.h:33:70: error: FUNC undeclared (first use in this function)
   33 | #define HERROR(maj_id, min_id, ...) H5E_printf_stack(NULL, __FILE__, FUNC, __LINE__, H5E_ERR_CLS_g, maj_id, min_id, __VA_ARGS__)
      |                                                                      ^~~~
H5Eprivate.h:124:5: note: in expansion of macro HERROR
  124 |     HERROR(H5E_INTERNAL, H5E_MPIERRSTR, "%s", H5E_mpi_error_str);                   \
      |     ^~~~~~
H5Eprivate.h:131:5: note: in expansion of macro HMPI_ERROR
  131 |     HMPI_ERROR(mpierr);                                                       \
      |     ^~~~~~~~~~
```

**Comment by bedroge** [comment]
```
            SUMMARY OF THE HDF5 CONFIGURATION
            =================================

General Information:
-------------------
                   HDF5 Version: 1.10.7
```
Seems like it's picking up a wrong HDF5, as we have `('HDF5', '1.14.0')` in the easyconfig.

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1

**Comment by xinan1911** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512

**Review by trz42 — APPROVED** [review]
All good: 🎉

**Pull request merged**
