### PR TITLE
{2023.6}[2023b,a64fx] ESPResSo 4.2.2 + pyMBE 0.8.0

### PR DESCRIPTION
**Pull request by boegel**
I'm using this PR to verify that the changes made for support builds for `dev.eessi.io` don't cause trouble for the `software.eessi.io` builds, so it sits on top of:
* #771

This PR shouldn't be merged until #771 is merged, so marking it as draft...

### CODE REVIEW

**Comment by boegel** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/a64fx

**Review by bedroge — APPROVED** [review]

**Comment by boegel** [comment]
@bedroge The `2023.06/init/minimal_eessi_env` that's being deployed in here is due to the changes to it in #771, we should've done a build & deploy in there...

**Comment by bedroge** [comment]
This was deployed and ingested, but it turned out that this somehow included a wrong/old and broken version of `minimal_eessi_env`, so I've rolled back the transaction. We should do a rebuild here to make sure that the latest version is included, or do this in a separate PR.

**Comment by boegel** [comment]
> This was deployed and ingested, but it turned out that this somehow included a wrong/old and broken version of `minimal_eessi_env`, so I've rolled back the transaction. We should do a rebuild here to make sure that the latest version is included, or do this in a separate PR.

The build was done before the commit that adds a guard for `$EESSI_COMPAT_LAYER_DIR` being defined was added, see https://github.com/EESSI/software-layer/commit/1afc5995b7f53a11f8f196d1f0a7c764c348b755

Easiest way forward is just doing the build again here, which should pick up on the correct `init/minimal_eessi_env`...

**Comment by boegel** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/a64fx

**Comment by boegel** [comment]
@bedroge Can you verify that the `init/minimal_eessi_env` in the tarball is correct now?

**Comment by bedroge** [comment]
> @bedroge Can you verify that the `init/minimal_eessi_env` in the tarball is correct now?

Extracted the tarball and did a diff with the file from the software-layer repo:
```
[bob@multixscale-stratum0 tmp]$ diff 2023.06/init/minimal_eessi_env software-layer/init/minimal_eessi_env 
[bob@multixscale-stratum0 tmp]$ 
```

And, indeed, the file now has:
```
# set $EPREFIX since that is basically a standard in Gentoo Prefix
# if $EESSI_COMPAT_LAYER_DIR is defined (for example by run_in_compat_layer_env.sh script), we use that value
if [ ! -z ${EESSI_COMPAT_LAYER_DIR} ]; then
    export EPREFIX=$EESSI_COMPAT_LAYER_DIR
else
    export EPREFIX=$EESSI_PREFIX/compat/$EESSI_OS_TYPE/$EESSI_CPU_FAMILY
fi
```

So, looks good to me now.

**Pull request merged**
