### PR TITLE
Rebuild `hatchling 1.18.0`, `Python 3.11.*`, `Python-bundle-PyPI-2023.*` to solve `setuptools_scm` issue

### PR DESCRIPTION
**Pull request by bedroge**
During the installation of R-bundle-Bioconductor with EB 4.9.1 in #533, I ran into the same issue as reported in https://github.com/easybuilders/easybuild-easyconfigs/issues/19849. In order to fix it, we have to apply the changes from https://github.com/easybuilders/easybuild-easyconfigs/pull/19777, which involves a reinstallation of some modules.

### CODE REVIEW

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3

**Comment by bedroge** [comment]
Something really weird is going on here. Python was reinstalled without any issues, but the installation of hatchling fails due to:
```
Successfully built hatchling
Installing collected packages: hatchling
ERROR: Could not install packages due to an OSError.
Consider using the `--user` option or check the permissions.
Traceback (most recent call last):
  File "/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/python3.11/site-packages/pip/_internal/commands/install.py", line 449, in run
    installed = install_given_reqs(
                ^^^^^^^^^^^^^^^^^^^
  File "/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/python3.11/site-packages/pip/_internal/req/__init__.py", line 72, in install_given_reqs
    requirement.install(
  File "/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/python3.11/site-packages/pip/_internal/req/req_install.py", line 800, in install
    install_wheel(
  File "/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/python3.11/site-packages/pip/_internal/operations/install/wheel.py", line 731, in install_wheel
    _install_wheel(
  File "/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/python3.11/site-packages/pip/_internal/operations/install/wheel.py", line 648, in _install_wheel
    generated_console_scripts = maker.make_multiple(scripts_to_generate)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/python3.11/site-packages/pip/_vendor/distlib/scripts.py", line 436, in make_multiple
    filenames.extend(self.make(specification, options))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/python3.11/site-packages/pip/_internal/operations/install/wheel.py", line 429, in make
    return super().make(specification, options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/python3.11/site-packages/pip/_vendor/distlib/scripts.py", line 425, in make
    self._make_script(entry, filenames, options=options)
  File "/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/python3.11/site-packages/pip/_vendor/distlib/scripts.py", line 325, in _make_script
    self._write_script(scriptnames, shebang, script, filenames, ext)
  File "/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/python3.11/site-packages/pip/_vendor/distlib/scripts.py", line 293, in _write_script
    self._fileop.write_binary_file(outname, script_bytes)
  File "/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/Python/3.11.3-GCCcore-12.3.0/lib/python3.11/site-packages/pip/_vendor/distlib/util.py", line 555, in write_binary_file
    os.remove(path)
PermissionError: [Errno 13] Permission denied: '/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/hatchling/1.18.0-GCCcore-12.3.0/bin/hatchling'
 (at easybuild/tools/run.py:682 in parse_cmd_output)
```

I checked the tarball of the removal step, and this shows that the hatchling versions were removed correctly:
```
$ ls /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/hatchling/
$ 
```

Then I inspected the container resumed from the build step, and it shows:
```
$ ls /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/hatchling/
1.18.0-GCCcore-12.3.0
$ ls /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/hatchling/1.18.0-GCCcore-12.3.0/
lib
$ mkdir /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/hatchling/1.18.0-GCCcore-12.3.0/bin
mkdir: cannot create directory '/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/hatchling/1.18.0-GCCcore-12.3.0/bin': File exists
```
:man_shrugging:

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3

**Comment by bedroge** [comment]
Tried doing them one by one, but that didn't help either. Still don't understand why it's only happening with hatchling, while the Python rebuilds have no issues (and neither did the GCC and OpenMPI rebuilds in previous PRs).

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3

**Comment by bedroge** [comment]
I had added user write permissions to the hatchling directories on the Stratum 0, and that did solve the issue for hatchling, but now the same thing is also happening to PYthon-bundle-PyPI. So, Ive done the same for those directories, and will try again.

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512

**Comment by boegel** [comment]
> I had added user write permissions to the hatchling directories on the Stratum 0, and that did solve the issue for hatchling, but now the same thing is also happening to PYthon-bundle-PyPI. So, Ive done the same for those directories, and will try again.

@bedroge Can you open an issue where you write down some kind of conclusion from this? What you observed, what you tried to work around it, what worked in the end?
It doesn't seem like this is going to be a one-off case, but hopefully it's some kind of bug in `fuse-overlayfs` and hence the problem may be temporary?

Did you try doing a recursive `chmod` before doing the removal to trigger the rebuild?
Maybe doing a `mv` before `rm` would work too, not sure.

**Comment by bedroge** [comment]
> 
> @bedroge Can you open an issue where you write down some kind of conclusion from this? What you observed, what you tried to work around it, what worked in the end?
> 
> It doesn't seem like this is going to be a one-off case, but hopefully it's some kind of bug in `fuse-overlayfs` and hence the problem may be temporary?
> 
> 
> 
> Did you try doing a recursive `chmod` before doing the removal to trigger the rebuild?
> 
> Maybe doing a `mv` before `rm` would work too, not sure.

Yep, I tried that as well (chmod and moving). I'll document it in an issue.

**Comment by boegel** [comment]
@bedroge Is this ready to deploy now?

**Comment by bedroge** [comment]
> @bedroge Is this ready to deploy now?

@boegel Yes it is, though it does require a manual ingestion, so the staging PRs should not be merged yet.

**Comment by bedroge** [comment]
> @bedroge Can you open an issue where you write down some kind of conclusion from this? What you observed, what you tried to work around it, what worked in the end?

Done in https://github.com/EESSI/software-layer/issues/556.

**Comment by bedroge** [comment]
Manual ingestion procedure:
```
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/generic/software/hatchling/1.18.0-GCCcore-12.3.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/generic/software/hatchling/1.18.0-GCCcore-13.2.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/neoverse_n1/software/hatchling/1.18.0-GCCcore-12.3.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/neoverse_n1/software/hatchling/1.18.0-GCCcore-13.2.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/neoverse_v1/software/hatchling/1.18.0-GCCcore-12.3.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/neoverse_v1/software/hatchling/1.18.0-GCCcore-13.2.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/generic/software/hatchling/1.18.0-GCCcore-12.3.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/generic/software/hatchling/1.18.0-GCCcore-13.2.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/hatchling/1.18.0-GCCcore-12.3.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/hatchling/1.18.0-GCCcore-13.2.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/hatchling/1.18.0-GCCcore-12.3.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/hatchling/1.18.0-GCCcore-13.2.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/hatchling/1.18.0-GCCcore-12.3.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/hatchling/1.18.0-GCCcore-13.2.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/software/hatchling/1.18.0-GCCcore-12.3.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/software/hatchling/1.18.0-GCCcore-13.2.0

rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/generic/software/Python-bundle-PyPI/2023.06-GCCcore-12.3.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/generic/software/Python-bundle-PyPI/2023.10-GCCcore-13.2.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/neoverse_n1/software/Python-bundle-PyPI/2023.06-GCCcore-12.3.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/neoverse_n1/software/Python-bundle-PyPI/2023.10-GCCcore-13.2.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/neoverse_v1/software/Python-bundle-PyPI/2023.06-GCCcore-12.3.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/neoverse_v1/software/Python-bundle-PyPI/2023.10-GCCcore-13.2.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/generic/software/Python-bundle-PyPI/2023.06-GCCcore-12.3.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/generic/software/Python-bundle-PyPI/2023.10-GCCcore-13.2.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/Python-bundle-PyPI/2023.06-GCCcore-12.3.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/Python-bundle-PyPI/2023.10-GCCcore-13.2.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/Python-bundle-PyPI/2023.06-GCCcore-12.3.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/Python-bundle-PyPI/2023.10-GCCcore-13.2.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/Python-bundle-PyPI/2023.06-GCCcore-12.3.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/Python-bundle-PyPI/2023.10-GCCcore-13.2.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/software/Python-bundle-PyPI/2023.06-GCCcore-12.3.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/software/Python-bundle-PyPI/2023.10-GCCcore-13.2.0

rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/generic/software/Python/3.11.3-GCCcore-12.3.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/generic/software/Python/3.11.5-GCCcore-13.2.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/neoverse_n1/software/Python/3.11.3-GCCcore-12.3.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/neoverse_n1/software/Python/3.11.5-GCCcore-13.2.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/neoverse_v1/software/Python/3.11.3-GCCcore-12.3.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/neoverse_v1/software/Python/3.11.5-GCCcore-13.2.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/generic/software/Python/3.11.3-GCCcore-12.3.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/generic/software/Python/3.11.5-GCCcore-13.2.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/Python/3.11.3-GCCcore-12.3.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/Python/3.11.5-GCCcore-13.2.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/Python/3.11.3-GCCcore-12.3.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/Python/3.11.5-GCCcore-13.2.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/Python/3.11.3-GCCcore-12.3.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/Python/3.11.5-GCCcore-13.2.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/software/Python/3.11.3-GCCcore-12.3.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/software/Python/3.11.5-GCCcore-13.2.0

cd /cvmfs/software.eessi.io/versions

tar xvzf /srv/tmp/tarballs/eessi-2023.06-software-linux-aarch64-generic-1714491188.tar.gz
tar xvzf /srv/tmp/tarballs/eessi-2023.06-software-linux-aarch64-neoverse_n1-1714491164.tar.gz
tar xvzf /srv/tmp/tarballs/eessi-2023.06-software-linux-aarch64-neoverse_v1-1714490014.tar.gz
tar xvzf /srv/tmp/tarballs/eessi-2023.06-software-linux-x86_64-amd-zen2-1714490894.tar.gz
tar xvzf /srv/tmp/tarballs/eessi-2023.06-software-linux-x86_64-amd-zen3-1714490155.tar.gz
tar xvzf /srv/tmp/tarballs/eessi-2023.06-software-linux-x86_64-generic-1714491255.tar.gz
tar xvzf /srv/tmp/tarballs/eessi-2023.06-software-linux-x86_64-intel-haswell-1714491212.tar.gz
tar xvzf /srv/tmp/tarballs/eessi-2023.06-software-linux-x86_64-intel-skylake_avx512-1714490695.tar.gz
```

**Comment by bedroge** [comment]
Manual ingestion completed, I'll close the staging PRs.

**Review by boegel — APPROVED** [review]

**Pull request merged**
