### PR TITLE
{2023.06}[GCC/13.3.0] foss v2024a, GCC v13.3.0, SciPy-bundle v2024.05

### PR DESCRIPTION
**Pull request by maxim-masterov**
Adding foss/2024a toolchain

### CODE REVIEW

**Comment by maxim-masterov** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic

**Comment by boegel** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen4

**Comment by bedroge** [comment]
> New job on instance `eessi-bot-mc-aws` for architecture `x86_64-generic` for repository `eessi.io-2023.06-software` in job dir `/project/def-users/SHARED/jobs/2024.08/pr_685/17040`
> 
> date	job status	comment
> Aug 26 12:38:56 UTC 2024	submitted	job id `17040` awaits release by job manager
> Aug 26 12:39:53 UTC 2024	released	job awaits launch by Slurm scheduler
> Aug 26 12:45:55 UTC 2024	running	job `17040` is running
> Aug 26 16:59:45 UTC 2024	finished	
> 😢 FAILURE _(click triangle for details)_
> Aug 26 16:59:45 UTC 2024	test result	
> 😁 SUCCESS _(click triangle for details)_

The installation of Rust failed due to:

```
  = note: /cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64/usr/bin/ld: warning: libssl.so.3, needed by /cvmfs/software.eessi.io/versions/2023.06/so
ftware/linux/x86_64/generic/software/cURL/8.7.1-GCCcore-13.3.0/lib/libcurl.so, may conflict with libssl.so.1.1
          /cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64/usr/bin/ld: /tmp/bot/easybuild/build/Rust/1.78.0/GCCcore-13.3.0/rustc-1.78.0-src/build/x
86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/liblibgit2_sys-1576691ff55a4d5e.rlib(openssl.o): undefined reference to symbol 'SSL_get1_peer_certificate@@OPENSSL_3.0.0'
          /cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64/usr/bin/ld: /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/generic/software/OpenSSL/3/lib64/libssl.so.3: error adding symbols: DSO missing from command line
          collect2: error: ld returned 1 exit status
          
  = note: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#rustc-link-lib)

error: could not compile `cargo` (bin "cargo") due to 1 previous error
```

**Comment by boegel** [comment]
`OpenSSL/3` (which is supposed to wrap around the system OpenSSL) is used as a dependency in the `2024a` generation of easyconfigs. Here, it's being built from source, and then not fully working as it should.

We should either:
1) hold off on using `2024a` before we have a new compat layer version that uses OpenSSL 3.x rather than 1.1.x;
2) replace `OpenSSL/3` with `OpenSSL/1.1` in EasyBuild hooks when installing for EESSI version 2023.06;

I prefer option 1

**Comment by ocaisa** [comment]
I also prefer option 1, if we use a new version more recent architecture support will become simpler

**Comment by maxim-masterov** [comment]
Closing this PR for now, as we are waiting for the new combat layer. See [issue #56](https://gitlab.com/eessi/support/-/issues/56) on the EESSI support portal.

**Comment by casparvl** [comment]
> new combat layer

Combat layer, I like that :P 

On topic: I was wondering if there is anything preventing us from deploying OpenSSL 3 _next to_ OpenSSL 1.1 in the compat layer. And then use the OpenSSL 3 module to wrap the OpenSSL 3 from the compat layer?

**Pull request closed without merging**
