### PR TITLE
{2023.06}[foss/2023a] MBX v1.1.0

### PR DESCRIPTION
**Pull request by TopRichard**

### CODE REVIEW

**Comment by TopRichard** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic

**Comment by TopRichard** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1

**Comment by TopRichard** [comment]
The build process on `aarch64-generic` fails with : 
```
virtual memory exhausted: Cannot allocate memory
make[3]: *** [Makefile:2466: potential/3b/libmbx_la-poly_3b_A1B2_A1B2_A1B2_deg4_grad_vmbpbe.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
```

**Comment by TopRichard** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic

**Comment by TopRichard** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512

**Comment by TopRichard** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1
bot: build repo:eessi.io-2023.06-software arch:zen4

**Comment by boegel** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen4

**Comment by boegel** [comment]
@TopRichard Don't wait for the `zen4` build, there's a problem with the Azure cluster currently, it may take a while to resolve it...

**Review by bedroge — DISMISSED** [review]

**Review by bedroge — APPROVED** [review]

**Comment by boegel** [comment]
@TopRichard Did you manage to look into the large difference in sizes for `x86_64/*` vs `aarch64/*`?

**Comment by TopRichard** [comment]
> @TopRichard Did you manage to look into the large difference in sizes for `x86_64/*` vs `aarch64/*`?

Yes i compared `zen3` tarball with `aarch64` generic tarball, both tarballs have the same files,however the size difference lies in `bin`files

**Pull request merged**
