### PR TITLE
Use `$EESSI_VERSION` for `EESSI-extend` version and filter Yasm dependency on RISC-V

### PR DESCRIPTION
**Pull request by bedroge**
This makes the easyconfig a bit more flexible, and we can easily use it for the RISC-V repo (see #803) and for other new versions of the production/dev repo.

~Note that I still need to update the easystacks accordingly.~ Done

Note: besides adding Yasm to the filtered dependencies for RISC-V, I also changed `yasm` to `Yasm` for `aarch64`, since that's the correct naming (see https://github.com/easybuilders/easybuild-easyconfigs/tree/develop/easybuild/easyconfigs/y/Yasm).

### CODE REVIEW

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3

**Review by trz42 — APPROVED** [review]
lgtm

**Comment by trz42** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen4
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1

**Comment by trz42** [comment]
All ingested.

**Pull request merged**
