### PR TITLE
also install SciPy-bundle-2021.05-foss-2021a.eb into 2021.12 pilot

### PR DESCRIPTION
**Pull request by boegel**
Worked on:
* [x] `aarch64/generic` (done, ingested)
* [x] `aarch64/graviton2` (done, ingested)
* [x] `aarch64/graviton3` (done, ingested)
* [ ] `ppc64le/generic` (building)
* [ ] `ppc64le/power9le` (built, ready to ingest)
* [x] `x86_64/generic` (done, ingested)
* [x] `x86_64/amd/zen2` (done, ingested)
* [x] `x86_64/amd/zen3` (done, ingested)
* [x] `x86_64/intel/haswell` (done, ingested)
* [x] `x86_64/intel/skylake_avx512` (done, ingested)

### CODE REVIEW

**Comment by boegel** [comment]
Installing on POWER failed due to known issue with FlexiBLAS (part of `foss/2021a`), see also https://github.com/easybuilders/easybuild-easyconfigs/issues/12968...

Only way out short term seems to be mangling `foss/2021a` so it uses `OpenBLAS` directly on POWER, bypassing FlexiBLAS.

**Comment by boegel** [comment]
There's no easy way to get the problems on resolved, unless we start "mangling" `foss/2021a` to kick out FlexiBLAS.

Maybe we should go ahead and merge this, and open an issue to follow up on getting `SciPy-bundle-2021.05-foss-2021a.eb` installed on the `ppc64le` target (which are 2nd tier anyway, at bes.t...)

**Comment by ocaisa** [comment]
I'm keen to merge this even without POWER as every other arch has already been injested

**Review by ocaisa — APPROVED** [review]
This has already been ingested so only a visual ok from me...

**Pull request merged**
