### PR TITLE
use directory of called script as base dir for other scripts

### PR DESCRIPTION
**Pull request by trz42**
This improves the usability of `bot/inspect.sh` / fixes a bug. If one ran the script from another directory as the working directory of a bot job (or the main directory of a checkout of EESSI/software-layer), it fails to source other scripts and does not find `./eessi_container.sh`.

### CODE REVIEW

**Review by ocaisa — APPROVED** [review]
Changes look good, but I'm not sure how to test this, if I try to submit a build job I guess it will run...

**Review by ocaisa — CHANGES_REQUESTED** [review]
Line 260 in this file should be updated to keep things consistent

**Comment by trz42** [comment]
> Line 260 in this file should be updated to keep things consistent
> 
> https://github.com/trz42/software-layer/blob/use_full_path_in_inspect_script/bot/inspect.sh#L258-L263

Updated the script by using a single variable (and only setting its value once). Also changed variable name from uppercase to lowercase.

**Comment by trz42** [comment]
> Changes look good, but I'm not sure how to test this, if I try to submit a build job I guess it will run...

You can use this to inspect a build job by:
1. launching an interactive job on a node with the same architecture as was used by the build job
2. determine the working directory of the build job you want to inspect, say BUILD_JOB_DIR
3. then run `$BUILD_JOB_DIR/bot/inspect.sh --resume $BUILD_JOB_DIR/previous_tmp/build_step/eessi...tgz`

(I think, it should be possible to create a tool/script that does all three steps, such that you could just run `debug_session.sh --job-id SLURM_JOBID` or similar. Thus it would become even easier to debug failing jobs.)

**Review by ocaisa — APPROVED** [review]
LGTM

**Pull request merged**
