### PR TITLE
{2023.06}[foss/2023a] UCX-CUDA v1.14.1 w/ CUDA 12.1.1 (rebuild)

### PR DESCRIPTION
**Pull request by casparvl**
requires:
* #720

### CODE REVIEW

**Comment by casparvl** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2 accel:nvidia/cc80

**Comment by casparvl** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2 accel:nvidia/cc80

**Comment by casparvl** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2 accel:nvidia/cc80

**Comment by casparvl** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2 accel:nvidia/cc80

**Comment by casparvl** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3 accel:nvidia/cc80

**Comment by casparvl** [comment]
I checked the tarball for `19864`. This
```
$ readelf -d libucm_cuda.so | grep RPATH
 0x000000000000000f (RPATH)              Library rpath: [/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/accel/nvidia/cc80/software/UCX-CUDA/1.14.1-GCCcore-12.3.0-CUDA-12.1.1/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/accel/nvidia/cc80/software/UCX-CUDA/1.14.1-GCCcore-12.3.0-CUDA-12.1.1/lib64:$ORIGIN:$ORIGIN/../lib:$ORIGIN/../lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/GDRCopy/2.3.1-GCCcore-12.3.0/lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/UCX/1.14.1-GCCcore-12.3.0/lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/accel/nvidia/cc80/software/CUDA/12.1.1/lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/pkgconf/1.9.5-GCCcore-12.3.0/lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/GCCcore/12.3.0/lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/GCCcore/12.3.0/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/numactl/2.0.16-GCCcore-12.3.0/lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/GCCcore/12.3.0/lib/gcc/x86_64-pc-linux-gnu/12.3.0:/cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64/lib/../lib64:/cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64/usr/lib/../lib64:/cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64/lib:/cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64/usr/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/UCX/1.14.1-GCCcore-12.3.0/lib]
```
Looks like it's using the correct path to the newly deployed CUDA installation at `/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/accel/nvidia/cc80/software/CUDA/12.1.1/lib64`. One thing I did notice is that we hae GDRcopy in the CPU tree. We might consider moving that to the GPU tree (first).

**Comment by boegel** [comment]
Also for job `19865`, looks good:
```
[bot@login1 19865]$ readelf -d 2023.06/software/linux/x86_64/amd/zen3/accel/nvidia/cc80/software/UCX-CUDA/1.14.1-GCCcore-12.3.0-CUDA-12.1.1/ucx/libuct_cuda_gdrcopy.so.0| grep RPATH | tr ':' '\n' | grep '/CUDA/'
/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/accel/nvidia/cc80/software/CUDA/12.1.1/lib64
```

W.r.t. GDRCopy: since it doesn't depend on CUDA at all, I wouldn't move it under `accel/`, even though it's really only useful on an NVIDIA GPU system, just to keep the rule simple as to what goes under `accel/` (stuff that depends on CUDA).

**Comment by ocaisa** [comment]
Gdrcopy is a tough one but I think I lean towards @boegel point of view, it doesn't need CUDA and builds just fine for all CPUs (at least currently). It allows us to keep the hook exception free which has value, and if it does cause problems later we can fix it in the next version

**Comment by boegel** [comment]
staging PRs merged

**Review by boegel — APPROVED** [review]

**Pull request merged**
