### PR TITLE
{2023.06}[foss/2022b] h5py v3.8.0

### PR DESCRIPTION
**Pull request by TopRichard**
```
Missing packages:
h5py/3.8.0-foss-2022b
mpi4py/3.1.4-gompi-2022b
pkgconfig/1.5.5-GCCcore-12.2.0-python
```

### CODE REVIEW

**Comment by TopRichard** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1

**Comment by boegel** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen4

**Comment by ocaisa** [comment]
@boegel You've trigged a build for zen4 and 2022b but this is currently "not supported" due to an issue with OpenBLAS

**Comment by boegel** [comment]
> @boegel You've trigged a build for zen4 and 2022b but this is currently "not supported" due to an issue with OpenBLAS

Sorry, I overlooked that this was for `2022b`.

**Review by boegel — APPROVED** [review]

**Pull request merged**
