### PR TITLE
{2023.06,zen4} foss/2023b

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen4

**Comment by boegel** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen4

**Comment by bedroge** [comment]
The tarball of job 83 contains init files, probably because #569 wasn't merged yet, so let's try again.

**Comment by boegel** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen4

**Comment by boegel** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen4

**Review by bedroge — APPROVED** [review]

**Comment by bedroge** [comment]
@boegel I think this needs a sync with the main branch to solve the failing CI?

**Pull request merged**
