### PR TITLE
Fix test_suite not being able to retrieve memory on systems that use cgroups v2

### PR DESCRIPTION
**Pull request by casparvl**
Fixes https://gitlab.com/eessi/support/-/issues/86

### CODE REVIEW

**Comment by casparvl** [comment]
bot: build repo:eessi.io-2023.06-software arch:zen4

**Comment by casparvl** [comment]
Ok, need to debug further, it seems to get a memory limit of `0` now...

```
[ RUN      ] EESSI_CP2K %benchmark_info=QS/H2O-32 %module_name=CP2K/2023.1-foss-2023a %scale=1_node /ae4db8cc @BotBuildTests:default+default
[     SKIP ] ( 1/18) Skipping test: nodes in this partition only have 0 MiB memory available (per node) accodring to the current ReFrame configuration, but 4198.4 MiB is needed
[ RUN      ] EESSI_ESPRESSO_LJ_PARTICLES %module_name=ESPResSo/4.2.2-foss-2023b %device_type=cpu %scale=1_node /adc964f6 @BotBuildTests:default+default
[     SKIP ] ( 2/18) Skipping test: nodes in this partition only have 0 MiB memory available (per node) accodring to the current ReFrame configuration, but 7372.799999999999 MiB is needed
[ RUN      ] EESSI_ESPRESSO_LJ_PARTICLES %module_name=ESPResSo/4.2.2-foss-2023a %device_type=cpu %scale=1_node /3b8b8926 @BotBuildTests:default+default
[     SKIP ] ( 3/18) Skipping test: nodes in this partition only have 0 MiB memory available (per node) accodring to the current ReFrame configuration, but 7372.799999999999 MiB is needed
[ RUN      ] EESSI_ESPRESSO_LJ_PARTICLES %module_name=ESPResSo/4.2.1-foss-2023a %device_type=cpu %scale=1_node /fdd6aced @BotBuildTests:default+default
[     SKIP ] ( 4/18) Skipping test: nodes in this partition only have 0 MiB memory available (per node) accodring to the current ReFrame configuration, but 7372.799999999999 MiB is needed
[ RUN      ] EESSI_ESPRESSO_P3M_IONIC_CRYSTALS %module_name=ESPResSo/4.2.2-foss-2023b %device_type=cpu %scale=1_node /3b90ffd6 @BotBuildTests:default+default
[     SKIP ] ( 5/18) Skipping test: nodes in this partition only have 0 MiB memory available (per node) accodring to the current ReFrame configuration, but 22118.4 MiB is needed
[ RUN      ] EESSI_ESPRESSO_P3M_IONIC_CRYSTALS %module_name=ESPResSo/4.2.2-foss-2023a %device_type=cpu %scale=1_node /f1621689 @BotBuildTests:default+default
[     SKIP ] ( 6/18) Skipping test: nodes in this partition only have 0 MiB memory available (per node) accodring to the current ReFrame configuration, but 22118.4 MiB is needed
[ RUN      ] EESSI_ESPRESSO_P3M_IONIC_CRYSTALS %module_name=ESPResSo/4.2.1-foss-2023a %device_type=cpu %scale=1_node /4a9e965c @BotBuildTests:default+default
[     SKIP ] ( 7/18) Skipping test: nodes in this partition only have 0 MiB memory available (per node) accodring to the current ReFrame configuration, but 22118.4 MiB is needed
[ RUN      ] EESSI_GROMACS %benchmark_info=HECBioSim/Crambin %nb_impl=cpu %scale=1_node %module_name=GROMACS/2024.1-foss-2023b /02920241 @BotBuildTests:default+default
[ RUN      ] EESSI_LAMMPS_lj %scale=1_node %device_type=cpu %module_name=LAMMPS/2Aug2023_update2-foss-2023a-kokkos /04ff9ece @BotBuildTests:default+default
[     SKIP ] ( 8/18) Skipping test: nodes in this partition only have 0 MiB memory available (per node) accodring to the current ReFrame configuration, but 2232.32 MiB is needed
````

**Comment by casparvl** [comment]
bot: build repo:eessi.io-2023.06-software arch:zen4

**Comment by casparvl** [comment]
bot: build repo:eessi.io-2023.06-software arch:zen4

**Comment by casparvl** [comment]
bot: build repo:eessi.io-2023.06-software arch:zen4

**Comment by casparvl** [comment]
Oh, good to realize, the test suite will run with `zen3` optimized code...

```
Found EESSI repo @ /cvmfs/software.eessi.io/versions/2023.06!
archdetect says x86_64/amd/zen4
ESC[33mSticking to x86_64/amd/zen3 for now, since optimized installations for AMD Genoa (Zen4) are a work in progress, see https://gitlab.com/eessi/support/-/issues/37 for more informationESC[0m
Using x86_64/amd/zen3 as software subdirectory.
```

So it is currently not _actually_ testing the `zen4` installation.

**Comment by casparvl** [comment]
```
================================================================================
SUMMARY OF FAILURES
--------------------------------------------------------------------------------
FAILURE INFO for EESSI_TensorFlow %scale=1_node %module_name=TensorFlow/2.13.0-foss-2023a %device_type=cpu (run: 1/1)
  * Description: TensorFlow benchmark on cpu
  * System partition: BotBuildTests:default
  * Environment: default
  * Stage directory: /project/60006/SHARED/jobs/2024.08/pr_670/event_a60dc670-5af6-11ef-8b15-1638b43216e9/run_000/linux_x86_64_amd_zen4/eessi.io-2023.06-software/reframe_runs/stage/BotBuildTests/default/default/EESSI_TensorFlow_9864d0f5
  * Node list: x86-64-amd-zen4-node1.int.azure-almalinux93-202403
  * Job type: local (id=38718)
  * Dependencies (conceptual): []
  * Dependencies (actual): []
  * Maintainers: []
  * Failing phase: run
  * Rerun with '-n /9864d0f5 -p default --system BotBuildTests:default -r'
  * Reason: job error: [jobid=38718] job timed out (1807.937331s > 1800.0s)
--------------------------------------------------------------------------------
```

**Comment by casparvl** [comment]
bot: build repo:eessi.io-2023.06-software arch:zen4

**Comment by casparvl** [comment]
bot: build repo:eessi.io-2023.06-software arch:zen4

**Comment by casparvl** [comment]
bot: build repo:eessi.io-2023.06-software arch:zen4

**Comment by casparvl** [comment]
Ok:
```
EESSI_SOFTWARE_SUBDIR_OVERRIDE before calling eessi_software_subdir.py: x86_64/amd/zen4
EESSI_SOFTWARE_SUBDIR_OVERRIDE after calling eessi_software_subdir.py: x86_64/amd/zen4
Found EESSI repo @ /cvmfs/software.eessi.io/versions/2023.06!
archdetect says x86_64/amd/zen4
Using x86_64/amd/zen4 as software subdirectory.
```
That looks good, it works now and will run the test from this. But:

```
Prepending site path /cvmfs/software.eessi.io/host_injections/2023.06/software/linux/x86_64/amd/zen4/modules/all to $MODULEPATH...
Environment set up to use EESSI (2023.06), have fun!
Lmod has detected the following error: The following module(s) are unknown:
"ReFrame"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore_cache load "ReFrame"

Also make sure that all modulefiles written in TCL start with the string
#%Module



ESC[31mERROR: Failed to load the ReFrame moduleESC[0m
```
Ouch, no ReFrame module yet for `zen4`. I'll replace my 'dummy' `gnuplot` with the ReFrame version we also have for the other architectures... :)

**Comment by casparvl** [comment]
bot: build repo:eessi.io-2023.06-software arch:zen4

**Comment by casparvl** [comment]
bot: build repo:eessi.io-2023.06-software arch:zen4

**Comment by casparvl** [comment]
I'm confused. In the test step of the bot:

```
Checking if ReFrame module exists:
ls: cannot access '/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen4/modules/all/ReFrame/4.3.3.lua': No such file or directory
```

How can that not exist, I just installed it didn't I? And the test step resumes from the correct tempdir:

```
./eessi_container.sh --verbose --access ro --mode run --container docker://ghcr.io/eessi/build-node:debian11 --repository eessi.io-2023.06-software --save /project/60006/SHARED/jobs/2024.08/pr_670/event_05f02830-5b24-11ef-8f2d-cbb6fa9c
f255/run_000/linux_x86_64_amd_zen4/eessi.io-2023.06-software/previous_tmp/test_step --resume /tmp/bot/EESSI/eessi.XvUflydXGA --extra-bind-paths /sys/fs/cgroup:/hostsys/fs/cgroup:ro
                     -- ./run_tests.sh "" "" 2>&1 | tee -a test.outerr.J1vQ
```

What's going on here?

**Comment by casparvl** [comment]
Tried manually, got:
```
Apptainer> ls /tmp/overlay-upper/versions/2023.06/software/linux/x86_64/amd/zen4/modules/all/ReFrame/4.3.3.lua
/tmp/overlay-upper/versions/2023.06/software/linux/x86_64/amd/zen4/modules/all/ReFrame/4.3.3.lua
Apptainer> ls /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen4/modules/all/ReFrame/4.3.3.lua
ls: cannot access '/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen4/modules/all/ReFrame/4.3.3.lua': No such file or directory
```

**Comment by casparvl** [comment]
bot: build repo:eessi.io-2023.06-software arch:zen4

**Comment by casparvl** [comment]
bot: build repo:eessi.io-2023.06-software arch:zen4

**Comment by casparvl** [comment]
And the actual test step for this one looks perfect:
```
[----------] start processing checks
[ RUN      ] EESSI_CP2K %benchmark_info=QS/H2O-32 %module_name=CP2K/2023.1-foss-2023a %scale=1_node /ae4db8cc @BotBuildTests:default+default
ESC[33mWARNING: hooks.req_memory_per_node does not support the scheduler you configured (local). The test will run, but since it doesn't request the required amount of memory explicitely, it may result in an out-of-memory error. Please expand the functionality of hooks.req_memory_per_n
ode for your scheduler.ESC[0m
[ RUN      ] EESSI_ESPRESSO_LJ_PARTICLES %module_name=ESPResSo/4.2.2-foss-2023b %device_type=cpu %scale=1_node /adc964f6 @BotBuildTests:default+default
ESC[33mWARNING: hooks.req_memory_per_node does not support the scheduler you configured (local). The test will run, but since it doesn't request the required amount of memory explicitely, it may result in an out-of-memory error. Please expand the functionality of hooks.req_memory_per_n
ode for your scheduler.ESC[0m
[ RUN      ] EESSI_ESPRESSO_LJ_PARTICLES %module_name=ESPResSo/4.2.2-foss-2023a %device_type=cpu %scale=1_node /3b8b8926 @BotBuildTests:default+default
ESC[33mWARNING: hooks.req_memory_per_node does not support the scheduler you configured (local). The test will run, but since it doesn't request the required amount of memory explicitely, it may result in an out-of-memory error. Please expand the functionality of hooks.req_memory_per_n
ode for your scheduler.ESC[0m
[ RUN      ] EESSI_ESPRESSO_LJ_PARTICLES %module_name=ESPResSo/4.2.1-foss-2023a %device_type=cpu %scale=1_node /fdd6aced @BotBuildTests:default+default
ESC[33mWARNING: hooks.req_memory_per_node does not support the scheduler you configured (local). The test will run, but since it doesn't request the required amount of memory explicitely, it may result in an out-of-memory error. Please expand the functionality of hooks.req_memory_per_n
ode for your scheduler.ESC[0m
[ RUN      ] EESSI_ESPRESSO_P3M_IONIC_CRYSTALS %module_name=ESPResSo/4.2.2-foss-2023b %device_type=cpu %scale=1_node /3b90ffd6 @BotBuildTests:default+default
ESC[33mWARNING: hooks.req_memory_per_node does not support the scheduler you configured (local). The test will run, but since it doesn't request the required amount of memory explicitely, it may result in an out-of-memory error. Please expand the functionality of hooks.req_memory_per_n
ode for your scheduler.ESC[0m
[ RUN      ] EESSI_ESPRESSO_P3M_IONIC_CRYSTALS %module_name=ESPResSo/4.2.2-foss-2023a %device_type=cpu %scale=1_node /f1621689 @BotBuildTests:default+default
ESC[33mWARNING: hooks.req_memory_per_node does not support the scheduler you configured (local). The test will run, but since it doesn't request the required amount of memory explicitely, it may result in an out-of-memory error. Please expand the functionality of hooks.req_memory_per_n
ode for your scheduler.ESC[0m
[ RUN      ] EESSI_ESPRESSO_P3M_IONIC_CRYSTALS %module_name=ESPResSo/4.2.1-foss-2023a %device_type=cpu %scale=1_node /4a9e965c @BotBuildTests:default+default
ESC[33mWARNING: hooks.req_memory_per_node does not support the scheduler you configured (local). The test will run, but since it doesn't request the required amount of memory explicitely, it may result in an out-of-memory error. Please expand the functionality of hooks.req_memory_per_n
ode for your scheduler.ESC[0m
[ RUN      ] EESSI_GROMACS %benchmark_info=HECBioSim/Crambin %nb_impl=cpu %scale=1_node %module_name=GROMACS/2024.1-foss-2023b /02920241 @BotBuildTests:default+default
[ RUN      ] EESSI_OSU_Micro_Benchmarks_coll %benchmark_info=mpi.collective.osu_allreduce %scale=1_node %module_name=OSU-Micro-Benchmarks/7.2-gompi-2023b %device_type=cpu /31ac6ab9 @BotBuildTests:default+default
[ RUN      ] EESSI_OSU_Micro_Benchmarks_coll %benchmark_info=mpi.collective.osu_alltoall %scale=1_node %module_name=OSU-Micro-Benchmarks/7.2-gompi-2023b %device_type=cpu /10e66fba @BotBuildTests:default+default
[ RUN      ] EESSI_OSU_Micro_Benchmarks_pt2pt %benchmark_info=mpi.pt2pt.osu_latency %scale=1_node %module_name=OSU-Micro-Benchmarks/7.2-gompi-2023b %device_type=cpu /c8c9aff5 @BotBuildTests:default+default
[ RUN      ] EESSI_OSU_Micro_Benchmarks_pt2pt %benchmark_info=mpi.pt2pt.osu_bw %scale=1_node %module_name=OSU-Micro-Benchmarks/7.2-gompi-2023b %device_type=cpu /48da21c5 @BotBuildTests:default+default
[ RUN      ] EESSI_TensorFlow %scale=1_node %module_name=TensorFlow/2.13.0-foss-2023a %device_type=cpu /9864d0f5 @BotBuildTests:default+default
[       OK ] ( 1/13) EESSI_CP2K %benchmark_info=QS/H2O-32 %module_name=CP2K/2023.1-foss-2023a %scale=1_node /ae4db8cc @BotBuildTests:default+default
P: time: 13.582 s (r:0, l:None, u:None)
[       OK ] ( 2/13) EESSI_ESPRESSO_LJ_PARTICLES %module_name=ESPResSo/4.2.2-foss-2023b %device_type=cpu %scale=1_node /adc964f6 @BotBuildTests:default+default
P: perf: 0.001411 s/step (r:0, l:None, u:None)
[       OK ] ( 3/13) EESSI_ESPRESSO_LJ_PARTICLES %module_name=ESPResSo/4.2.2-foss-2023a %device_type=cpu %scale=1_node /3b8b8926 @BotBuildTests:default+default
P: perf: 0.001363 s/step (r:0, l:None, u:None)
[       OK ] ( 4/13) EESSI_ESPRESSO_LJ_PARTICLES %module_name=ESPResSo/4.2.1-foss-2023a %device_type=cpu %scale=1_node /fdd6aced @BotBuildTests:default+default
P: perf: 0.001389 s/step (r:0, l:None, u:None)
[       OK ] ( 5/13) EESSI_ESPRESSO_P3M_IONIC_CRYSTALS %module_name=ESPResSo/4.2.2-foss-2023b %device_type=cpu %scale=1_node /3b90ffd6 @BotBuildTests:default+default
P: perf: 2.683 s/step (r:0, l:None, u:None)
[       OK ] ( 6/13) EESSI_ESPRESSO_P3M_IONIC_CRYSTALS %module_name=ESPResSo/4.2.2-foss-2023a %device_type=cpu %scale=1_node /f1621689 @BotBuildTests:default+default
P: perf: 2.596 s/step (r:0, l:None, u:None)
[       OK ] ( 7/13) EESSI_ESPRESSO_P3M_IONIC_CRYSTALS %module_name=ESPResSo/4.2.1-foss-2023a %device_type=cpu %scale=1_node /4a9e965c @BotBuildTests:default+default
P: perf: 2.628 s/step (r:0, l:None, u:None)
[       OK ] ( 8/13) EESSI_GROMACS %benchmark_info=HECBioSim/Crambin %nb_impl=cpu %scale=1_node %module_name=GROMACS/2024.1-foss-2023b /02920241 @BotBuildTests:default+default
P: perf: 166.709 ns/day (r:0, l:None, u:None)
[       OK ] ( 9/13) EESSI_OSU_Micro_Benchmarks_coll %benchmark_info=mpi.collective.osu_allreduce %scale=1_node %module_name=OSU-Micro-Benchmarks/7.2-gompi-2023b %device_type=cpu /31ac6ab9 @BotBuildTests:default+default
P: latency: 3.67 us (r:0, l:None, u:None)
[       OK ] (10/13) EESSI_OSU_Micro_Benchmarks_coll %benchmark_info=mpi.collective.osu_alltoall %scale=1_node %module_name=OSU-Micro-Benchmarks/7.2-gompi-2023b %device_type=cpu /10e66fba @BotBuildTests:default+default
P: latency: 10.48 us (r:0, l:None, u:None)
[       OK ] (11/13) EESSI_OSU_Micro_Benchmarks_pt2pt %benchmark_info=mpi.pt2pt.osu_latency %scale=1_node %module_name=OSU-Micro-Benchmarks/7.2-gompi-2023b %device_type=cpu /c8c9aff5 @BotBuildTests:default+default
P: latency: 0.3 us (r:0, l:None, u:None)
[       OK ] (12/13) EESSI_OSU_Micro_Benchmarks_pt2pt %benchmark_info=mpi.pt2pt.osu_bw %scale=1_node %module_name=OSU-Micro-Benchmarks/7.2-gompi-2023b %device_type=cpu /48da21c5 @BotBuildTests:default+default
P: bandwidth: 44334.1 MB/s (r:0, l:None, u:None)
[       OK ] (13/13) EESSI_TensorFlow %scale=1_node %module_name=TensorFlow/2.13.0-foss-2023a %device_type=cpu /9864d0f5 @BotBuildTests:default+default
P: perf: 59672.899852645496 img/s (r:0, l:None, u:None)
[----------] all spawned checks have finished

[  PASSED  ] Ran 13/13 test case(s) from 13 check(s) (0 failure(s), 0 skipped, 0 aborted)
```

**Review by boegel — APPROVED** [review]
lgtm

**Pull request merged**
