### PR TITLE
{2023.06}[foss/2023a] R-bundle-CRAN 2023.12

### PR DESCRIPTION
**Pull request by trz42**
Attempt to add `R-bundle-CRAN/2023.12` to `software.eessi.io/2023.06`.

License:
- ca. 1100 R packages $\rightarrow$ need automation to determine individual licenses

Missing installations:
```
25 out of 148 required modules missing:

* NLopt/2.7.1-GCCcore-12.3.0 (NLopt-2.7.1-GCCcore-12.3.0.eb)
* nettle/3.9.1-GCCcore-12.3.0 (nettle-3.9.1-GCCcore-12.3.0.eb)
* libogg/1.3.5-GCCcore-12.3.0 (libogg-1.3.5-GCCcore-12.3.0.eb)
* FLAC/1.4.2-GCCcore-12.3.0 (FLAC-1.4.2-GCCcore-12.3.0.eb)
* libvorbis/1.3.7-GCCcore-12.3.0 (libvorbis-1.3.7-GCCcore-12.3.0.eb)
* Xvfb/21.1.8-GCCcore-12.3.0 (Xvfb-21.1.8-GCCcore-12.3.0.eb)
* libopus/1.4-GCCcore-12.3.0 (libopus-1.4-GCCcore-12.3.0.eb)
* libsndfile/1.2.2-GCCcore-12.3.0 (libsndfile-1.2.2-GCCcore-12.3.0.eb)
* PostgreSQL/16.1-GCCcore-12.3.0 (PostgreSQL-16.1-GCCcore-12.3.0.eb)
* GEOS/3.12.0-GCC-12.3.0 (GEOS-3.12.0-GCC-12.3.0.eb)
* libgeotiff/1.7.1-GCCcore-12.3.0 (libgeotiff-1.7.1-GCCcore-12.3.0.eb)
* libtirpc/1.3.3-GCCcore-12.3.0 (libtirpc-1.3.3-GCCcore-12.3.0.eb)
* HDF/4.2.16-2-GCCcore-12.3.0 (HDF-4.2.16-2-GCCcore-12.3.0.eb)
* CFITSIO/4.3.0-GCCcore-12.3.0 (CFITSIO-4.3.0-GCCcore-12.3.0.eb)
* arpack-ng/3.9.0-foss-2023a (arpack-ng-3.9.0-foss-2023a.eb)
* Armadillo/12.6.2-foss-2023a (Armadillo-12.6.2-foss-2023a.eb)
* json-c/0.16-GCCcore-12.3.0 (json-c-0.16-GCCcore-12.3.0.eb)
* Xerces-C++/3.2.4-GCCcore-12.3.0 (Xerces-C++-3.2.4-GCCcore-12.3.0.eb)
* Imath/3.1.7-GCCcore-12.3.0 (Imath-3.1.7-GCCcore-12.3.0.eb)
* OpenEXR/3.1.7-GCCcore-12.3.0 (OpenEXR-3.1.7-GCCcore-12.3.0.eb)
* Brunsli/0.1-GCCcore-12.3.0 (Brunsli-0.1-GCCcore-12.3.0.eb)
* LERC/4.0.0-GCCcore-12.3.0 (LERC-4.0.0-GCCcore-12.3.0.eb)
* SWIG/4.1.1-GCCcore-12.3.0 (SWIG-4.1.1-GCCcore-12.3.0.eb)
* GDAL/3.7.1-foss-2023a (GDAL-3.7.1-foss-2023a.eb)
* R-bundle-CRAN/2023.12-foss-2023a (R-bundle-CRAN-2023.12-foss-2023a.eb)
```

### CODE REVIEW

**Comment by trz42** [comment]
bot: build repo:eessi.io-2023.06-software

**Comment by trz42** [comment]
bot: build arch:x86_64/amd/zen3  repo:eessi.io-2023.06-software

**Comment by trz42** [comment]
bot: build arch:x86_64/amd/zen3 repo:eessi.io-2023.06-software

**Comment by bedroge** [comment]
I've spent quite a lot of time on debugging the issue with `at-spi2-core`, and ultimately found the cause in its dependency `GObject-Introspection`. The build of `at-spi2-core` calls `g-ir-scanner` via Meson's https://mesonbuild.com/Gnome-module.html#gnomegenerate_gir (see https://gitlab.gnome.org/GNOME/at-spi2-core/-/blob/AT_SPI2_CORE_2_49_91/atspi/meson.build?ref_type=tags#L128). This tool compiles some binary, and checks with `ldd` afterwards if the shared libraries of that binary can be found. In order to do that, it sets `LD_LIBRARY_PATH` to directories that include dependencies, and also to `$EPREFIX/usr/lib64`. The latter somehow breaks `ldd` in our build container, resulting in errors like:
```
/bin/bash: /cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64/usr/lib64/libtinfo.so.6: no version information available (required by /bin/bash)
/bin/bash: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64/usr/lib64/libtinfo.so.6)
```
I think this is because `ldd` is actually a bash script, which has a shebang that points to the host (not sure why Gentoo does not eprefixify this to the bash of the Prefix installation); by setting `$LD_LIBRARY_PATH`, this `bash` is picking up libraries from Prefix. I tried manually eprefixifying `ldd` in our container (and let is use the correct `bash`), and for some reason that did solve it interactively, but not when installing with EasyBuild.

As an alternative, we could patch the `meson.build` of `at-spi2-core`, and let it instruct `g-ir-scanner` to use some other variable instead of `$LD_LIBRARY_PATH` by setting `--lib-dirs-envvar` to some dummy variable. I've tested this approach by adding the following hook, which adds the option right below this line https://gitlab.gnome.org/GNOME/at-spi2-core/-/blob/AT_SPI2_CORE_2_49_91/atspi/meson.build?ref_type=tags#L119 (and only if EasyBuild is configured to filter `$LD_LIBRARY_PATH`):
```
def pre_configure_hook_atspi2core_filter_ld_library_path(self, *args, **kwargs):
    """
    Pre-configure hook for at-spi2-core: don't set LD_LIBRARY_PATH when calling g-ir-scanner
    """
    if self.name == 'at-spi2-core':
        if build_option('filter_env_vars') and 'LD_LIBRARY_PATH' in build_option('filter_env_vars'):
            self.cfg.update('preconfigopts', 'sed -i "s/gir_extra_args = \[/gir_extra_args = \[\\n  \'--lib-dirs-envvar=FILTER_LD_LIBRARY_PATH\',/g" %(start_dir)s/atspi/meson.build && ')
    else:
        raise EasyBuildError("at-spi2-core-specific hook triggered for non-at-spi2-core easyconfig?!")
```
Not sure if this is the cleanest way to do it, and the same issue could potentially pop up for other tools using `GObject-Introspection`, but at least it allowed me to build `at-spi2-core` in our build container.

**Comment by bedroge** [comment]
If you want to reproduce the issue, you can do the following:
```
cd /path/to/software-layer
./eessi_container.sh
/cvmfs/software.eessi.io/versions/2023.06/compat/linux/$(uname -m)/startprefix
env LD_LIBRARY_PATH=/cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64/usr/lib64 ldd --version
```
which should result in:
```
/bin/bash: /cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64/usr/lib64/libtinfo.so.6: no version information available (required by /bin/bash)
/bin/bash: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64/usr/lib64/libtinfo.so.6)
```

**Comment by ocaisa** [comment]
Good work @bedroge , this is what lay behind https://github.com/EESSI/software-layer/issues/196

**Comment by bedroge** [comment]
@trz42 I've made a PR to your branch that syncs this PR with the main 2023.06-software.eessi.io branch, resolved the merge conflict, removes `LERC` and `MPFR` (as those fixes are included with EB 4.9.0), and moves `R-bundle-CRAN` to the EB 4.9.0 easystack file: https://github.com/trz42/software-layer/pull/68/files.

**Comment by bedroge** [comment]
Resolved the new merge conflict, let's see how far we get this time... (I'm pretty sure it's going to break on `Highway`, just like #419).

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3

**Comment by bedroge** [comment]
It failed on `ImageMagick-7.1.1-15-GCCcore-12.3.0.eb`, with first a whole bunch of warnings that some libraries have been moved, e.g.:
```
libtool: warning: '/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/libpng/1.6.39-GCCcore-12.3.0/lib64/libpng16.la' seems to be moved
libtool: warning: '/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/fontconfig/2.14.2-GCCcore-12.3.0/lib64/libfontconfig.la' seems to be moved
libtool: warning: '/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/freetype/2.13.0-GCCcore-12.3.0/lib64/libfreetype.la' seems to be moved
libtool: warning: '/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/X11/20230603-GCCcore-12.3.0/lib64/libXext.la' seems to be moved
libtool: warning: '/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/X11/20230603-GCCcore-12.3.0/lib64/libXt.la' seems to be moved
libtool: warning: '/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/X11/20230603-GCCcore-12.3.0/lib64/libSM.la' seems to be moved
libtool: warning: '/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/X11/20230603-GCCcore-12.3.0/lib64/libICE.la' seems to be moved
libtool: warning: '/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/X11/20230603-GCCcore-12.3.0/lib64/libX11.la' seems to be moved
libtool: warning: '/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/X11/20230603-GCCcore-12.3.0/lib64/libxcb.la' seems to be moved
libtool: warning: '/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/HarfBuzz/5.3.1-GCCcore-12.3.0/lib64/libharfbuzz.la' seems to be moved
libtool: warning: '/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/libxml2/2.11.4-GCCcore-12.3.0/lib64/libxml2.la' seems to be moved
```

Followed by these two warning:
```
/cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64/usr/bin/ld: warning: libfribidi.so.0, needed by /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/Pango/1.50.14-GCCcore-12.3.0/lib64/libpango-1.0.so, not found (try using -rpath or -rpath-link)
/cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64/usr/bin/ld: warning: libpixman-1.so.0, needed by /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/cairo/1.17.8-GCCcore-12.3.0/lib64/libcairo.so, not found (try using -rpath or -rpath-link)
```

And, finally, a whole bunch of undefined references (just showing a few here, but they're all about `cairo -> pixman` or `pango -> fribidi`:
```
/cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64/usr/bin/ld: /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/cairo/1.17.8-GCCcore-12.3.0/lib64/libcairo.so: undefined reference to `pixman_add_triangles'
/cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64/usr/bin/ld: /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/cairo/1.17.8-GCCcore-12.3.0/lib64/libcairo.so: undefined reference to `pixman_region32_union'
/cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64/usr/bin/ld: /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/cairo/1.17.8-GCCcore-12.3.0/lib64/libcairo.so: undefined reference to `pixman_region32_equal'
/cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64/usr/bin/ld: /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/Pango/1.50.14-GCCcore-12.3.0/lib64/libpango-1.0.so: undefined reference to `fribidi_get_bracket'
```

**Comment by bedroge** [comment]
Adding both to the dependencies of ImageMagick seems to solve the issue:
```
    ('pixman', '0.42.2'),
    ('FriBidi', '1.0.12'),
```
Not sure why that's required though. `pixman` is included in the RPATH section of `libcairo`, and the same for `fribidi` and `libpango`... And searching for any of them in the sources doesn't show a lot, only here: https://github.com/ImageMagick/ImageMagick/blob/7.1.1-15/Magick%2B%2B/lib/Magick%2B%2B/Include.h#L169.

I haven't seen this issue on our local cluster, where we do use RPATH, but don't filter `$LD_LIBRARY_PATH`.

@boegel any thoughts? Should we just add them to the easyconfig, or inject them via a hook?

**Comment by ocaisa** [comment]
My vote would be that they are clearly required deps, so should be listed in the easyconfig

**Comment by bedroge** [comment]
Done in https://github.com/easybuilders/easybuild-easyconfigs/pull/20086, and split off the installation of ImageMagick to #498.

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3

**Comment by bedroge** [comment]
We're almost there, even Highway (for which I expected some new issue to pop up) built fine. It now failed during the installation of the CRAN bundle itself:
```
== 2024-03-12 16:51:04,000 build_log.py:171 ERROR EasyBuild crashed with an error (at easybuild/tools/build_log.py:111 in cal
ler_info): Unexpected error occurred when trying to download https://cran.r-project.org/src/contrib/farver_2.1.1.tar.gz to /p
roject/def-users/bot/shared/easybuild/sources/r/R-bundle-CRAN/extensions/farver_2.1.1.tar.gz: 'Failed to write to /project/de
f-users/bot/shared/easybuild/sources/r/R-bundle-CRAN/extensions/farver_2.1.1.tar.gz: The read operation timed out' (at easybu
ild/tools/filetools.py:843 in download_file)
```

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512

**Comment by trz42** [comment]
> > We're almost there, even Highway (for which I expected some new issue to pop up) built fine.
> 
> Ah, of course, forgot that the Highway issue only popped up on Neoverse. Now it does fail with lots of the following errors:
> 
> ```
> /tmp/bot/easybuild/build/Highway/1.0.4/GCCcore-12.3.0/highway-1.0.4/hwy/tests/test_util.h:139:17: error: inlining failed in call to always_inline void hwy::AssertEqual(T, T, const char*, const char*, int, size_t) [with T = long unsigned int]: target specific option mismatch
> ```

Maybe a hint in https://stackoverflow.com/questions/75745202/arm64-sha512-intrinsics-fail-to-compile-with-gcc-target-specific-option-mismat

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
all staging PRs merged

**Review by boegel — APPROVED** [review]

**Pull request merged**
