### PR TITLE
Disable LMOD cache in test step so we can use modules built in the build step

### PR DESCRIPTION
**Pull request by casparvl**

### CODE REVIEW

**Comment by casparvl** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell

**Comment by casparvl** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell

**Comment by boegel** [comment]
@casparvl Setting `$LMOD_IGNORE_CACHE` makes sense to me, since the Lmod cache is only updated on ingestion.

**Comment by casparvl** [comment]
I know, right? ;-) The only thing that surprises me is that we didn't do this sooner :D

**Review by boegel — APPROVED** [review]

**Pull request merged**
