### PR TITLE
{2023.06}[gfbf/2023a,zen4] ipympl v0.9.3 for zen4

### PR DESCRIPTION
**Pull request by laraPPr**

### CODE REVIEW

**Comment by laraPPr** [comment]
bot: build repo:eessi.io-2023.06-software arch:zen4

**Comment by laraPPr** [comment]
bot: build repo:eessi.io-2023.06-software arch:zen4

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
staging PRs merged, so also merging this...

**Pull request merged**
