### PR TITLE
{2023.06}[foss/2023a] Critic2 v1.2

### PR DESCRIPTION
**Pull request by TopRichard**
```
missing packages:

Critic2/1.2-foss-2023a
libcint/5.4.0-gfbf-2023a
```

### CODE REVIEW

**Comment by TopRichard** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic

**Comment by TopRichard** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1

**Comment by TopRichard** [comment]
bot: build repo:eessi.io-2023.06-software arch:zen4

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:zen4

**Comment by TopRichard** [comment]
bot: build repo:eessi.io-2023.06-software arch:zen4

**Comment by TopRichard** [comment]
bot: build repo:eessi.io-2023.06-software arch:zen4

**Comment by boegel** [comment]
All staging PRs merged...

**Review by boegel — APPROVED** [review]
lgtm

**Pull request merged**
