### PR TITLE
{2023.06,a64fx}[foss/2023a] R v4.3.2

### PR DESCRIPTION
**Pull request by boegel**
Step up towards #680, which is stuck due to a tricky problem with a dependency of `R-bundle-CRAN`...

### CODE REVIEW

**Comment by boegel** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/a64fx

**Comment by boegel** [comment]
Failed because `hatchling/1.18.0-GCCcore-12.3.0` is temporary unavailable for A64FX, see #669

**Comment by Neves-P** [comment]
> Failed because `hatchling/1.18.0-GCCcore-12.3.0` is temporary unavailable for A64FX, see #669

@boegel, `hatchling` should be available now 🤞

**Comment by boegel** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/a64fx

**Comment by boegel** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/a64fx

**Review by trz42 — APPROVED** [review]
lgtm

**Review by bedroge — APPROVED** [review]
```
$ ls /cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/a64fx/software/R/4.3.2-gfbf-2023a/
bin  easybuild  lib  lib64  share
```

Lgtm!

**Pull request merged**
