### PR TITLE
make `link_nvidia_host_libraries.sh` script a bit more robust, in case target of host_injections directory is a non-existing directory

### PR DESCRIPTION
**Pull request by boegel**
If the target of the `host_injections` variant symlink, you get the following puzzling error:

```
$ ls -l ${EESSI_CVMFS_REPO}/host_injections
lrwxrwxrwx 1 cvmfs cvmfs 23 Oct  3 13:51 /cvmfs/software.eessi.io/host_injections -> /tmp/opt/eessi

$ scripts/gpu_support/nvidia/link_nvidia_host_libraries.sh
Found ldconfig in the following locations:
- /sbin/ldconfig
- /usr/sbin/ldconfig
Using first version
Found NVIDIA GPU driver version 535.129.03
Found host CUDA version 12.2
Creating /cvmfs/software.eessi.io/host_injections/nvidia/x86_64/host (real path /tmp/opt/eessi/nvidia/x86_64/host) failed with:
 mkdir: cannot create directory ‘/cvmfs/software.eessi.io/host_injections’: File exists
ERROR: No write permissions to directory /cvmfs/software.eessi.io/host_injections/nvidia/x86_64/host
```

works fine if the target does exist:

```
$ mkdir /tmp/opt/eessi
$ scripts/gpu_support/nvidia/link_nvidia_host_libraries.sh
Found ldconfig in the following locations:
- /sbin/ldconfig
- /usr/sbin/ldconfig
Using first version
Found NVIDIA GPU driver version 535.129.03
Found host CUDA version 12.2
Downloading latest version of nvliblist.conf from Apptainer to /tmp/tmp.Ko6VDH8wev/nvliblist.conf
Host NVIDIA gpu drivers linked successfully for EESSI
```

The extra block of code with `host_injections_target` makes sure the target of the `host_injections` variant symlink is an existing directory.

If you don't have permissions, you'll also get a clearer error now (though the confusing one is still there):

```
Creating /opt/eessi (real path /opt/eessi) failed with:
 mkdir: cannot create directory ‘/opt/eessi’: Permission denied
Creating /cvmfs/software.eessi.io/host_injections/nvidia/x86_64/host (real path /opt/eessi/nvidia/x86_64/host) failed with:
 mkdir: cannot create directory ‘/cvmfs/software.eessi.io/host_injections’: File exists
ERROR: No write permissions to directory /cvmfs/software.eessi.io/host_injections/nvidia/x86_64/host
```

I've also added some extra informative messages, like mentioning GPU driver version that was found, etc., and muted the useless download progress output produced by `curl` by using `--silent`.

### CODE REVIEW

**Review by ocaisa — APPROVED** [review]

**Comment by ocaisa** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512

**Comment by ocaisa** [comment]
@boegel So the failure  is probably because there is no easystack change in the PR so EasyBuild never gets called, we should add some kind of  `or` clause when no yaml is touched that just prints "No missing installations"

**Comment by casparvl** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512

**Review by ocaisa — DISMISSED** [review]

**Comment by ocaisa** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1

**Comment by casparvl** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1

**Comment by boegel** [comment]
@ocaisa @casparvl Ready to merge, since it's deployed:

```
$ date
Fri Dec 22 18:36:35 CET 2023

$ grep host_injections_target /cvmfs/software.eessi.io/versions/2023.06/scripts/gpu_support/nvidia/link_nvidia_host_libraries.sh
host_injections_target=$(realpath -m ${EESSI_CVMFS_REPO}/host_injections)
if [ ! -d ${host_injections_target} ]; then
    create_directory_structure ${host_injections_target}
```

**Review by casparvl — APPROVED** [review]

**Pull request merged**
