### PR TITLE
{2023.06}[GCCcore/13.2.0] Qt5 v5.15.13

### PR DESCRIPTION
**Pull request by TopRichard**
Attempt for building Qt5 v5.15.11 GCCcore-13.2.0
```
21 out of 55 required modules missing:

* PCRE2/10.42-GCCcore-13.2.0 (PCRE2-10.42-GCCcore-13.2.0.eb)
* re2c/3.1-GCCcore-13.2.0 (re2c-3.1-GCCcore-13.2.0.eb)
* double-conversion/3.3.0-GCCcore-13.2.0 (double-conversion-3.3.0-GCCcore-13.2.0.eb)
* GLib/2.78.1-GCCcore-13.2.0 (GLib-2.78.1-GCCcore-13.2.0.eb)
* graphite2/1.3.14-GCCcore-13.2.0 (graphite2-1.3.14-GCCcore-13.2.0.eb)
* pixman/0.42.2-GCCcore-13.2.0 (pixman-0.42.2-GCCcore-13.2.0.eb)
* cairo/1.18.0-GCCcore-13.2.0 (cairo-1.18.0-GCCcore-13.2.0.eb)
* GObject-Introspection/1.78.1-GCCcore-13.2.0 (GObject-Introspection-1.78.1-GCCcore-13.2.0.eb)
* HarfBuzz/8.2.2-GCCcore-13.2.0 (HarfBuzz-8.2.2-GCCcore-13.2.0.eb)
* Mako/1.2.4-GCCcore-13.2.0 (Mako-1.2.4-GCCcore-13.2.0.eb)
* snappy/1.1.10-GCCcore-13.2.0 (snappy-1.1.10-GCCcore-13.2.0.eb)
* NSPR/4.35-GCCcore-13.2.0 (NSPR-4.35-GCCcore-13.2.0.eb)
* NSS/3.94-GCCcore-13.2.0 (NSS-3.94-GCCcore-13.2.0.eb)
* libdrm/2.4.117-GCCcore-13.2.0 (libdrm-2.4.117-GCCcore-13.2.0.eb)
* nodejs/20.9.0-GCCcore-13.2.0 (nodejs-20.9.0-GCCcore-13.2.0.eb)
* libglvnd/1.7.0-GCCcore-13.2.0 (libglvnd-1.7.0-GCCcore-13.2.0.eb)
* libunwind/1.6.2-GCCcore-13.2.0 (libunwind-1.6.2-GCCcore-13.2.0.eb)
* LLVM/16.0.6-GCCcore-13.2.0 (LLVM-16.0.6-GCCcore-13.2.0.eb)
* Mesa/23.1.9-GCCcore-13.2.0 (Mesa-23.1.9-GCCcore-13.2.0.eb)
* libGLU/9.0.3-GCCcore-13.2.0 (libGLU-9.0.3-GCCcore-13.2.0.eb)
* Qt5/5.15.13-GCCcore-13.2.0 (Qt5-5.15.13-GCCcore-13.2.0.eb)

```

### CODE REVIEW

**Comment by TopRichard** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic

**Comment by boegel** [comment]
@TopRichard There's little point in trying this while test reports are still failing in https://github.com/easybuilders/easybuild-easyconfigs/pull/19320 .

I know @Neves-P also looked into this, or was planning to, I haven't found time to look back into the missing patches to get Qt5 working with `GCCcore/13.2.0`...

**Comment by TopRichard** [comment]
Shall i close the PR and reopen afterwards?

**Comment by Neves-P** [comment]
I did look into it, but didn't make much progress... @boegel, maybe it makes sense to open an issue in the support portal since this will almost certainly impact more things? If so, I can open it.

**Comment by boegel** [comment]
@Neves-P Sure!

**Comment by TopRichard** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic

**Comment by TopRichard** [comment]
The build was successful but is reported as failure because of `check_missing_installations.sh` which reports :
```
4 out of 69 required modules missing:

* giflib/5.2.1-GCCcore-13.2.0 (giflib-5.2.1-GCCcore-13.2.0.eb)
* LittleCMS/2.15-GCCcore-13.2.0 (LittleCMS-2.15-GCCcore-13.2.0.eb)
* libwebp/1.3.2-GCCcore-13.2.0 (libwebp-1.3.2-GCCcore-13.2.0.eb)
* OpenJPEG/2.5.0-GCCcore-13.2.0 (OpenJPEG-2.5.0-GCCcore-13.2.0.eb)
```

**Comment by TopRichard** [comment]
Missing packages added by #513 , will re initiate build process.

**Comment by TopRichard** [comment]
Builds are failing :
```
1 out of 56 required modules missing:

* Wayland/1.22.0-GCCcore-13.2.0 (Wayland-1.22.0-GCCcore-13.2.0.eb)
```

**Comment by boegel** [comment]
@TopRichard Seems like that's because of the change made in https://github.com/easybuilders/easybuild-easyconfigs/pull/20069

**Comment by TopRichard** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic

**Comment by TopRichard** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1

**Review by bedroge — APPROVED** [review]

**Comment by bedroge** [comment]
Thanks for all your efforts @Neves-P and @TopRichard!

**Pull request merged**
