### PR TITLE
{2023.06}[foss/2022b] math-packages

### PR DESCRIPTION
**Pull request by TopRichard**
```
missing packages:

CGAL/5.5.2-GCCcore-12.2.0
KaHIP/3.14-gompi-2022b
METIS/5.1.0-GCCcore-12.2.0
MPC/1.3.1-GCCcore-12.2.0
MUMPS/5.6.1-foss-2022b-metis
SCOTCH/7.0.3-gompi-2022b

```

### CODE REVIEW

**Comment by TopRichard** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic

**Comment by TopRichard** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1

**Comment by boegel** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen4

**Comment by bedroge** [comment]
> bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen4

@boegel this won't work, it depends on foss/2022b.

**Review by bedroge — APPROVED** [review]

**Pull request merged**
