### PR TITLE
don't filter cURL as dependency in EasyBuild

### PR DESCRIPTION
**Pull request by laraPPr**
Two builds are failing because cURL is being filtered.
- https://github.com/EESSI/software-layer/pull/299
- https://github.com/EESSI/software-layer/pull/321

### CODE REVIEW

**Comment by laraPPr** [comment]
bot:build repo:eessi-2023.06-software

**Comment by laraPPr** [comment]
bot: build repo:eessi-2023.06-software

**Comment by laraPPr** [comment]
This error occured on aarch64-neoverse_v1, x86_64-amd-zen3, x86_64-intel-skylake_avx512. For the other architectures it seems to have worked. Bot says it failed but no log were coppied to the bot-build-logs.
```
== 2023-09-04 14:15:18,839 build_log.py:267 INFO FAILED: Installation ended unsuccessfully (build directory: /tmp/bot/easybuild/build/ReFrame/4.2.0/system-system): build failed (first 300 chars): Unexpected error occurred when trying to download https://github.com/reframe-hpc/reframe/archive/v4.2.0.tar.gz to /tmp/bot/easybuild/sources/r/ReFrame/extensions/v4.2.0.tar.gz: 'Failed to write to /tmp/bot/easybuild/sources/r/ReFrame/extensions/v4.2.0.tar.gz: The read operation timed out' (took 15 secs)
```

**Comment by boegel** [comment]
@laraPPr That download problem seems to be a temporary glitch with GitHub, so we should probably just try again there (and maybe also improve the way that sources are shared between builds, but that can be dealt with later).

The builds are marked as failed because the `git` installations are not being redone, since they are not listed in the easystack files (while ReFrame and CMake are), so we will need to explicitly include `git` in the easystack files:

* in `eessi-2023.06-eb-4.7.2-2021a.yml` we need to add `git-2.32.0-GCCcore-10.3.0-nodocs.eb`
* in `eessi-2023.06-eb-4.7.2-2021b.yml` we need to add `git-2.33.1-GCCcore-11.2.0-nodocs.eb`

**Comment by laraPPr** [comment]
bot: build repo:eessi-2023.06-software

**Comment by boegel** [comment]
bot: build repo:eessi-2023.06-software arch:x86_64-amd-zen3
bot: build repo:eessi-2023.06-software arch:aarch64-generic
bot: build repo:eessi-2023.06-software arch:aarch64-neoverse_n1
bot: build repo:eessi-2023.06-software arch:aarch64-neoverse_v1

**Comment by boegel** [comment]
`aarch64` build nodes failed to spin us, `x86_64-amd-zen3` failed because of flake download from GitHub currently, so I gave those a kick...

**Comment by laraPPr** [comment]
job 7123 failed because of git issue so retriggering it

**Comment by laraPPr** [comment]
bot: build repo:eessi-2023.06-software arch:aarch64-neoverse_n1

**Comment by laraPPr** [comment]
Error of current [git issue](https://www.githubstatus.com/incidents/frdfpnnt85s8)
```
== 2023-09-05 09:11:58,117 build_log.py:171 ERROR EasyBuild crashed with an error (at easybuild/tools/build_log.py:111 in caller_info): Build of /cvmfs/pilot.eessi-hpc.org/versions/2023.06/software/linux/aarch64/neoverse_n1/software/EasyBuild/4.7.2/easybuild/easyconfigs/g/git/git-2.32.0-GCCcore-10.3.0-nodocs.eb failed (err: 'build failed (first 300 chars): Unexpected error occurred when trying to download https://github.com/git/git/archive/v2.32.0.tar.gz to /tmp/bot/easybuild/sources/g/git/v2.32.0.tar.gz: IncompleteRead(688128 bytes read)') (at easybuild/main.py:174 in build_and_install_software)
```

**Comment by laraPPr** [comment]
bot: build repo:eessi-2023.06-software arch:aarch64-neoverse_n1

**Comment by laraPPr** [comment]
bot: build repo:eessi-2023.06-software arch:x86_64/intel/haswell

**Comment by boegel** [comment]
bot: build repo:eessi-2023.06-software arch:x86_64/intel/haswell

**Review by boegel — APPROVED** [review]

**Pull request merged**
