### PR TITLE
{2023.06}[foss/2021b] GROMACS v2021.5

### PR DESCRIPTION
**Pull request by laraPPr**

### CODE REVIEW

**Comment by laraPPr** [comment]
bot: build repo:eessi-2023.06-software

**Comment by bedroge** [comment]
For job 5800, there's a bunch of failing tests:
```
=========================== short test summary info ============================
FAILED fft/tests/test_pocketfft.py::TestFFT1D::test_identity - AssertionError: 
FAILED fft/tests/test_pocketfft.py::TestFFT1D::test_ifft[None] - AssertionErr...
FAILED fft/tests/test_pocketfft.py::TestFFT1D::test_ifft[backward] - Assertio...
FAILED fft/tests/test_pocketfft.py::TestFFT1D::test_ifft[ortho] - AssertionEr...
FAILED fft/tests/test_pocketfft.py::TestFFT1D::test_ifft[forward] - Assertion...
FAILED fft/tests/test_pocketfft.py::TestFFT1D::test_ifft2 - AssertionError: 
FAILED fft/tests/test_pocketfft.py::TestFFT1D::test_ifftn - AssertionError: 
FAILED fft/tests/test_pocketfft.py::TestFFT1D::test_irfft2 - AssertionError: 
FAILED fft/tests/test_pocketfft.py::TestFFT1D::test_irfftn - AssertionError: 
FAILED fft/tests/test_pocketfft.py::TestFFT1D::test_all_1d_norm_preserving - ...
FAILED fft/tests/test_pocketfft.py::TestFFT1D::test_dtypes[float16] - Asserti...
FAILED fft/tests/test_pocketfft.py::TestFFT1D::test_dtypes[float32] - Asserti...
FAILED fft/tests/test_pocketfft.py::TestFFT1D::test_dtypes[float64] - Asserti...
FAILED fft/tests/test_pocketfft.py::TestFFT1D::test_dtypes[float128] - Assert...
FAILED polynomial/tests/test_classes.py::test_bad_conditioned_fit[Polynomial]
FAILED polynomial/tests/test_classes.py::test_bad_conditioned_fit[Legendre]
FAILED polynomial/tests/test_classes.py::test_bad_conditioned_fit[Chebyshev]
FAILED polynomial/tests/test_classes.py::test_bad_conditioned_fit[Laguerre]
FAILED polynomial/tests/test_classes.py::test_bad_conditioned_fit[Hermite] - ...
FAILED polynomial/tests/test_classes.py::test_bad_conditioned_fit[HermiteE]
= 20 failed, 14429 passed, 81 skipped, 1253 deselected, 22 xfailed, 79 warnings in 157.76s (0:02:37) =
```

**Comment by laraPPr** [comment]
bot: build repo:eessi-2023.06-software arch:x86_64-generic

**Comment by laraPPr** [comment]
> For job 5800, there's a bunch of failing tests:
> 
> ```
> =========================== short test summary info ============================
> FAILED fft/tests/test_pocketfft.py::TestFFT1D::test_identity - AssertionError: 
> FAILED fft/tests/test_pocketfft.py::TestFFT1D::test_ifft[None] - AssertionErr...
> FAILED fft/tests/test_pocketfft.py::TestFFT1D::test_ifft[backward] - Assertio...
> FAILED fft/tests/test_pocketfft.py::TestFFT1D::test_ifft[ortho] - AssertionEr...
> FAILED fft/tests/test_pocketfft.py::TestFFT1D::test_ifft[forward] - Assertion...
> FAILED fft/tests/test_pocketfft.py::TestFFT1D::test_ifft2 - AssertionError: 
> FAILED fft/tests/test_pocketfft.py::TestFFT1D::test_ifftn - AssertionError: 
> FAILED fft/tests/test_pocketfft.py::TestFFT1D::test_irfft2 - AssertionError: 
> FAILED fft/tests/test_pocketfft.py::TestFFT1D::test_irfftn - AssertionError: 
> FAILED fft/tests/test_pocketfft.py::TestFFT1D::test_all_1d_norm_preserving - ...
> FAILED fft/tests/test_pocketfft.py::TestFFT1D::test_dtypes[float16] - Asserti...
> FAILED fft/tests/test_pocketfft.py::TestFFT1D::test_dtypes[float32] - Asserti...
> FAILED fft/tests/test_pocketfft.py::TestFFT1D::test_dtypes[float64] - Asserti...
> FAILED fft/tests/test_pocketfft.py::TestFFT1D::test_dtypes[float128] - Assert...
> FAILED polynomial/tests/test_classes.py::test_bad_conditioned_fit[Polynomial]
> FAILED polynomial/tests/test_classes.py::test_bad_conditioned_fit[Legendre]
> FAILED polynomial/tests/test_classes.py::test_bad_conditioned_fit[Chebyshev]
> FAILED polynomial/tests/test_classes.py::test_bad_conditioned_fit[Laguerre]
> FAILED polynomial/tests/test_classes.py::test_bad_conditioned_fit[Hermite] - ...
> FAILED polynomial/tests/test_classes.py::test_bad_conditioned_fit[HermiteE]
> = 20 failed, 14429 passed, 81 skipped, 1253 deselected, 22 xfailed, 79 warnings in 157.76s (0:02:37) =
> ```

We've been comming accross test failing when installing on aarch64-neoverse_v1 often but for some reason it did not pop up when installing QuantumEspresso https://github.com/EESSI/software-layer/pull/289. And it is not really clear why.

**Comment by laraPPr** [comment]
bot: build repo:eessi-2023.06-software arch:aarch64-neoverse_v1

**Comment by laraPPr** [comment]
They are all numpy tests that have failed in this list. I've also been going through the log of successful installs of GROMACS in 2023.06 and in those logs I can't find any of these numpy tests.

**Comment by laraPPr** [comment]
But before these numpy test there are a bunch of other fails. Example:
`types.py:182 DEBUG Non-trivial value type checking of easyconfig value '[('binutils', '2.37')]': FAILED`
I do not really know where this types.py is coming from and I also cannot find any reference to types.py in successful GROMACS logs.

**Comment by bedroge** [comment]
> But before these numpy test there are a bunch of other fails. Example: `types.py:182 DEBUG Non-trivial value type checking of easyconfig value '[('binutils', '2.37')]': FAILED` I do not really know where this types.py is coming from and I also cannot find any reference to types.py in successful GROMACS logs.

This is an internal Easybuild message coming from https://github.com/easybuilders/easybuild-framework/blob/develop/easybuild/framework/easyconfig/types.py#L138. But looking at other build logs, this is quite normal.

So it's really about the failing tests, and all them seem to fail due to a too large numerical difference between the actual and expected result: 
```
>           assert_allclose(np.fft.ifft(np.fft.fft(x[0:i])), x[0:i],
                            atol=1e-12)
E           AssertionError: 
E           Not equal to tolerance rtol=1e-07, atol=1e-12
```
I'm not sure if this is to be expected on these CPUs, but if so, we could change the tolerance.

**Comment by bedroge** [comment]
I tried adapting the `numpy` version in this `SciPy-bundle` to 1.20.3, which is the same one as used by `SciPy-bundle/2021.05-foss-2021a` (which was built without issues in https://github.com/EESSI/software-layer/pull/288), but even then several tests are failing. So, I suspect it's caused by one of the underlying libraries, e.g. `OpenBLAS`.

**Comment by laraPPr** [comment]
> > But before these numpy test there are a bunch of other fails. Example: `types.py:182 DEBUG Non-trivial value type checking of easyconfig value '[('binutils', '2.37')]': FAILED` I do not really know where this types.py is coming from and I also cannot find any reference to types.py in successful GROMACS logs.
> 
> This is an internal Easybuild message coming from https://github.com/easybuilders/easybuild-framework/blob/develop/easybuild/framework/easyconfig/types.py#L138. But looking at other build logs, this is quite normal.
> 
> So it's really about the failing tests, and all them seem to fail due to a too large numerical difference between the actual and expected result:
> 
> ```
> >           assert_allclose(np.fft.ifft(np.fft.fft(x[0:i])), x[0:i],
>                             atol=1e-12)
> E           AssertionError: 
> E           Not equal to tolerance rtol=1e-07, atol=1e-12
> ```
> 
> I'm not sure if this is to be expected on these CPUs, but if so, we could change the tolerance.

And is than the numpy install that fails?

**Comment by bedroge** [comment]
> > > But before these numpy test there are a bunch of other fails. Example: `types.py:182 DEBUG Non-trivial value type checking of easyconfig value '[('binutils', '2.37')]': FAILED` I do not really know where this types.py is coming from and I also cannot find any reference to types.py in successful GROMACS logs.
> > 
> > 
> > This is an internal Easybuild message coming from https://github.com/easybuilders/easybuild-framework/blob/develop/easybuild/framework/easyconfig/types.py#L138. But looking at other build logs, this is quite normal.
> > So it's really about the failing tests, and all them seem to fail due to a too large numerical difference between the actual and expected result:
> > ```
> > >           assert_allclose(np.fft.ifft(np.fft.fft(x[0:i])), x[0:i],
> >                             atol=1e-12)
> > E           AssertionError: 
> > E           Not equal to tolerance rtol=1e-07, atol=1e-12
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I'm not sure if this is to be expected on these CPUs, but if so, we could change the tolerance.
> 
> And is than the numpy install that fails?

Yep, it's failing on the `numpy` extension of `SciPybundle/2021.10/foss-2021b`.

**Comment by bedroge** [comment]
> Can I try to get install `SciPy-bundle/2021.10-foss-2021b` on its own? Via another pull request only targetting neoverse_v1 that than gets deployed if successful but not merged.

Sure! Since the issue is not related to / caused by `GROMACS` itself, perhaps it's better to debug it in a separate PR for just `SciPy-bundle` anyway. Once we've figured it out, we can continue with `GROMACS`.

**Comment by laraPPr** [comment]
First resolve this for arch:aarch64/neoverse_v1
https://github.com/EESSI/software-layer/pull/306

**Comment by laraPPr** [comment]
bot: build repo:eessi-2023.06-software arch:aarch64-neoverse_v1

**Comment by laraPPr** [comment]
@boegel Do I need to create new tarballs for all the architectures since they include SciPy-bundle which now deployed for all architectures? 
see:
- https://github.com/EESSI/software-layer/pull/306

**Comment by laraPPr** [comment]
bot: build arch:x86_64/generic repo:eessi-2023.06-software
bot: build arch:x86_64/intel/haswell repo:eessi-2023.06-software
bot: build arch:x86_64/intel/skylake_avx512 repo:eessi-2023.06-software
bot: build arch:x86_64/amd/zen2 repo:eessi-2023.06-software
bot: build arch:x86_64/amd/zen3 repo:eessi-2023.06-software
bot: build arch:aarch64/generic repo:eessi-2023.06-software
bot: build arch:aarch64/neoverse_n1 repo:eessi-2023.06-software

**Review by boegel — APPROVED** [review]

**Pull request merged**
