### PR TITLE
{2023.06}[2023a] mpl-ascii v0.10.0

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/a64fx
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen4
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1

**Comment by boegel** [comment]
rebuild is needed since the tarballs produced above include `2023.06/init/easybuild/eb_hooks.py` and `2023.06/init/eessi_environment_variables`, which is incorrect - caused by triggering the builds while the tarballs for #772 were deployed but the PR wasn't merged yet...

bot: build repo:eessi.io-2023.06-software arch:x86_64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen4
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1

**Comment by boegel** [comment]
Have to redo the A64FX build, since last one still includes `2023.06/init/easybuild/eb_hooks.py` and `2023.06/init/eessi_environment_variables`, which is incorrect - caused by triggering the builds while the tarballs for https://github.com/EESSI/software-layer/pull/772 were deployed but the PR wasn't merged yet...

bot: build repo:eessi.io-2023.06-software arch:aarch64/a64fx

**Review by casparvl — COMMENTED** [review]
Lgtm

**Review by casparvl — APPROVED** [review]

**Pull request merged**
