### PR TITLE
{2023.06}[2023a,zen4] ALL 0.9.2

### PR DESCRIPTION
**Pull request by laraPPr**

### CODE REVIEW

**Comment by laraPPr** [comment]
bot: build repo:eessi.io-2023.06-software arch:zen4

**Comment by boegel** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/a64fx

**Comment by boegel** [comment]
I've cancelled the job for `a64fx`, since too many software installations are still missing there, we'll need to close the gap more gradually...

**Comment by boegel** [comment]
Staging PR merged for `zen4`, so merging this PR

**Review by boegel — APPROVED** [review]

**Pull request merged**
