### PR TITLE
Rebuild GObject-Introspection/1.76.1-GCCcore-12.3.0 for A64FX

### PR DESCRIPTION
**Pull request by Neves-P**
The fix in #646 did not apply to `a64fx`, so we are rebuilding `GObject-Introspection/1.76.1-GCCcore-12.3.0`.

This should let the work in #680 carry on.

Before triggering the rebuild, I need to manually remove this installation from the stratum 0.

### CODE REVIEW

**Comment by Neves-P** [comment]
```
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/a64fx/software/GObject-Introspection
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/a64fx/modules/all/GObject-Introspection
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/a64fx/modules/devel/GObject-Introspection/
```

@boegel, should be ready to rebuild, you can trigger it when ready 😄

**Comment by boegel** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/a64fx

**Comment by boegel** [comment]
@Neves-P It seems like Deucalion workernodes are down currently, but the job to rebuild `GObject-Introspection` is in the queue

**Comment by Neves-P** [comment]
Looks like the build went fine 🎉 

I suppose the automatic ingestion will work fine because the directories are not there, but I can also do it manually if necessary.

**Comment by boegel** [comment]
@Neves-P deploy triggered, staging PR should show up very soon

**Review by boegel — APPROVED** [review]

**Pull request merged**
