### PR TITLE
{2023.06}[foss/2023a] CUDA-Samples v12.1 w/ CUDA 12.1.1 (rebuild)

### PR DESCRIPTION
**Pull request by casparvl**
requires:
* #720

### CODE REVIEW

**Comment by casparvl** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2 accel:nvidia/cc80

**Comment by casparvl** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2 accel:nvidia/cc80

**Comment by casparvl** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2 accel:nvidia/cc80

**Comment by casparvl** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2 accel:nvidia/cc80
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3 accel:nvidia/cc80

**Comment by casparvl** [comment]
For pr `19866`:

```
[casparvl@login1 bin]$ readelf -d vectorAdd | grep RPATH
 0x000000000000000f (RPATH)              Library rpath: [/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/accel/nvidia/cc80/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/accel/nvidia/cc80/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1/lib64:$ORIGIN:$ORIGIN/../lib:$ORIGIN/../lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/accel/nvidia/cc80/software/CUDA/12.1.1/bin/../targets/x86_64-linux/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/GCCcore/12.3.0/lib/gcc/x86_64-pc-linux-gnu/12.3.0:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/GCCcore/12.3.0/lib/gcc/x86_64-pc-linux-gnu/12.3.0/../../../../lib64:/cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64/lib/../lib64:/cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64/usr/lib/../lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/GCCcore/12.3.0/lib/gcc/x86_64-pc-linux-gnu/12.3.0/../../..:/cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64/lib:/cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64/usr/lib]
[casparvl@login1 bin]$ pwd
/project/def-users/SHARED/jobs/2024.09/pr_715/19866/2023.06/software/linux/x86_64/amd/zen2/accel/nvidia/cc80/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1/bin
```

This looks good, it lists the correct CUDA, from the `accel` prefix.

**Comment by casparvl** [comment]
Same for pr `19867`:

```
$ readelf -d vectorAdd | grep RPATH
 0x000000000000000f (RPATH)              Library rpath: [/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/accel/nvidia/cc80/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/accel/nvidia/cc80/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1/lib64:$ORIGIN:$ORIGIN/../lib:$ORIGIN/../lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/accel/nvidia/cc80/software/CUDA/12.1.1/bin/../targets/x86_64-linux/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/GCCcore/12.3.0/lib/gcc/x86_64-pc-linux-gnu/12.3.0:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/GCCcore/12.3.0/lib/gcc/x86_64-pc-linux-gnu/12.3.0/../../../../lib64:/cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64/lib/../lib64:/cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64/usr/lib/../lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/GCCcore/12.3.0/lib/gcc/x86_64-pc-linux-gnu/12.3.0/../../..:/cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64/lib:/cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64/usr/lib]
```
Also looks good I think.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
both staging PRs merged, so I'll go ahead and merge this

**Pull request merged**
