### PR TITLE
Try to retrigger FFTW.MPI build issue for 2022a

### PR DESCRIPTION
**Pull request by casparvl**
See if we can trigger a rebuild without the FFTW.MPI test hook, to see if we can retrigger the issue on the new Magic Castle cluster

DONT MERGE THIS PR!

### CODE REVIEW

**Comment by casparvl** [comment]
bot: build repo:eessi-hpc.org-2023.06-software arch:aarch64/neoverse_v1

**Comment by casparvl** [comment]
Ok, so it is not so easy to retrigger a build that has already been ingested...
```
(last error: [Errno 13] Permission denied: '/cvmfs/pilot.eessi-hpc.org/versions/2023.06/software/linux/aarch64/neoverse_v1/software/FFTW.MPI/3.3.10-gompi-2022a/lib/libfftw3.a') (at easybuild/tools/filetools.py:1835 in adjust_permissions)
```
I guess that's because that file exists. Thus it doesn't end up in the writeable overlay, but is actually trying to change the existing (read-only) file.

Does anyone have suggestions on how to retrigger this build with the bot...?

**Comment by casparvl** [comment]
bot: build repo:eessi-hpc.org-2023.06-software arch:aarch64/neoverse_v1

**Comment by casparvl** [comment]
bot: build repo:eessi-hpc.org-2023.06-software arch:aarch64/neoverse_v1

**Comment by casparvl** [comment]
Hm...
```
--------------------------------------------------------------
     MPI FFTW transforms passed 10 tests, 1 CPU
--------------------------------------------------------------
perl -w ../tests/check.pl --verbose --random --maxsize=10000 -c=10  --mpi "mpirun -np 2 `pwd`/mpi-bench"
Executing "mpirun -np 2 /tmp/bot/easybuild/build/FFTWMPI/3.3.10/gompi-2022a/fftw-3.3.10/mpi/mpi-bench --verbose=1   --verify 'obr[40x7' --verify 'ibr[40x7' --verify 'obc[40x7' --verify 'ibc[40x7' --verify 'ofc[40x7' --verify 'ifc[40x7' --verify 'ofr]8x10x11x7' --verify 'ifr]8x10x11x7' --verify 'obc]8x10x11x7' --verify 'ibc]8x10x11x7' --verify 'ofc]8x10x11x7' --verify 'ifc]8x10x11x7' --verify 'okd8o11x4o11x12o10v1' --verify 'ikd8o11x4o11x12o10v1' --verify 'obr[2x5x11' --verify 'ibr[2x5x11' --verify 'obc[2x5x11' --verify 'ibc[2x5x11' --verify 'ofc[2x5x11' --verify 'ifc[2x5x11' --verify 'ok[5e11x6e11x6e01x8e00v3' --verify 'ik[5e11x6e11x6e01x8e00v3' --verify 'okd9e11x13e10x7hx9o11' --verify 'ikd9e11x13e10x7hx9o11' --verify 'obr[4x6x5x8' --verify 'ibr[4x6x5x8' --verify 'obc[4x6x5x8' --verify 'ibc[4x6x5x8' --verify 'ofc[4x6x5x8' --verify 'ifc[4x6x5x8'"
obr[40x7 3.56943e-16 6.36946e-16 3.62614e-16
ibr[40x7 3.71849e-16 6.36946e-16 3.4114e-16
obc[40x7 2.69428e-16 8.49261e-16 3.69264e-16
ibc[40x7 3.18407e-16 6.36946e-16 4.38655e-16
ofc[40x7 4.01251e-16 6.36946e-16 3.78697e-16
ifc[40x7 3.21605e-16 6.36946e-16 4.37138e-16
ofr]8x10x11x7 3.64956e-16 2.53488e-15 5.81605e-16
ifr]8x10x11x7 3.77969e-16 2.89701e-15 5.1962e-16
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 1 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
FAILED mpirun -np 2 /tmp/bot/easybuild/build/FFTWMPI/3.3.10/gompi-2022a/fftw-3.3.10/mpi/mpi-bench:  --verify 'obr[40x7' --verify 'ibr[40x7' --verify 'obc[40x7' --verify 'ibc[40x7' --verify 'ofc[40x7' --verify 'ifc[40x7' --verify 'ofr]8x10x11x7' --verify 'ifr]8x10x11x7' --verify 'obc]8x10x11x7' --verify 'ibc]8x10x11x7' --verify 'ofc]8x10x11x7' --verify 'ifc]8x10x11x7' --verify 'okd8o11x4o11x12o10v1' --verify 'ikd8o11x4o11x12o10v1' --verify 'obr[2x5x11' --verify 'ibr[2x5x11' --verify 'obc[2x5x11' --verify 'ibc[2x5x11' --verify 'ofc[2x5x11' --verify 'ifc[2x5x11' --verify 'ok[5e11x6e11x6e01x8e00v3' --verify 'ik[5e11x6e11x6e01x8e00v3' --verify 'okd9e11x13e10x7hx9o11' --verify 'ikd9e11x13e10x7hx9o11' --verify 'obr[4x6x5x8' --verify 'ibr[4x6x5x8' --verify 'obc[4x6x5x8' --verify 'ibc[4x6x5x8' --verify 'ofc[4x6x5x8' --verify 'ifc[4x6x5x8'
```

**Comment by casparvl** [comment]
bot: build repo:eessi-hpc.org-2023.06-software arch:aarch64/neoverse_v1

**Comment by boegel** [comment]
@casparvl Did we reach a conclusion here?

**Comment by casparvl** [comment]
Not really. As you can see, the bot is often reporting 'UNKNOWN' after 24h. Not sure what's going wrong in those cases? Does it loose sight of the job somehow?

The one time it did run there was some error in the test, but not like I've seen before (I think). It's... strange...

**Comment by boegel** [comment]
The "unknown" state is what the bot will currently report when the build job has timed out after 24h, so based on the timestamps that's likely what's going on here...

**Comment by casparvl** [comment]
I'm closing this PR. This still targetted the pilot, it's not so relevant anymore. We _could_ try to see if we can get rid of the `FFTW.MPI` hook now that we reinstalled `OpenMPI` in `software.eessi.io`. I'd love to see if that's possible, but since the bot currently doesn't work, I guess it'll have to wait.

**Pull request closed without merging**
