### PR TITLE
{2023.06}[foss/2023a] SAMtools v1.18

### PR DESCRIPTION
**Pull request by Neves-P**
### Please do not merge this PR!

This is a test PR to see how building `SAMtools` v 1.18 goes. I plan to do a live demo of the build -> deploy workflow to EESSI with the bot on the EasyBuild user meeting on 26/04/2024. As such, I will close this PR even if SAMtools successfully builds for all architectures so that I can repeat the process then.

### CODE REVIEW

**Comment by boegel** [comment]
@Neves-P If you want to play safe, you could close the PR already, but continue to trigger builds with the bot, which will probably work

**Comment by Neves-P** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic

**Comment by Neves-P** [comment]
> @Neves-P If you want to play safe, you could close the PR already, but continue to trigger builds with the bot, which will probably work

Didn't think of that, but good idea, thanks!

**Comment by boegel** [comment]
FYI: There's a problem currently with the `neoverse-n1` partition, which is also used for `aarch64-generic`

**Comment by Neves-P** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512

**Comment by Neves-P** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1

**Pull request closed without merging**
