### PR TITLE
{2023.06}[foss/2021a] GROMACS v2021.3

### PR DESCRIPTION
**Pull request by laraPPr**

### CODE REVIEW

**Comment by laraPPr** [comment]
bot: build arch:x86_64/generic repo:eessi-2023.06-software

**Comment by laraPPr** [comment]
bot: build arch:x86_64/generic repo:eessi-2023.06-software

**Comment by laraPPr** [comment]
bot: build arch:x86_64/intel/haswell repo:eessi-2023.06-software
bot: build arch:x86_64/intel/skylake_avx512 repo:eessi-2023.06-software
bot: build arch:x86_64/amd/zen2 repo:eessi-2023.06-software
bot: build arch:x86_64/amd/zen3 repo:eessi-2023.06-software
bot: build arch:aarch64/generic repo:eessi-2023.06-software
bot: build arch:aarch64/neoverse_n1 repo:eessi-2023.06-software
bot: build arch:aarch64/neoverse_v1 repo:eessi-2023.06-software

**Comment by boegel** [comment]
Ingestion triggered for all 8 tarballs...

**Comment by laraPPr** [comment]
Something weird happened the bot says it ingested the failed tarball for `arch:x86_64-generic` and not the succesfull one
succefull tarball: eessi-2023.06-software-linux-x86_64-generic-1687955624.tar.gz
failed tarball: eessi-2023.06-software-linux-x86_64-generic-1687944635.tar.gz
ingested tarball: eessi-2023.06-software-linux-x86_64-generic-1687944635.tar.gz

**Comment by boegel** [comment]
> Something weird happened the bot says it ingested the failed tarball for `arch:x86_64-generic` and not the succesfull one succefull tarball: eessi-2023.06-software-linux-x86_64-generic-1687955624.tar.gz failed tarball: eessi-2023.06-software-linux-x86_64-generic-1687944635.tar.gz ingested tarball: eessi-2023.06-software-linux-x86_64-generic-1687944635.tar.gz

`eessi-2023.06-software-linux-x86_64-generic-1687955624.tar.gz` was originally marked as failed because this PR originally also included an included entry to `eessi-2023.06-eb-4.7.2-2021b.yml` (and hence not all checks for the tarball passed).
Once that was removed from this PR, `eessi-2023.06-software-linux-x86_64-generic-1687955624.tar.gz`  was actually correctly marked as `SUCCESS` when the check was performed during the `deploy` phase, since it actually included everything needed for `GROMACS/2021.3-foss-2021a` in `x86_64/generic`.

So, it looks weird, but it actually worked correctly. :)

**Comment by trz42** [comment]
> `eessi-2023.06-software-linux-x86_64-generic-1687955624.tar.gz` was originally marked as failed because this PR originally also included an included entry to `eessi-2023.06-eb-4.7.2-2021b.yml` (and hence not all checks for the tarball passed). Once that was removed from this PR, `eessi-2023.06-software-linux-x86_64-generic-1687955624.tar.gz` was actually correctly marked as `SUCCESS` when the check was performed during the `deploy` phase, since it actually included everything needed for `GROMACS/2021.3-foss-2021a` in `x86_64/generic`.
> 
> So, it looks weird, but it actually worked correctly. :)

Interesting case:
- small typo in original PR, which should actually not be included $\Longrightarrow$ what if there was no typo?
- leads to failed PR as a whole, but what it was intended to built succeeded
- outdated/lacking code in bot deploy procedure leading it to be uploaded (albeit it seemed to have failed)

In NESSI we make an effort to detect such issues (not sure we would have catched this one) using a checklist before we set the `bot:deploy` label.

# NESSI Checklist for building: 

  - [ ]  Check whether builds for all required architectures succeeded (SUCCESS message + reasonably sized tarball)
  - [ ]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
  - [ ]  Assess if all requested changes are sound (checking files changed on GitHub.com)
  - [ ]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
  - [ ]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

The third check might have revealed something is a bit off with the PR.

Some of the checks may be better performed before triggering the builds. Some tests could also be automated (check that there is no typo, pre-build analysis of missing packages).

Also, I try to force myself adding some description to a PR. May be a bit duplication / additional effort. However, may help in detecting issues as early as possible.

**Comment by boegel** [comment]
The typo in the easystack file could have been caught early by the bot, it could have done a `eb --missing`, which would have failed.

But if there was no typo, and just an accidental change in two rather than one easystack file, that's more difficult to catch automatically...
Unless we make it a policy that each PR should only touch one easystack file, not sure if that's too limiting for some edge cases.

No need to block this PR though, especially since these installations are deployed already, so I'll merge this.
We can open issues for things to improve either here in `software-layer` repo, or in the bot repo.

**Review by boegel — APPROVED** [review]

**Comment by trz42** [comment]
> No need to block this PR though, especially since these installations are deployed already, so I'll merge this.

Sure. More food for thought.

**Pull request merged**
