### PR TITLE
{2023.06}[GCCcore/12.3.0] FFmpeg 6.0

### PR DESCRIPTION
**Pull request by Neves-P**
First installing FFmpeg v6.0 as a necessary dependency of #404
```
7 out of 34 required modules missing:

* ffnvcodec/12.0.16.0 (ffnvcodec-12.0.16.0.eb)
* x264/20230226-GCCcore-12.3.0 (x264-20230226-GCCcore-12.3.0.eb)
* LAME/3.100-GCCcore-12.3.0 (LAME-3.100-GCCcore-12.3.0.eb)
* Yasm/1.3.0-GCCcore-12.3.0 (Yasm-1.3.0-GCCcore-12.3.0.eb)
* x265/3.5-GCCcore-12.3.0 (x265-3.5-GCCcore-12.3.0.eb)
* SDL2/2.28.2-GCCcore-12.3.0 (SDL2-2.28.2-GCCcore-12.3.0.eb)
* FFmpeg/6.0-GCCcore-12.3.0 (FFmpeg-6.0-GCCcore-12.3.0.eb)
```

### CODE REVIEW

**Comment by Neves-P** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1

**Comment by Neves-P** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3

**Comment by Neves-P** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1

**Comment by Neves-P** [comment]
All builds pass 🎉

**Review by bedroge — APPROVED** [review]

**Comment by bedroge** [comment]
CI is failing for `aarch64/*`, because `EESSI_CPU_FAMILY` is set to `x86_64` on the Github runners, and due to this it's failing to detect that Yasm should be filtered [here](https://github.com/EESSI/software-layer/blob/2023.06-software.eessi.io/configure_easybuild#L31).

**Review by bedroge — APPROVED** [review]

**Pull request merged**
