### PR TITLE
{2023.06}[2023b] OSU-Micro-Benchmarks 7.5 w/ CUDA 12.4.0

### PR DESCRIPTION
**Pull request by bedroge**

### CODE REVIEW

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2 accel:nvidia/cc80

**Comment by bedroge** [comment]
> New job on instance `eessi-bot-mc-aws` for CPU micro-architecture `x86_64-amd-zen2` and accelerator `nvidia/cc80` for repository `eessi.io-2023.06-software` in job dir `/project/def-users/SHARED/jobs/2024.11/pr_831/31482`
> 
> date	job status	comment
> Nov 28 15:36:23 UTC 2024	submitted	job id `31482` awaits release by job manager
> Nov 28 15:37:25 UTC 2024	released	job awaits launch by Slurm scheduler
> Nov 28 15:43:27 UTC 2024	running	job `31482` is running

This failed in the sanity check:
```
== sanity checking...
  >> (non-empty) directory 'libexec/osu-micro-benchmarks/mpi/collective' found: OK
  >> (non-empty) directory 'libexec/osu-micro-benchmarks/mpi/one-sided' found: OK
  >> (non-empty) directory 'libexec/osu-micro-benchmarks/mpi/pt2pt' found: OK
  >> (non-empty) directory 'libexec/osu-micro-benchmarks/mpi/startup' found: OK
  >> (non-empty) directory 'libexec/osu-micro-benchmarks/nccl/collective' found: FAILED
  >> (non-empty) directory 'libexec/osu-micro-benchmarks/nccl/pt2pt' found: FAILED
```

Haven't checked the build logs yet, but it may be related to similar CUDA issues as observed in #828.

**Comment by ocaisa** [comment]
@bedroge This is also ready to deploy?

**Comment by bedroge** [comment]
> @bedroge This is also ready to deploy?

Yep, I see you've just merged the easyconfig, so this should be ready now.

**Review by ocaisa — APPROVED** [review]

**Pull request merged**
