### PR TITLE
{2023.06}[2023b] Cython 3.0.10

### PR DESCRIPTION
**Pull request by bedroge**
This should fix the currently broken CI (see #805), which is complaining about a missing Cython:
```
1 out of 42 required modules missing:

* Cython/3.0.10-GCCcore-13.2.0 (Cython-3.0.10-GCCcore-13.2.0.eb)
```

### CODE REVIEW

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen4

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512

**Review by trz42 — APPROVED** [review]
lgtm

**Comment by trz42** [comment]
All good now.

**Comment by trz42** [comment]
bot: status

**Pull request merged**
