### PR TITLE
rebuild OpenFOAM-10-foss-2023a.eb and OpenFOAM-11-foss-2023a.eb without `-ftree-vectorize`

### PR DESCRIPTION
**Pull request by boegel**
see also https://github.com/easybuilders/easybuild-easyconfigs/issues/20927

### CODE REVIEW

**Comment by boegel** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1

**Review by bedroge — APPROVED** [review]

**Comment by bedroge** [comment]
Ingestion procedure:
```
cvmfs_server transaction software.eessi.io

rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/generic/software/OpenFOAM/10-foss-2023a
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/generic/software/OpenFOAM/11-foss-2023a

rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/neoverse_n1/software/OpenFOAM/10-foss-2023a
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/neoverse_n1/software/OpenFOAM/11-foss-2023a

rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/neoverse_v1/software/OpenFOAM/10-foss-2023a
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/neoverse_v1/software/OpenFOAM/11-foss-2023a

rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/generic/software/OpenFOAM/10-foss-2023a
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/generic/software/OpenFOAM/11-foss-2023a

rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/OpenFOAM/10-foss-2023a
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/OpenFOAM/11-foss-2023a

rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/software/OpenFOAM/10-foss-2023a
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/software/OpenFOAM/11-foss-2023a

rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/OpenFOAM/10-foss-2023a
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/OpenFOAM/11-foss-2023a

rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/OpenFOAM/10-foss-2023a
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/OpenFOAM/11-foss-2023a

cd /cvmfs/software.eessi.io/versions

tar -xzf /srv/tmp/tarballs/eessi-2023.06-software-linux-x86_64-generic-1720264753.tar.gz
tar -xzf /srv/tmp/tarballs/eessi-2023.06-software-linux-x86_64-intel-haswell-1720264786.tar.gz
tar -xzf /srv/tmp/tarballs/eessi-2023.06-software-linux-x86_64-intel-skylake_avx512-1720264497.tar.gz
tar -xzf /srv/tmp/tarballs/eessi-2023.06-software-linux-x86_64-amd-zen2-1720265524.tar.gz
tar -xzf /srv/tmp/tarballs/eessi-2023.06-software-linux-x86_64-amd-zen3-1720264124.tar.gz
tar -xzf /srv/tmp/tarballs/eessi-2023.06-software-linux-aarch64-generic-1720264486.tar.gz
tar -xzf /srv/tmp/tarballs/eessi-2023.06-software-linux-aarch64-neoverse_n1-1720264391.tar.gz
tar -xzf /srv/tmp/tarballs/eessi-2023.06-software-linux-aarch64-neoverse_v1-1720262929.tar.gz

cd

cvmfs_server diff --worktree software.eessi.io > PR638-diff.txt
cvmfs_server publish -m "replace OpenFOAM 10+11, PR 638" software.eessi.io
```

When this is done, we can either close or merge (which will just overwrite things) the staging PRs.

**Comment by bedroge** [comment]
I've completed the manual removal+ingestion, and also merged the staging PRs (then it's in some sense also properly logged that this was ingested).

**Comment by bedroge** [comment]
Staging PRs merged and ingested, the rebuilt versions are available.

**Pull request merged**
