### PR TITLE
{2023.06} foss/2023b

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1

**Comment by boegel** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1

**Comment by ocaisa** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic

**Comment by boegel** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic

**Comment by boegel** [comment]
Installation of `OpenBLAS/0.3.24-GCC-13.2.0` fails on `aarch64/generic` with:

```
gcc -O2 -ftree-vectorize -mcpu=generic -fno-math-errno -O2 -DMAX_STACK_ALLOC=2048 -fopenmp -Wall -DF_INTERFACE_GFORT -fPIC -DDYNAMIC_ARCH -DSMP_SERVER -DUSE_OPENMP -DNO_WARMUP -DMAX_CPU_NUMBER=16 -DMAX_PARALLEL_NUMBER=1 -DBUILD_SINGLE=1 -DBUILD_DOUBLE=1 -DBUILD_COMPLEX=1 -DBUILD_COMPLEX16=1 -DVERSION=\"0.3.24\" -march=armv8.4-a+sve -mtune=neoverse-v1 -UASMNAME -UASMFNAME -UNAME -UCNAME -UCHAR_NAME -UCHAR_CNAME -DASMNAME=strmm_kernel_LT_NEOVERSEV1 -DASMFNAME=strmm_kernel_LT_NEOVERSEV1_ -DNAME=strmm_kernel_LT_NEOVERSEV1_ -DCNAME=strmm_kernel_LT_NEOVERSEV1 -DCHAR_NAME=\"strmm_kernel_LT_NEOVERSEV1_\" -DCHAR_CNAME=\"strmm_kernel_LT_NEOVERSEV1\" -DNO_AFFINITY -DTS=_NEOVERSEV1 -I.. -DBUILD_KERNEL -DTABLE_NAME=gotoblas_NEOVERSEV1 -UDOUBLE  -UCOMPLEX -c -DTRMMKERNEL -UDOUBLE -UCOMPLEX -DLEFT -DTRANSA ../kernel/arm64/strmm_kernel_sve_v1x8.S -o strmm_kernel_LT_NEOVERSEV1.o
...
cc1: warning: switch -mcpu=generic conflicts with -march=armv8.4-a+sve switch
../kernel/arm64/sgemm_kernel_sve_v2x8.S: Assembler messages:
../kernel/arm64/sgemm_kernel_sve_v2x8.S:873: Error: selected processor does not support `dup z7.s,w18'
../kernel/arm64/sgemm_kernel_sve_v2x8.S:874: Error: selected processor does not support `cntw x19'
../kernel/arm64/sgemm_kernel_sve_v2x8.S:878: Error: selected processor does not support `ptrue p0.s'
../kernel/arm64/sgemm_kernel_sve_v2x8.S:140: Error: selected processor does not support `dup z16.s,#0'
```

Somehow `-march=armv8.4-a+sve` is being injected, which clashes with `-mcpu=generic`

The same warning is present in the log for both `OpenBLAS/0.3.23-GCC-12.3.0` and `OpenBLAS/0.3.21-GCC-12.2.0`, but then there are no compiler failures...

It seems like we'll need to strip out `-mcpu=generic` when building OpenBLAS with `DYNAMIC_ARCH=1` on `aarch64/generic`?

@martin-frbg Any idea why we didn't run into build errors with previous versions of OpenBLAS when using `-mcpu=generic` in combination with `DYNAMIC_ARCH=1`?

**Comment by boegel** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic

**Comment by martin-frbg** [comment]
@Uhh, I got a similar question a few weeks ago from some other project, probably spack - is spack involved in your build too by any chance ? IIRC, their build wrapper injected the arch flags for the build host unconditionally in addition to what OpenBLAS' build files used, so when they built for DYNAMIC_ARCH they got a mix of `-march` for each cpu until they hit one of the SVE targets where they actually conflicted.

**Comment by boegel** [comment]
@martin-frbg Spack is not involved in the EESSI project, but I'm not surprised they ran into something similar.

For some reason combining `-mcpu=generic` with `DYNAMIC_ARCH=1` was not an actual problem before (except for the warning being produced), but it is know. Not sure if it's due to a change in OpenBLAS, or in GCC 13.x.

Whatever the reason, it's clear that `-mcpu=generic` doesn't play well with `DYNAMIC_ARCH=1`, so we'll replace it with `-mtune=generic` instead (which is what we use for `x86_64` when building generic binaries)

**Comment by martin-frbg** [comment]
Ok, the SVE GEMM kernels for NeoverseV1 were introduced with 0.3.24 so the "problematic" instructions would not have been encountered with 0.3.23 and earlier.

**Review by bedroge — APPROVED** [review]

**Pull request merged**
