### PR TITLE
{2023.06}[2023a,GPU] LAMMPS 2Aug2023 CUDA 12.1.1

### PR DESCRIPTION
**Pull request by laraPPr**
- [x] https://github.com/EESSI/software-layer/pull/710
- [x] https://github.com/easybuilders/easybuild-easyblocks/pull/3451
- [x] #741

### CODE REVIEW

**Comment by laraPPr** [comment]
Waiting on https://github.com/EESSI/software-layer/pull/710

**Comment by boegel** [comment]
@laraPPr NCCL will also be built as a dependency, we should make sure that the `LICENSE.txt` file is included in the installation there

**Comment by boegel** [comment]
@laraPPr The production bots need to be updated to be aware of the new `accel` filter, so it won't work yet until that's taken care of

**Comment by laraPPr** [comment]
@boegel we are already shipping [NCCL](https://www.eessi.io/docs/available_software/detail/NCCL/)

**Comment by laraPPr** [comment]
Opened a pull request in easybuild-easyblock to add the license of NCCL in the installation

**Comment by boegel** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2 accel:nvidia/cc80

**Comment by boegel** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3 accel:nvidia/cc80

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
I tested this build on our AMD Milan A100 GPU cluster, results (interactive Slurm job with 1x A100, 12 CPU cores):

Did a quick test with the LAMMPS build from https://github.com/EESSI/software-layer/pull/711 on zen3 + A100 (HPC-UGent Tier-2 cluster).

With CPU-only LAMMPS (`LAMMPS/2Aug2023_update2-foss-2023a-kokkos` module), [using rhodo test case from EESSI test suite](https://github.com/EESSI/test-suite/tree/main/eessi/testsuite/tests/apps/lammps/src/rhodo):
* single-core (`lmp -in in.rhodo`): Performance: 0.841 ns/day
* 12-core (`unset OMP_PROC_BIND; mpirun -np 12 lmp -in in.rhodo`): Performance: 8.968 ns/day
* 12-core w/ Kokkos (`lmp -in in.rhodo -kokkos on t 12 -suffix kk -package kokkos newton on neigh half`): Performance: 6.153 ns/day

GPU (`LAMMPS/2Aug2023_update2-foss-2023a-kokkos-CUDA-12.1.1`):
```
export EESSI_OVERRIDE_GPU_CHECK=1
export LD_PRELOAD=/usr/lib64/libcuda.so
lmp -in in.rhodo -kokkos on t 12 g 1 -suffix kk -package kokkos newton on neigh half
```
=> Performance: 34.778 ns/day

🥳 :shipit:

**Comment by boegel** [comment]
ingest PRs merged, deploy under way, so merging this...

**Pull request merged**
