### PR TITLE
use `TARGET=ARMV8` when building OpenBLAS for `aarch64/generic`

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic

**Comment by boegel** [comment]
Hmm, check for missing installations is reporting this for all CPU targets:
```
* jedi/0.19.0-GCCcore-12.3.0 (jedi-0.19.0-GCCcore-12.3.0.eb)
```

How did that happen? 🤔

**Comment by boegel** [comment]
This is actually a great opportunity to strip out `pre_configure_hook_openblas_optarch_generic` and implement it in the OpenBLAS easyblock in EasyBuild instead...

**Comment by boegel** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic

**Comment by boegel** [comment]
@bedroge Should be OK to trigger deployment for this one too?

The `x86_64/generic` builds are unaffected, no need to rebuild those, this is purely for `aarch64/generic`

**Review by bedroge — APPROVED** [review]

**Comment by bedroge** [comment]
Manual ingestion procedure:

```
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/generic/software/OpenBLAS/0.3.21-GCC-12.2.0/
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/generic/software/OpenBLAS/0.3.23-GCC-12.3.0/
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/generic/software/OpenBLAS/0.3.24-GCC-13.2.0/

cd /cvmfs/software.eessi.io/versions

tar xvzf /srv/tmp/tarballs/eessi-2023.06-software-linux-aarch64-generic-1729196442.tar.gz
```

**Pull request merged**
