### PR TITLE
{2023.06}[foss/2023a] CUDA 12.1.1 (rebuild)

### PR DESCRIPTION
**Pull request by casparvl**
requires:
* #735

### CODE REVIEW

**Comment by casparvl** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2 accel:nvidia/cc80

**Comment by casparvl** [comment]
```
== Running parse hook for CUDA-12.1.1.eb...
== CUDA/12.1.1 is already installed (module found), skipping
== No easyconfigs left to be built.
== Build succeeded for 0 out of 0
```
We'll probably need to put it in a `rebuild` EasyStack file since the module exists in the CPU prefix

**Comment by casparvl** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2 accel:nvidia/cc80

**Comment by casparvl** [comment]
Removal fails, we have to updated the `EESSI-remove-software.sh` script as well to make sure the CPU prefix is also on the MODULEPATH. I.e. This section from the `EESSI-install-software.sh`:

```
# if an accelerator target is specified, we need to make sure that the CPU-only modules are also still available
if [ ! -z ${EESSI_ACCELERATOR_TARGET} ]; then
    CPU_ONLY_MODULES_PATH=$(echo $EASYBUILD_INSTALLPATH | sed "s@/accel/${EESSI_ACCELERATOR_TARGET}@@g")/modules/all
    if [ -d ${CPU_ONLY_MODULES_PATH} ]; then
        module use ${CPU_ONLY_MODULES_PATH}
    else
        fatal_error "Derived path to CPU-only modules does not exist: ${CPU_ONLY_MODULES_PATH}"
    fi
fi
```

**Comment by casparvl** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2 accel:nvidia/cc80

**Comment by casparvl** [comment]
Ouch, the `EESSI-remove-installation.sh` script is really too naive for this new setup:

```
                for app in ${rebuild_apps}; do
                    app_dir=${EASYBUILD_INSTALLPATH}/software/${app}
                    app_module=${EASYBUILD_INSTALLPATH}/modules/all/${app}.lua
                    echo_yellow "Removing ${app_dir} and ${app_module}..."
                    rm -rf ${app_dir}
                    rm -rf ${app_module}
```
It just assumes that the module is on the `EASYBUILD_INSTALLPATH`, so this is what it tries to remove:
```
ESC[33mRemoving /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/accel/nvidia/cc80/software/CUDA/12.1.1 and /cvmfs/software.eessi.io/
versions/2023.06/software/linux/x86_64/amd/zen2/accel/nvidia/cc80/modules/all/CUDA/12.1.1.lua...ESC[0m
```
We need to make that more intelligent...

**Comment by casparvl** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2 accel:nvidia/cc80

**Comment by casparvl** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2 accel:nvidia/cc80

**Comment by casparvl** [comment]
Ugh... It seems that the `create_tarball` step doesn't find the software and as a result, the `modules_files_list` remains emtpy (which is normally created at https://github.com/EESSI/software-layer/blob/89c49a0814260dc7e59b4560cbcbb90e4f3dedd8/create_tarball.sh#L71 ). I don't immediately see why or where this goes wrong. One would assume that the addition of the `accel` prefix on https://github.com/EESSI/software-layer/blob/89c49a0814260dc7e59b4560cbcbb90e4f3dedd8/create_tarball.sh#L63 would have been sufficient, but maybe not?

**Comment by casparvl** [comment]
For some reason, the for loop never uses `${cpu_arch_subdir}/accel/${accel_subdir}`... I added a print statement:

```
# consider both CPU-only and accelerator subdirectories
for subdir in ${cpu_arch_subdir} ${cpu_arch_subdir}/accel/${accel_subdir}; do
    echo "Checking subdir ${subdir} for new modulefiles"
    if [ -d ${eessi_version}/software/${os}/${subdir}/modules ]; then
        # module files
        find ${eessi_version}/software/${os}/${subdir}/modules -type f | grep -v '/\.wh\.' >> ${files_list}
        # module symlinks
        find ${eessi_version}/software/${os}/${subdir}/modules -type l | grep -v '/\.wh\.' >> ${files_list}
        # module files and symlinks
        find ${eessi_version}/software/${os}/${subdir}/modules/all -type f -o -type l \
            | grep -v '/\.wh\.' | grep -v '/\.modulerc\.lua' | sed -e 's/.lua$//' | sed -e 's@.*/modules/all/@@g' | sort -u \
            >> ${module_files_list}
    fi

    if [ -d ${eessi_version}/software/${os}/${subdir}/software -a -r ${module_files_list} ]; then
        # installation directories but only those for which module files were created
        # Note, we assume that module names (as defined by 'PACKAGE_NAME/VERSION.lua'
        # using EasyBuild's standard module naming scheme) match the name of the
        # software installation directory (expected to be 'PACKAGE_NAME/VERSION/').
        # If either side changes (module naming scheme or naming of software
        # installation directories), the procedure will likely not work.
        for package_version in $(cat ${module_files_list}); do
            echo "handling ${package_version}"
            ls -d ${eessi_version}/software/${os}/${subdir}/software/${package_version} \
                | grep -v '/\.wh\.' >> ${files_list}
        done
    fi
done
```

but only get:

```
casparvl@x86-64-amd-zen2-node1 ~/EESSI/software-layer $ ./create_tarball.sh /tmp 2023.06 x86_64/amd/zen2 "nvidia/cc80" my_tar.tar.gz
>> tmpdir: /tmp/tmp.JB8VSFR5Ok
>> Collecting list of files/directories to include in tarball via /tmp/software.eessi.io/overlay-upper/versions...
Checking subdir x86_64/amd/zen2 for new modulefiles
casparvl@x86-64-amd-zen2-node1 ~/EESSI/software-layer $
```

As output

**Comment by casparvl** [comment]
If I comment out the body of the loop, it does run both iterations:
```
# consider both CPU-only and accelerator subdirectories
for subdir in ${cpu_arch_subdir} ${cpu_arch_subdir}/accel/${accel_subdir}; do
    echo "Checking subdir ${subdir} for new modulefiles"
#     if [ -d ${eessi_version}/software/${os}/${subdir}/modules ]; then
#         # module files
#         find ${eessi_version}/software/${os}/${subdir}/modules -type f | grep -v '/\.wh\.' >> ${files_list}
#         # module symlinks
#         find ${eessi_version}/software/${os}/${subdir}/modules -type l | grep -v '/\.wh\.' >> ${files_list}
#         # module files and symlinks
#         find ${eessi_version}/software/${os}/${subdir}/modules/all -type f -o -type l \
#             | grep -v '/\.wh\.' | grep -v '/\.modulerc\.lua' | sed -e 's/.lua$//' | sed -e 's@.*/modules/all/@@g' | sort -u \
#             >> ${module_files_list}
#     fi
#
#     if [ -d ${eessi_version}/software/${os}/${subdir}/software -a -r ${module_files_list} ]; then
#         # installation directories but only those for which module files were created
#         # Note, we assume that module names (as defined by 'PACKAGE_NAME/VERSION.lua'
#         # using EasyBuild's standard module naming scheme) match the name of the
#         # software installation directory (expected to be 'PACKAGE_NAME/VERSION/').
#         # If either side changes (module naming scheme or naming of software
#         # installation directories), the procedure will likely not work.
#         for package_version in $(cat ${module_files_list}); do
#             echo "handling ${package_version}"
#             ls -d ${eessi_version}/software/${os}/${subdir}/software/${package_version} \
#                 | grep -v '/\.wh\.' >> ${files_list}
#         done
#     fi
done
```
results in 
```
casparvl@x86-64-amd-zen2-node1 ~/EESSI/software-layer $ ./create_tarball.sh /tmp 2023.06 x86_64/amd/zen2 "nvidia/cc80" my_tar.tar.gz
>> tmpdir: /tmp/tmp.wWlviJD2hK
>> Collecting list of files/directories to include in tarball via /tmp/software.eessi.io/overlay-upper/versions...
Checking subdir x86_64/amd/zen2 for new modulefiles
Checking subdir x86_64/amd/zen2/accel/nvidia/cc80 for new modulefiles
wrote file list to /tmp/tmp.wWlviJD2hK/files.list.txt
wrote module file list to /tmp/tmp.wWlviJD2hK/module_files.list.txt
cp: cannot stat '/tmp/tmp.wWlviJD2hK/module_files.list.txt': No such file or directory
```

Something seems to break the loop?
```

**Comment by casparvl** [comment]
It's probably the `set -e`. It probably just exits the whole script due to one of the `find` statements

**Comment by casparvl** [comment]
Ok, found the culprit:
```
find ${eessi_version}/software/${os}/${subdir}/modules -type f | grep -v '/\.wh\.'
```
the `grep` here returns an exit code of 1 if no match is found. We never encountered this before, so apparently we _always_ had files matching that pattern in the install prefix. But since the CPU only prefix is the first one that is checked, and since nothing is installed there, it doesn't match.

I'll resolve this in this PR to prove we can make it work, but also make a separate PR with the fix later.

**Comment by casparvl** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2 accel:nvidia/cc80

**Comment by casparvl** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2 accel:nvidia/cc80

**Comment by casparvl** [comment]
Weird, it seems consistent here, but not in the other PRs...

**Comment by casparvl** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2 accel:nvidia/cc80

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2 accel:nvidia/cc80

**Comment by ocaisa** [comment]
@casparvl I've included this PR in #735 where I symlink to a CUDA without the `accel/nvidia/cc80` in the path. Including it is just duplication and would require additional changes in our GPU scripts

**Pull request merged**
