### PR TITLE
{2023.06,a64fx}[2023a] OpenMPI 4.1.5

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/a64fx

**Comment by boegel** [comment]
Hmm, first attempt failed when contacting GitHub, hopefully that's just a fluke...

<details>

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/tmp/tmp.jFNGiCYMwk/ebtmp/lib/python3.11/site-packages/easybuild/main.py", line 789, in <module>
    main(prepared_cfg_data=(init_session_state, eb_go, cfg_settings))
  File "/tmp/tmp.jFNGiCYMwk/ebtmp/lib/python3.11/site-packages/easybuild/main.py", line 744, in main
    do_cleanup = process_eb_args(orig_paths, eb_go, cfg_settings, modtool, testing, init_session_state,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/tmp.jFNGiCYMwk/ebtmp/lib/python3.11/site-packages/easybuild/main.py", line 325, in process_eb_args
    eb_file = find_easybuild_easyconfig()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/tmp.jFNGiCYMwk/ebtmp/lib/python3.11/site-packages/easybuild/tools/github.py", line 2494, in find_easybuild_easyconfig
    dev_repo = download_repo(GITHUB_EASYCONFIGS_REPO, branch=GITHUB_DEVELOP_BRANCH,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/tmp.jFNGiCYMwk/ebtmp/lib/python3.11/site-packages/easybuild/tools/github.py", line 397, in download_repo
    status, data = github_api_get_request(lambda x: x.repos[account][repo].branches,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/tmp.jFNGiCYMwk/ebtmp/lib/python3.11/site-packages/easybuild/tools/github.py", line 283, in github_api_get_request
    status, data = url.get(**kwargs)
                   ^^^^^^^^^^^^^^^^^
  File "/tmp/tmp.jFNGiCYMwk/ebtmp/lib/python3.11/site-packages/easybuild/base/rest.py", line 115, in get
    return self.request(self.GET, url, None, headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/tmp.jFNGiCYMwk/ebtmp/lib/python3.11/site-packages/easybuild/base/rest.py", line 176, in request
    conn = self.get_connection(method, url, body, headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/tmp.jFNGiCYMwk/ebtmp/lib/python3.11/site-packages/easybuild/base/rest.py", line 217, in get_connection
    connection = self.opener.open(request)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cvmfs/software.eessi.io/versions/2023.06/compat/linux/aarch64/usr/lib/python3.11/urllib/request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/cvmfs/software.eessi.io/versions/2023.06/compat/linux/aarch64/usr/lib/python3.11/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cvmfs/software.eessi.io/versions/2023.06/compat/linux/aarch64/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/cvmfs/software.eessi.io/versions/2023.06/compat/linux/aarch64/usr/lib/python3.11/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cvmfs/software.eessi.io/versions/2023.06/compat/linux/aarch64/usr/lib/python3.11/urllib/request.py", line 1352, in do_open
    r = h.getresponse()
        ^^^^^^^^^^^^^^^
  File "/cvmfs/software.eessi.io/versions/2023.06/compat/linux/aarch64/usr/lib/python3.11/http/client.py", line 1378, in getresponse
    response.begin()
  File "/cvmfs/software.eessi.io/versions/2023.06/compat/linux/aarch64/usr/lib/python3.11/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/cvmfs/software.eessi.io/versions/2023.06/compat/linux/aarch64/usr/lib/python3.11/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
== Temporary log file in case of crash /tmp/eb-0buupou0/easybuild-d3lc7ofn.log
^[[31mERROR: Installing latest EasyBuild release failed, that's not good... (output: /tmp/tmp.jFNGiCYMwk/eb_install.out)^[[0m
```

</details>

**Comment by boegel** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/a64fx

**Review by trz42 — APPROVED** [review]
Congrats! Some tests for archdetect fail. Maybe worth to fix it a separate PR.

**Pull request merged**
