### PR TITLE
{2023.06,zen4}[2023a] Modflow 6.4.4

### PR DESCRIPTION
**Pull request by casparvl**

### CODE REVIEW

**Comment by casparvl** [comment]
bot: build repo:eessi.io-2023.06-software arch:zen4

**Comment by casparvl** [comment]
Hmmm
```
== fetching files...
  >> download failed: http://glaros.dtc.umn.edu/gkhome/fetch/sw/parmetis/parmetis-4.0.3.tar.gz
  >> download failed: http://glaros.dtc.umn.edu/gkhome/fetch/sw/parmetis/OLD/parmetis-4.0.3.tar.gz
  >> download failed: https://sources.easybuild.io/p/ParMETIS/parmetis-4.0.3.tar.gz
```

Tried locally, same result. Not a hickup either: https://github.com/KarypisLab/ParMETIS/issues/27 Seems that getting it from the github is not a drop-in solution either... https://github.com/easybuilders/easybuild-easyblocks/issues/2961

**Comment by ocaisa** [comment]
bot: build repo:eessi.io-2023.06-software arch:zen4

**Review by ocaisa — APPROVED** [review]

**Comment by casparvl** [comment]
For posterity: it works now, because we manually uploaded the `parmetis-4.0.3.tar.gz` to the right directory on our build cluster... The weblink is still very much broken...

**Comment by ocaisa** [comment]
Tarball has been ingested

**Pull request merged**
