### PR TITLE
{2023.06}[foss/2023a] LAMMPS 2Aug2023

### PR DESCRIPTION
**Pull request by laraPPr**

### CODE REVIEW

**Comment by laraPPr** [comment]
bot: build arch:aarch64/generic repo:eessi.io-2023.06-software

**Comment by laraPPr** [comment]
bot: build arch:aarch64/neoverse_n1 repo:eessi.io-2023.06-software

**Comment by laraPPr** [comment]
`cvmfs/software.eessi.io/versions/2023.06/compat/linux/aarch64/usr/bin/ld: /cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/neoverse_n1/software/ScaFaCoS/1.0.4-foss-2023a/lib64/libfcs_fmm.so.0: undefined reference to `armci_die'

/cvmfs/software.eessi.io/versions/2023.06/compat/linux/aarch64/usr/bin/ld: /cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/neoverse_n1/software/ScaFaCoS/1.0.4-foss-2023a/lib64/libfcs_fmm.so.0: undefined reference to `atomic_fetch_and_add'`

**Comment by laraPPr** [comment]
bot: build arch:x86_64/generic repo:eessi.io-2023.06-software

**Comment by boegel** [comment]
> ScaFaCos seems to be still causing issues on ARM. For LAMMPS-23Jun2022-foss-2021b-kokkos.eb I had removed it as a dependency on ARM. shall do the same for LAMMPS-2Aug2023_update2-foss-2023a-kokkos.eb to see if that fixes the issue.
> 
> ```
> cvmfs/software.eessi.io/versions/2023.06/compat/linux/aarch64/usr/bin/ld: /cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/neoverse_n1/software/ScaFaCoS/1.0.4-foss-2023a/lib64/libfcs_fmm.so.0: undefined reference to `armci_die`
> 
> /cvmfs/software.eessi.io/versions/2023.06/compat/linux/aarch64/usr/bin/ld: /cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/neoverse_n1/software/ScaFaCoS/1.0.4-foss-2023a/lib64/libfcs_fmm.so.0: undefined reference to `atomic_fetch_and_add`
> ```

An approach similar to https://github.com/easybuilders/easybuild-easyconfigs/pull/19164 makes sense to me.

**Comment by laraPPr** [comment]
On x86_64 it is failing due to an RPATH sanity check:

```
== 2024-02-12 17:29:50,489 run.py:725 DEBUG Using default regular expression: (?<![(,-]|\w)(?:error|segmentation fault|failed)(?![(,-]|\.?\w)

== 2024-02-12 17:29:50,490 easyblock.py:3158 DEBUG Failed to determine dynamically linked libraries for /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/generic/software/LAMMPS/2Aug2023_update2-foss-2023a-kokkos/lib64/pkgconfig, so skipping it in RPATH sanity check

== 2024-02-12 17:29:50,490 easyblock.py:3654 WARNING RPATH sanity check failed!

== 2024-02-12 17:29:50,559 build_log.py:171 ERROR EasyBuild crashed with an error (at easybuild/tools/build_log.py:111 in caller_info): Sanity check failed: Library libmdi.so.1 not found for /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/generic/software/LAMMPS/2Aug2023_update2-foss-2023a-kokkos/bin/lmp

Library libmdi.so.1 not found for /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/generic/software/LAMMPS/2Aug2023_update2-foss-2023a-kokkos/bin/lmp

Library libmdi.so.1 not found for /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/generic/software/LAMMPS/2Aug2023_update2-foss-2023a-kokkos/lib/liblammps.so.0

Library libmdi.so.1 not found for /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/generic/software/LAMMPS/2Aug2023_update2-foss-2023a-kokkos/lib64/liblammps.so.0 (at easybuild/framework/easyblock.py:3661 in _sanity_check_step)
```

**Comment by laraPPr** [comment]
bot: build arch:aarch64/generic repo:eessi.io-2023.06-software

**Comment by laraPPr** [comment]
bot: build arch:aarch64/generic repo:eessi.io-2023.06-software

**Comment by laraPPr** [comment]
bot: build arch:x86_64/generic repo:eessi.io-2023.06-software

**Comment by laraPPr** [comment]
bot: build arch:x86_64/intel/haswell repo:eessi.io-2023.06-software
bot: build arch:x86_64/intel/skylake_avx512 repo:eessi.io-2023.06-software
bot: build arch:x86_64/amd/zen2 repo:eessi.io-2023.06-software
bot: build arch:x86_64/amd/zen3 repo:eessi.io-2023.06-software
bot: build arch:aarch64/neoverse_n1 repo:eessi.io-2023.06-software
bot: build arch:aarch64/neoverse_v1 repo:eessi.io-2023.06-software

**Comment by ocaisa** [comment]
bot: build arch:x86_64/intel/haswell repo:eessi.io-2023.06-software
bot: build arch:x86_64/intel/skylake_avx512 repo:eessi.io-2023.06-software
bot: build arch:x86_64/amd/zen2 repo:eessi.io-2023.06-software
bot: build arch:x86_64/amd/zen3 repo:eessi.io-2023.06-software
bot: build arch:aarch64/neoverse_n1 repo:eessi.io-2023.06-software
bot: build arch:aarch64/neoverse_v1 repo:eessi.io-2023.06-software
bot: build arch:x86_64/generic repo:eessi.io-2023.06-software
bot: build arch:aarch64/generic repo:eessi.io-2023.06-software

**Pull request merged**
