### PR TITLE
Only correct the Zen4 software subdirectory if it has not been overridden

### PR DESCRIPTION
**Pull request by ocaisa**
Forcing Zen3 over Zen4 was not respecting `$EESSI_SOFTWARE_SUBDIR_OVERRIDE`

### CODE REVIEW

**Comment by ocaisa** [comment]
Works as intended:
```
[ocaisa@x86-64-amd-zen4-node1 software-layer]$ source init/bash 
Found EESSI repo @ /cvmfs/software.eessi.io/versions/2023.06!
archdetect says x86_64/amd/zen4
Sticking to x86_64/amd/zen3 for now, since optimized installations for AMD Genoa (Zen4) are a work in progress, see https://gitlab.com/eessi/support/-/issues/37 for more information
...
{EESSI 2023.06} [ocaisa@x86-64-amd-zen4-node1 software-layer]$ export EESSI_SOFTWARE_SUBDIR_OVERRIDE=x86_64/amd/zen4
{EESSI 2023.06} [ocaisa@x86-64-amd-zen4-node1 software-layer]$ source init/bash 
Found EESSI repo @ /cvmfs/software.eessi.io/versions/2023.06!
archdetect says x86_64/amd/zen4
Using x86_64/amd/zen4 as software subdirectory.
...
```

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Tests are not happy?

**Comment by ocaisa** [comment]
It's https://github.com/easybuilders/easybuild-easyconfigs/pull/20501 , tricky one to decide what to do about it

**Comment by boegel** [comment]
> It's [easybuilders/easybuild-easyconfigs#20501](https://github.com/easybuilders/easybuild-easyconfigs/pull/20501) , tricky one to decide what to do about it

Filter out `PSM2` in our parse hook (at least in short term)?

**Comment by ocaisa** [comment]
Solution in https://github.com/EESSI/software-layer/pull/574

**Comment by boegel** [comment]
@ocaisa #576 merged, so this just needs a kick?

**Comment by ocaisa** [comment]
@boegel all the open PRs need a sync with the default branch due to the change in the EasyBuild configuration, starting on it now

**Review by boegel — APPROVED** [review]

**Comment by boegel** [comment]
Sorry for overlooking the deployment part... I saw a green light by CI, so I went for it :)

**Pull request merged**
