### PR TITLE
Only run OSU test for now in test step. 

### PR DESCRIPTION
**Pull request by casparvl**
As the test suite is growing, the test step would start taking longer and longer. This is particularly annoying if you want to do small tweaks during a build. 

In the (near) future, we should make some mapping to determine which tests to run for which software installations. E.g. if your tarball contains a new TensorFlow module, you probably want to run the TensorFlow test (`-n TensorFlow`). If your tarball contains OpenMPI, you probably want to run `OSU` and maybe one MPI-based application (i.e. `-n OSU -n GROMACS.*foss` for example).

### CODE REVIEW

**Comment by casparvl** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512

**Comment by ocaisa** [comment]
Something is going wrong, I see a CUDA and PSM2 as missing installations

**Comment by ocaisa** [comment]
PSM2 is coming from https://github.com/easybuilders/easybuild-easyconfigs/pull/20501

**Comment by ocaisa** [comment]
@casparvl This now requires a sync with the default branch for CI to pass

**Comment by casparvl** [comment]
No longer needed, we now have test selection possibilities in https://github.com/EESSI/software-layer/pull/673

**Pull request closed without merging**
