### PR TITLE
{2023.06}{GCCcore/12.3.0} BWA 0.7.17.202209

### PR DESCRIPTION
**Pull request by kErica**
Add latest BWA

### CODE REVIEW

**Comment by kErica** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic

**Comment by kErica** [comment]
bot: build arch:x86_64/generic repo:eessi-hpc.org-2023.06-software

**Comment by kErica** [comment]
bot: build arch:aarch64/generic repo:eessi-hpc.org-2023.06-software

**Comment by bedroge** [comment]
This version of BWA has been added via #468, so closing this PR.

**Pull request closed without merging**
