### PR TITLE
{2023.06}[foss/2022b] QuantumESPRESSO v7.2

### PR DESCRIPTION
**Pull request by TopRichard**
5 out of 46 required modules missing:

* Szip/2.1.1-GCCcore-12.2.0 (Szip-2.1.1-GCCcore-12.2.0.eb)
* libxc/6.1.0-GCC-12.2.0 (libxc-6.1.0-GCC-12.2.0.eb)
* HDF5/1.14.0-gompi-2022b (HDF5-1.14.0-gompi-2022b.eb)
* ELPA/2022.05.001-foss-2022b (ELPA-2022.05.001-foss-2022b.eb)
* QuantumESPRESSO/7.2-foss-2022b (QuantumESPRESSO-7.2-foss-2022b.eb)

### CODE REVIEW

**Comment by TopRichard** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1

**Comment by TopRichard** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell

**Comment by TopRichard** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell

**Comment by TopRichard** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell

**Comment by TopRichard** [comment]
@boegel `libxc-6.1.0-GCC-12.2.0.eb` which is a dependency of `QuantumESPRESSO v7.2` fails to build with error 
`Build of libxc-6.1.0-GCC-12.2.0.eb failed (err: 'build failed (first 300 chars): cmd " make  -j 16 " exited with exit code 2`  on different archs(haswell,aarch64-generic) after setting the parallel = 1 which is removed in https://github.com/easybuilders/easybuild-easyconfigs/pull/18467/files the build succeeds https://github.com/EESSI/software-layer/pull/436#issuecomment-1906499509

**Comment by TopRichard** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1

**Comment by TopRichard** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1

**Comment by TopRichard** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic

**Review by bedroge — APPROVED** [review]

**Comment by bedroge** [comment]
The CI fails for three CPU targets, because the tarballs for those were already created a month ago (as those builds succeeded right away). They now include an outdated Lmod cache that doesn't contain EB 4.9.0 yet, which means that the CI is picking up EB 4.8.2, and that's causing issues when testing the 4.9.0 easystacks. There's an open issue about this already (#167). For now we could wait for something else to be ingested, which should update the Lmod cache and resolve the issue.

**Pull request merged**
