### PR TITLE
take into account accelerator target when configuring EasyBuild

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by trz42** [comment]
We have to tweak the `bot/check-build.sh` so it recognises the modules/software under the different path. For example, see output in https://github.com/boegel/software-layer/pull/33#issuecomment-2356559701 where module files and installed files are shown under 'other'.

**Comment by boegel** [comment]
@trz42 As discussed, this should be good to merge so we can start building CUDA software to be included in `software.eessi.io...

The improvements to `bot/check-build.sh` will be done in a follow-up PR

**Comment by boegel** [comment]
Testing of this was done in https://github.com/boegel/software-layer/pull/33, see [last comment](https://github.com/boegel/software-layer/pull/33#issuecomment-2356559701) for success build of `beagle-lib-4.0.1-GCC-12.3.0-CUDA-12.1.1.eb`

**Review by trz42 — APPROVED** [review]
lgtm, thanks a lot @boegel !

**Pull request merged**
