### PR TITLE
{2023.06}[foss/2021a] SciPy-bundle V2021.05

### PR DESCRIPTION
**Pull request by TopRichard**

### CODE REVIEW

**Comment by TopRichard** [comment]
bot: build repo:eessi-2023.06-software arch:x86_64/generic

**Comment by TopRichard** [comment]
bot: build repo:eessi-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi-2023.06-software arch:x86_64/intel/skylake_avx512
bot: build repo:eessi-2023.06-software arch:x86_64/amd/zen3
bot: build repo:eessi-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi-2023.06-software arch:aarch64/generic
bot: build repo:eessi-2023.06-software arch:aarch64/neoverse_v1
bot: build repo:eessi-2023.06-software arch:aarch64/neoverse_n1

**Comment by boegel** [comment]
@TopRichard `SciPy-bundle` with `foss/2021a` is already installed in EESSI 2023.06, it was installed as a dependency for GROMACS via #288, as indicated by the passing CI tests.

I don't see the point of explicitly adding it to the easystack file?

**Comment by TopRichard** [comment]
@boegel This is exactly what i was trying to say on slack yesterday, by targeting larger packages, how can we, as builders through the bot, know if the package already exists without initiating a build(or mounting the EESSI file system layer) ?

**Comment by boegel** [comment]
@TopRichard Currently you can only check what's already deployed in the EESSI pilot repository - if it's installed already there's no point in opening a PR for it?

Sort of orthogonal: maybe we need to come up with a "locking" mechanism to avoid partially overlapping simultaneous builds?

To discuss further, we should open an issue on this (and close this PR)

**Pull request closed without merging**
