### PR TITLE
[2023.06]{2023a} R-bundle-Bioconductor v3.18

### PR DESCRIPTION
**Pull request by bedroge**
```
5 out of 156 required modules missing:

* RapidJSON/1.1.0-20230928-GCCcore-12.3.0 (RapidJSON-1.1.0-20230928-GCCcore-12.3.0.eb)
* utf8proc/2.8.0-GCCcore-12.3.0 (utf8proc-2.8.0-GCCcore-12.3.0.eb)
* Arrow/14.0.1-gfbf-2023a (Arrow-14.0.1-gfbf-2023a.eb)
* arrow-R/14.0.1-foss-2023a-R-4.3.2 (arrow-R-14.0.1-foss-2023a-R-4.3.2.eb)
* R-bundle-Bioconductor/3.18-foss-2023a-R-4.3.2 (R-bundle-Bioconductor-3.18-foss-2023a-R-4.3.2.eb)
```

### CODE REVIEW

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1

**Comment by bedroge** [comment]
> New job on instance `eessi-bot-mc-aws` for architecture `aarch64-neoverse_v1` for repository `eessi.io-2023.06-software` in job dir `/project/def-users/SHARED/jobs/2024.04/pr_533/9216`
> 
> date	job status	comment
> Apr 08 18:16:58 UTC 2024	submitted	job id `9216` awaits release by job manager
> Apr 08 18:17:45 UTC 2024	released	job awaits launch by Slurm scheduler
> Apr 08 18:22:49 UTC 2024	running	job `9216` is running
> Apr 08 19:09:16 UTC 2024	finished	
> 😢 FAILURE _(click triangle for details)_
> Apr 08 19:09:16 UTC 2024	test result	
> 😁 SUCCESS _(click triangle for details)_

Failing in the `arrow-R` installation:
```
installing to /cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/neoverse_v1/software/arrow-R/14.0.0.2-foss-2023a-R-4.3.2/00LOCK-arrow/00new/arrow/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for arrow in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/neoverse_v1/software/arrow-R/14.0.0.2-foss-2023a-R-4.3.2/00LOCK-arrow/00new/arrow/libs/arrow.so':
  /cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/neoverse_v1/software/arrow-R/14.0.0.2-foss-2023a-R-4.3.2/00LOCK-arrow/00new/arrow/libs/arrow.so: undefined symbol: _ZN4absl12lts_2023012519str_format_internal13FormatArgImpl8DispatchIlEEbNS2_4DataENS1_24FormatConversionSpecImplEPv
Error: loading failed
Execution halted
ERROR: loading failed

```

**Comment by bedroge** [comment]
> 
> Failing in the `arrow-R` installation:
> 
> ```
> installing to /cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/neoverse_v1/software/arrow-R/14.0.0.2-foss-2023a-R-4.3.2/00LOCK-arrow/00new/arrow/libs
> ** R
> ** inst
> ** byte-compile and prepare package for lazy loading
> ** help
> *** installing help indices
> ** building package indices
> ** testing if installed package can be loaded from temporary location
> Error: package or namespace load failed for arrow in dyn.load(file, DLLpath = DLLpath, ...):
>  unable to load shared object '/cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/neoverse_v1/software/arrow-R/14.0.0.2-foss-2023a-R-4.3.2/00LOCK-arrow/00new/arrow/libs/arrow.so':
>   /cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/neoverse_v1/software/arrow-R/14.0.0.2-foss-2023a-R-4.3.2/00LOCK-arrow/00new/arrow/libs/arrow.so: undefined symbol: _ZN4absl12lts_2023012519str_format_internal13FormatArgImpl8DispatchIlEEbNS2_4DataENS1_24FormatConversionSpecImplEPv
> Error: loading failed
> Execution halted
> ERROR: loading failed
> ```

https://github.com/easybuilders/easybuild-easyconfigs/pull/20324 should probably fix this.

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512

**Comment by bedroge** [comment]
This one shouldn't be deployed yet, as we probably first want to fix an issue with its dependencies: see #546.

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512

**Comment by boegel** [comment]
bot: status

**Comment by boegel** [comment]
all staging PRs merged

**Pull request merged**
