### PR TITLE
add OpenFOAM v9 to EESSI pilot 2021.12

### PR DESCRIPTION
**Pull request by boegel**
checklist:

* [x] `aarch64/generic` (done, [ingested](https://github.com/EESSI/staging/pull/129))
* [ ] `aarch64/graviton2` (building...)
* [x] `aarch64/graviton3` (done, [ingested](https://github.com/EESSI/staging/pull/130))
* [x] `ppc64le/generic` (done, [ingested](https://github.com/EESSI/staging/pull/136))
* [x] `ppc64le/power9le` (done, [ingested](https://github.com/EESSI/staging/pull/137))
* [x] `x86_64/generic` (done, [ingested](https://github.com/EESSI/staging/pull/133))
* [x] `x86_64/amd/zen2` (done, [ingested](https://github.com/EESSI/staging/pull/93))
* [x] `x86_64/amd/zen3` (done, [ingested](https://github.com/EESSI/staging/pull/95))
* [x] `x86_64/intel/haswell` (done, [ingested](https://github.com/EESSI/staging/pull/94))
* [x] `x86_64/intel/skylake_avx512` (done, [ingested](https://github.com/EESSI/staging/pull/135))

### CODE REVIEW

**Comment by boegel** [comment]
I'm hitting a weird error during `make install` of `Qt5` while building this on AWS, see https://github.com/easybuilders/easybuild-easyconfigs/issues/16614 for more details...

**Comment by boegel** [comment]
Last iteration of builds seemed to fail due to a variety of issues (mostly building `Qt5`, one failed to build `GObject-Introspection`, another fail during OpenFOAM sanity check).

I've reconfigured the bot to use larger instances (16-core with 32GB of RAM, was 8-core with 16GB of RAM), let's see if that helps...

**Comment by boegel** [comment]
I've reproduced the build problem on `graviton2` manually, and this is the culprit for the failing build of `GObject-Introspection-1.68.0-GCCcore-10.3.0.eb`:

```
Illegal instruction (core dumped)
```

🤔

**Comment by ocaisa** [comment]
> I've reproduced the build problem on `graviton2` manually, and this is the culprit for the failing build of `GObject-Introspection-1.68.0-GCCcore-10.3.0.eb`:
> 
> ```
> Illegal instruction (core dumped)
> ```
> 
> 🤔

Hmm, that sounds familiar https://github.com/EESSI/software-layer/issues/196

**Comment by boegel** [comment]
I may found the culprit for the `Illegal instruction` error...

`OpenBLAS/0.3.15-GCC-10.3.0` was not correctly built, it wasn't using the tweaked OpenBLAS easyblock from https://github.com/easybuilders/easybuild-easyblocks/pull/1946, which caused `DYNAMIC_ARCH=1` to not be used in the options to `make`.

The build of `OpenBLAS/0.3.15-GCC-10.3.0` for `aarch64/generic` was done on a `c7g-8xlarge` instance (Graviton 3), so that effectively leads to an `OpenBLAS/0.3.15-GCC-10.3.0` installation that is incompatible with Graviton 2...

That was meant to fixed by #211, but it seems like the rebuild for `aarch64/generic` was done incorrectly, not using the required `--include-easyblocks-from-pr 1946`.

It's a perfect example of why the builds should be fully automated with the bot, rather than being done by a human who's prone to make mistakes...

**Comment by bedroge** [comment]
Since this involved manual builds and since the pilot repo is no longer supported, I'm going to close this PR.

**Pull request closed without merging**
