### PR TITLE
{2023.06}[foss/2023a] Add SciTools-iris and xarray

### PR DESCRIPTION
**Pull request by casparvl**

### CODE REVIEW

**Comment by casparvl** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3

**Comment by casparvl** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512

**Review by trz42 — APPROVED** [review]
Looks good.

Curious if we could have tried to build for `zen4` too.

**Comment by casparvl** [comment]
Yeah, I haven't really internalized that possibility yet. I'm not even sure if that bot listens to me. Let's try :D

**Comment by casparvl** [comment]
> account casparvl has NO permission to send commands to the bot

Nope, I'm not allowed to

**Comment by ocaisa** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen4

**Comment by casparvl** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen4

**Comment by casparvl** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen4

**Comment by boegel** [comment]
Hmm, still failing for `zen4`?

That doesn't need to block this PR, unless it's an easy fix...

@trz42 Does this just need another kick after ingesting #627?

**Comment by casparvl** [comment]
Eh nope, `librosa` is the problem. We need to build https://github.com/EESSI/software-layer/pull/655 for `zen4` as well. Not sure if all those Python's in that PR are already in `zen4`, would need to check and filter out whatever is not there for `zen4`. Since that PR is already merged, we need a new one anyway. Once that is merged, we can retry this. It's fine to wait for it, there is no rush.

**Comment by trz42** [comment]
> Eh nope, `librosa` is the problem. We need to build #655 for `zen4` as well. Not sure if all those Python's in that PR are already in `zen4`, would need to check and filter out whatever is not there for `zen4`. Since that PR is already merged, we need a new one anyway. Once that is merged, we can retry this. It's fine to wait for it, there is no rush.

Makes sense. See https://github.com/EESSI/software-layer/pull/657

**Comment by ocaisa** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen4

**Comment by ocaisa** [comment]
The build for Zen4 now succeeds, I will set the deploy label again and only merge the Zen4 one

**Review by ocaisa — APPROVED** [review]

**Comment by ocaisa** [comment]
All tarballs have been ingested, merging

**Pull request merged**
