### PR TITLE
{2023.06}[foss/2023a] ROOT 6.30.06

### PR DESCRIPTION
**Pull request by rungitta**
```
3 out of 79 required modules missing:

* freeglut/3.4.0-GCCcore-12.3.0 (freeglut-3.4.0-GCCcore-12.3.0.eb)
* GL2PS/1.4.2-GCCcore-12.3.0 (GL2PS-1.4.2-GCCcore-12.3.0.eb)
* ROOT/6.30.06-foss-2023a (ROOT-6.30.06-foss-2023a.eb)
```

### CODE REVIEW

**Comment by ocaisa** [comment]
@rungitta The convention is to always install using the latest version of EasyBuild, I've updated the PR

**Comment by ocaisa** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic

**Comment by rungitta** [comment]
> @rungitta The convention is to always install using the latest version of EasyBuild, I've updated the PR

Thanks for letting me know. I had just assumed that I should use the version I originally built it with.

**Comment by ocaisa** [comment]
This is failing already on generic ARM:
```
In file included from /tmp/bot/easybuild/build/ROOT/6.30.06/foss-2023a/easybuild_obj/include/ROOT/TExecutorCRTP.hxx:18:
In file included from /tmp/bot/easybuild/build/ROOT/6.30.06/foss-2023a/easybuild_obj/include/TList.h:25:
In file included from /tmp/bot/easybuild/build/ROOT/6.30.06/foss-2023a/easybuild_obj/include/TSeqCollection.h:25:
In file included from /tmp/bot/easybuild/build/ROOT/6.30.06/foss-2023a/easybuild_obj/include/TCollection.h:29:
In file included from /tmp/bot/easybuild/build/ROOT/6.30.06/foss-2023a/easybuild_obj/include/TString.h:28:
In file included from /tmp/bot/easybuild/build/ROOT/6.30.06/foss-2023a/easybuild_obj/include/TMathBase.h:32:
In file included from /cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/generic/software/GCCcore/12.3.0/lib/gcc/aarch64-unknown-linux-gnu/12.3.0/../../../../include/c++/12.3.0/cmath:45:
In file included from /usr/include/math.h:289:
/cvmfs/software.eessi.io/versions/2023.06/compat/linux/aarch64/usr/include/bits/mathcalls-helper-functions.h:20:24: error: unknown type name '__fpclassify'
__MATHDECL_ALIAS (int, __fpclassify,, (_Mdouble_ __value), fpclassify)
```
somehow the system math libraries are leaking in

**Comment by ocaisa** [comment]
This problem is very hard to find, I don't why ROOT is searching in that location but `/usr/include` is hardcoded in quite a few places in the sources

**Comment by bedroge** [comment]
Gentoo also has an ebuild file for ROOT, and I found two sysroot-related things that could perhaps help:

- they also set `DEFAULT_SYSROOT` here: https://github.com/gentoo/gentoo/blob/master/sci-physics/root/root-6.30.08.ebuild#L192C5-L192C20 (and this is used by / passed to Clang/LLVM, which seem to be used for this failing step?).
- they use some additional sysroot patch here: https://github.com/gentoo/gentoo/blob/master/sci-physics/root/files/root-6.12.06_cling-runtime-sysroot.patch. But this seems to be a runtime thing, so probably not related to this issue.

**Comment by rungitta** [comment]
I talked to @TopRichard and he suggested I tried the following on my local ARM machine:
```
To end up in an env similar to the bot's, make sure you run those two command:
1- /cvmfs/[software.eessi.io/versions/2023.06/compat/linux/aarch64/startprefix](http://software.eessi.io/versions/2023.06/compat/linux/aarch64/startprefix)
2- source /cvmfs/[software.eessi.io/versions/2023.06/init/bash](http://software.eessi.io/versions/2023.06/init/bash)
3- make sure to export WORKING_DIR=----
4- module load EESSI-extend
```

Building ROOT then worked without issues as preciously. `math.h` then seems to be installed together with ROOT:
```
-- Installing: /home/palrosen/eessi/versions/2023.06/software/linux/aarch64/neoverse_n1/software/ROOT/6.30.06-foss-2023a/etc/cling/lib/clang/13.0.0/include/openmp_wrappers/math.h
```

**Comment by TopRichard** [comment]
> I talked to @TopRichard and he suggested I tried the following on my local ARM machine:
> 
> ```
> To end up in an env similar to the bot's, make sure you run those two command:
> 1- /cvmfs/[software.eessi.io/versions/2023.06/compat/linux/aarch64/startprefix](http://software.eessi.io/versions/2023.06/compat/linux/aarch64/startprefix)
> 2- source /cvmfs/[software.eessi.io/versions/2023.06/init/bash](http://software.eessi.io/versions/2023.06/init/bash)
> 3- make sure to export WORKING_DIR=----
> 4- module load EESSI-extend
> ```
> 
> Building ROOT then worked without issues as preciously. `math.h` then seems to be installed together with ROOT:
> 
> ```
> -- Installing: /home/palrosen/eessi/versions/2023.06/software/linux/aarch64/neoverse_n1/software/ROOT/6.30.06-foss-2023a/etc/cling/lib/clang/13.0.0/include/openmp_wrappers/math.h
> ```

As @ocaisa  mentioned, if source is hardcoded, then it will still leak even when using the mentioned steps, to end up in an env exactly as the bot is to run within EESSI container : https://www.eessi.io/docs/getting_access/eessi_container/

**Comment by ocaisa** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic

**Comment by ocaisa** [comment]
@bedroge I implemented the build time tweak, not sure if we need the runtime tweak or now

**Comment by ocaisa** [comment]
I suspect we would need the runtime patch, and I _guess_ it would be ok to apply it globally to the easyconfig since it only triggers in a scenario where you have a sysroot (i.e., the code path is not followed by existing EasyBuild ROOT installations)

**Comment by ocaisa** [comment]
@rungitta The build with my easyblock PR succeeded but we will also need an easyconfig PR that adds the necessary runtime patch

**Comment by ocaisa** [comment]
@rungitta Can you make the easyconfig PR? The patch you need to add is https://github.com/gentoo/gentoo/blob/master/sci-physics/root/files/root-6.12.06_cling-runtime-sysroot.patch, and it should be done for all the ROOT easyconfigs that are still supported (so as far back as the `2021b` toolchain, which is 4 in total)

**Comment by rungitta** [comment]
I'll give it a shot.

**Comment by rungitta** [comment]
@ocaisa PR made. Does it look OK?
https://github.com/easybuilders/easybuild-easyconfigs/pull/21526/files

**Comment by ocaisa** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic

**Comment by ocaisa** [comment]
bot: build repo:eessi.io-2023.06-software arch:zen4
bot: build repo:eessi.io-2023.06-software arch:zen3
bot: build repo:eessi.io-2023.06-software arch:zen2
bot: build repo:eessi.io-2023.06-software arch:skylake_512
bot: build repo:eessi.io-2023.06-software arch:haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic
bot: build repo:eessi.io-2023.06-software arch:neoverse_n1
bot: build repo:eessi.io-2023.06-software arch:neoverse_v1

**Comment by ocaisa** [comment]
bot: build repo:eessi.io-2023.06-software arch:skylake_avx512

**Comment by ocaisa** [comment]
@rungitta This is good to go, just need to get the easyconfig PR merged before we can merge here

**Review by ocaisa — APPROVED** [review]

**Review by ocaisa — APPROVED** [review]
Welcome to the wonderful world of EESSI @rungitta !

**Pull request merged**
