### PR TITLE
{2023.06}[SYSTEM] ReFrame 4.2.0

### PR DESCRIPTION
**Pull request by satishskamath**
Created a new yml file via which ReFrame should be added since ReFrame depends on the system Python.

### CODE REVIEW

**Comment by satishskamath** [comment]
bot: build repo:eessi-2023.06-software arch:x86_64/amd/zen2

**Comment by boegel** [comment]
Had to restart the job manager to pick up the finished jobs, see also https://github.com/EESSI/eessi-bot-software-layer/issues/193

**Review by boegel — CHANGES_REQUESTED** [review]
@satishskamath The tarballs being produced are empty:

```
Artefacts
    eessi-2023.06-software-linux-aarch64-neoverse_n1-1688387058.tar.gz
    size: 0 MiB (55426 bytes)
    entries: 3
    modules under 2023.06/software/linux/aarch64/neoverse_n1/modules/all

    no module files in tarball

    software under 2023.06/software/linux/aarch64/neoverse_n1/software

    no software packages in tarball

```

The `EESSI-pilot-install-software.sh` script basically uses `eessi-2023.06-eb-4.7.2-*.yml` to collect all easystack files, and hence `

`eessi-2023.06-eb-4.7.2.yml` is not picked up at all. I would rename it to `eessi-2023.06-eb-4.7.2-system.yml`

**Comment by satishskamath** [comment]
bot: build repo:eessi-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi-2023.06-software arch:x86_64/generic
bot: build repo:eessi-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi-2023.06-software arch:x86_64/intel/skylake_avx512
bot: build repo:eessi-2023.06-software arch:x86_64/amd/zen3
bot: build repo:eessi-2023.06-software arch:aarch64/generic
bot: build repo:eessi-2023.06-software arch:aarch64/neoverse_v1
bot: build repo:eessi-2023.06-software arch:aarch64/neoverse_n1

**Comment by boegel** [comment]
All tarballs ingested

**Review by boegel — APPROVED** [review]

**Pull request merged**
