### PR TITLE
{2023.06}[system] EasyBuild v4.9.4

### PR DESCRIPTION
**Pull request by laraPPr**

### CODE REVIEW

**Comment by laraPPr** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic

**Comment by boegel** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/a64fx

**Comment by boegel** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/a64fx

**Comment by laraPPr** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1
bot: build repo:eessi.io-2023.06-software arch:zen4
bot: build arch:x86_64/generic repo:eessi.io-2023.06-software
bot: build arch:x86_64/intel/haswell repo:eessi.io-2023.06-software
bot: build arch:x86_64/intel/skylake_avx512 repo:eessi.io-2023.06-software
bot: build arch:x86_64/amd/zen2 repo:eessi.io-2023.06-software
bot: build arch:x86_64/amd/zen3 repo:eessi.io-2023.06-software

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
All staging PRs merged...

**Pull request merged**
