### PR TITLE
{2023.06}[foss/2022b] GDAL 3.6.2

### PR DESCRIPTION
**Pull request by bedroge**
Trying to work towards an R installation, this adds about half of its dependencies:

```
27 out of 91 required modules missing:

* GEOS/3.11.1-GCC-12.2.0 (GEOS-3.11.1-GCC-12.2.0.eb)
* PCRE/8.45-GCCcore-12.2.0 (PCRE-8.45-GCCcore-12.2.0.eb)
* jbigkit/2.1-GCCcore-12.2.0 (jbigkit-2.1-GCCcore-12.2.0.eb)
* libdeflate/1.15-GCCcore-12.2.0 (libdeflate-1.15-GCCcore-12.2.0.eb)
* LibTIFF/4.4.0-GCCcore-12.2.0 (LibTIFF-4.4.0-GCCcore-12.2.0.eb)
* googletest/1.12.1-GCCcore-12.2.0 (googletest-1.12.1-GCCcore-12.2.0.eb)
* netCDF/4.9.0-gompi-2022b (netCDF-4.9.0-gompi-2022b.eb)
* nlohmann_json/3.11.2-GCCcore-12.2.0 (nlohmann_json-3.11.2-GCCcore-12.2.0.eb)
* PROJ/9.1.1-GCCcore-12.2.0 (PROJ-9.1.1-GCCcore-12.2.0.eb)
* libgeotiff/1.7.1-GCCcore-12.2.0 (libgeotiff-1.7.1-GCCcore-12.2.0.eb)
* libtirpc/1.3.3-GCCcore-12.2.0 (libtirpc-1.3.3-GCCcore-12.2.0.eb)
* HDF/4.2.15-GCCcore-12.2.0 (HDF-4.2.15-GCCcore-12.2.0.eb)
* CFITSIO/4.2.0-GCCcore-12.2.0 (CFITSIO-4.2.0-GCCcore-12.2.0.eb)
* giflib/5.2.1-GCCcore-12.2.0 (giflib-5.2.1-GCCcore-12.2.0.eb)
* Boost/1.81.0-GCC-12.2.0 (Boost-1.81.0-GCC-12.2.0.eb)
* json-c/0.16-GCCcore-12.2.0 (json-c-0.16-GCCcore-12.2.0.eb)
* Xerces-C++/3.2.4-GCCcore-12.2.0 (Xerces-C++-3.2.4-GCCcore-12.2.0.eb)
* Imath/3.1.6-GCCcore-12.2.0 (Imath-3.1.6-GCCcore-12.2.0.eb)
* OpenEXR/3.1.5-GCCcore-12.2.0 (OpenEXR-3.1.5-GCCcore-12.2.0.eb)
* arpack-ng/3.8.0-foss-2022b (arpack-ng-3.8.0-foss-2022b.eb)
* Armadillo/11.4.3-foss-2022b (Armadillo-11.4.3-foss-2022b.eb)
* Qhull/2020.2-GCCcore-12.2.0 (Qhull-2020.2-GCCcore-12.2.0.eb)
* LERC/4.0.0-GCCcore-12.2.0 (LERC-4.0.0-GCCcore-12.2.0.eb)
* Highway/1.0.3-GCCcore-12.2.0 (Highway-1.0.3-GCCcore-12.2.0.eb)
* Brunsli/0.1-GCCcore-12.2.0 (Brunsli-0.1-GCCcore-12.2.0.eb)
* OpenJPEG/2.5.0-GCCcore-12.2.0 (OpenJPEG-2.5.0-GCCcore-12.2.0.eb)
* GDAL/3.6.2-foss-2022b (GDAL-3.6.2-foss-2022b.eb)
```

Let's see if this also fails on the netCDF tests...

### CODE REVIEW

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1

**Comment by bedroge** [comment]
The builds got quite far (even netCDF worked), but failed on the sanity check of LERC. It depends on LD_LIBRARY_PATH being set, and we filter it. I'm fixing this in a PR to the easyconfigs repo.

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1

**Comment by bedroge** [comment]
LERC was successfully built this time, but now there are quite a lot of test errors in SciPy-bundle.

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic

**Comment by bedroge** [comment]
Tried to build `SciPy-bundle` in an interactive session, and with the default easyconfig I indeed got almost 1000 errors. Then I tweaked the easyconfig and changed the `scipy` version from 1.10.1 to 1.11.0 and 1.11.1 (for which I also had to bump some dependencies, e.g. `Cython`, `Meson`, `pybind11`), and then I only got 6 errors:

```
FAILED scipy/integrate/_ivp/tests/test_ivp.py::test_empty - AssertionError: G...
FAILED scipy/spatial/tests/test_distance.py::TestPdist::test_pdist_correlation_iris
FAILED scipy/spatial/tests/test_distance.py::TestPdist::test_pdist_correlation_iris_float32
FAILED scipy/stats/tests/test_distributions.py::TestInvGamma::test_invgamma_inf_gh_1866
FAILED scipy/stats/tests/test_distributions.py::TestErlang::test_erlang_runtimewarning
FAILED scipy/stats/tests/test_morestats.py::TestMvsdist::test_warns - Runtime...
= 6 failed, 54403 passed, 3016 skipped, 224 xfailed, 12 xpassed, 2183 warnings in 983.61s (0:16:23) =
```

**Comment by bedroge** [comment]
Some more tests/observations with different `--optarch` values for `SciPy-bundle-2023.02-gfbf-2022b.eb`:

```
--optarch=march=armv8.4-a
installation succeeds

--optarch=march=armv8.4-a+sve
= 928 failed, 49044 passed, 2480 skipped, 231 xfailed, 11 xpassed, 36 errors in 199.12s (0:03:19) =

--optarch=mtune=neoverse-512tvb
= 44 failed, 49964 passed, 2480 skipped, 231 xfailed, 11 xpassed in 157.85s (0:02:37) =

--optarch=mcpu=neoverse-512tvb
= 46 failed, 49962 passed, 2480 skipped, 231 xfailed, 11 xpassed in 156.17s (0:02:36) =
```

**Comment by boegel** [comment]
Any idea why we're seeing way more errors with `SciPy-bundle/2023.02-gfbf-2022b` compared to `SciPy-bundle/2022.05-foss-2022a` which we have installed in EESSI pilot 2023.06?

**Comment by bedroge** [comment]
> Any idea why we're seeing way more errors with `SciPy-bundle/2023.02-gfbf-2022b` compared to `SciPy-bundle/2022.05-foss-2022a` which we have installed in EESSI pilot 2023.06?

I don't know, but it definitely feels like there's some issue with the SVE-related code/tests in numpy 1.24.x (either in general, or for this particular CPU, not sure): whenever I enable SVE in some way (e.g. by adding `+sve` to `march`), I get a lot of errors.

When comparing 1.24.4 to 1.25.1 in GitHub I did find issue https://github.com/numpy/numpy/pull/24054 and suspected that it may be the culprit, but when checking the actual 1.24.4 code I can't find this piece of code anymore. So I'm not sure why it popped up in the diff, but it looks like it may not apply to this version (or maybe in some different way).

**Review by boegel — CHANGES_REQUESTED** [review]

**Comment by boegel** [comment]
@bedroge Let's follow up on `SciPy-bundle` with `foss/2022b` in #448

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512

**Comment by boegel** [comment]
@bedroge faliure for `aarch64/neoverse_v1`...

**Comment by bedroge** [comment]
> @bedroge faliure for `aarch64/neoverse_v1`...

Of course... :disappointed: 
It's [Highway 1.0.3](https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/h/Highway/Highway-1.0.3-GCCcore-12.2.0.eb) that's failing on one particular test:

```
211/658 Test #211: HwyBlockwiseShiftTestGroup/HwyBlockwiseShiftTest.TestAllShiftRightLanes/SVE_256  # GetParam() = 33554432 ...............Subp
rocess aborted***Exception:   0.55 sec
Running main() from /tmp/bot/easybuild/build/googletest/1.12.1/GCCcore-12.2.0/googletest-release-1.12.1/googletest/src/gtest_main.cc
Note: Google Test filter = HwyBlockwiseShiftTestGroup/HwyBlockwiseShiftTest.TestAllShiftRightLanes/SVE_256
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from HwyBlockwiseShiftTestGroup/HwyBlockwiseShiftTest
[ RUN      ] HwyBlockwiseShiftTestGroup/HwyBlockwiseShiftTest.TestAllShiftRightLanes/SVE_256


i32x8 expect [2+ ->]:
  4,0,0,7,8,0,
i32x8 actual [2+ ->]:
  4,0,6,7,8,0,
Abort at /tmp/bot/easybuild/build/Highway/1.0.3/GCCcore-12.2.0/highway-1.0.3/hwy/tests/blockwise_shift_test.cc:135: SVE_256, i32x8 lane 4 misma
tch: expected '0', got '6'.
```

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
All staging PRs merged

**Pull request merged**
