### PR TITLE
{2023.06}[foss/2023b] GDRCopy 2.4

### PR DESCRIPTION
**Pull request by bedroge**
Required for https://github.com/EESSI/software-layer/pull/817.

### CODE REVIEW

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512

**Comment by bedroge** [comment]
Need to wait for the Azure cluster to be back online before we can trigger the missing zen4 build.

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen4

**Comment by trz42** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen4

**Review by trz42 — APPROVED** [review]
lgtm

**Comment by trz42** [comment]
CI checks succeeded. All good.

**Pull request merged**
