### PR TITLE
{2023.06}[gompi/2023a] CDO 2.2.2

### PR DESCRIPTION
**Pull request by trz42**
Attempt to add `CDO/2.2.2` to `software.eessi.io/2023.06`.

License:
- SPDX identifier: BSD-3-Clause
- Source: `README` and `LICENSE` files included in source tarball

Missing installations:
```
9 out of 49 required modules missing:
* ecBuild/3.8.0 (ecBuild-3.8.0.eb)
* googletest/1.13.0-GCCcore-12.3.0 (googletest-1.13.0-GCCcore-12.3.0.eb)
* UDUNITS/2.2.28-GCCcore-12.3.0 (UDUNITS-2.2.28-GCCcore-12.3.0.eb)
* libaec/1.0.6-GCCcore-12.3.0 (libaec-1.0.6-GCCcore-12.3.0.eb)
* nlohmann_json/3.11.2-GCCcore-12.3.0 (nlohmann_json-3.11.2-GCCcore-12.3.0.eb)
* PROJ/9.2.0-GCCcore-12.3.0 (PROJ-9.2.0-GCCcore-12.3.0.eb)
* netCDF/4.9.2-gompi-2023a (netCDF-4.9.2-gompi-2023a.eb)
* ecCodes/2.31.0-gompi-2023a (ecCodes-2.31.0-gompi-2023a.eb)
* CDO/2.2.2-gompi-2023a (CDO-2.2.2-gompi-2023a.eb)
```

### CODE REVIEW

**Comment by trz42** [comment]
bot: build arch:aarch64/generic repo:eessi.io-2023.06-software
bot: build arch:x86_64/generic repo:eessi.io-2023.06-software

**Comment by casparvl** [comment]
bot: build arch:aarch64/generic repo:eessi.io-2023.06-software
bot: build arch:x86_64/generic repo:eessi.io-2023.06-software

**Comment by casparvl** [comment]
bot: build arch:aarch64/generic repo:eessi.io-2023.06-software
bot: build arch:x86_64/generic repo:eessi.io-2023.06-software

**Comment by casparvl** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell

**Comment by boegel** [comment]
There's a merge conflict here, that needs to be resolved first, or the bot will fail to prepare the job working directory...

**Comment by casparvl** [comment]
bot: build arch:aarch64/generic repo:eessi.io-2023.06-software
bot: build arch:x86_64/generic repo:eessi.io-2023.06-software

**Comment by bedroge** [comment]
> New job on instance `eessi-bot-mc-aws` for architecture `aarch64-generic` for repository `eessi.io-2023.06-software` in job dir `/project/def-users/SHARED/jobs/2024.01/pr_427/4626`
> 
> date	job status	comment
> Jan 23 11:38:04 UTC 2024	submitted	job id `4626` awaits release by job manager
> Jan 23 11:38:19 UTC 2024	released	job awaits launch by Slurm scheduler
> Jan 23 11:43:23 UTC 2024	running	job `4626` is running
> Jan 23 12:09:50 UTC 2024	finished	
> 😢 FAILURE _(click triangle for details)_
> Jan 23 12:09:50 UTC 2024	test result	_(no tests yet)_

This failed because of:
```
cfortran.h:265:2: error: #error "cfortran.h:  Can't find your environment among:    - GNU gcc (gfortran) on Linux.                                           - MIPS cc and f77 2.0. (e.g. Silicon Graphics, DECstations, ...)         - IBM AIX XL C and FORTRAN Compiler/6000 Version 01.01.0000.0000         - VAX   VMS CC 3.1 and FORTRAN 5.4.                                      - Alpha VMS DEC C 1.3 and DEC FORTRAN 6.0.                               - Alpha OSF DEC C and DEC Fortran for OSF/1 AXP Version 1.2              - Apollo DomainOS 10.2 (sys5.3) with f77 10.7 and cc 6.7.                - CRAY                                                                   - NEC SX-4 SUPER-UX                                                      - CONVEX                                                                 - Sun                                                                    - PowerStation Fortran with Visual C++                                   - HP9000s300/s700/s800 Latest test with: HP-UX A.08.07 A 9000/730        - LynxOS: cc or gcc with f2c.                                            - VAXUltrix: vcc,cc or gcc with f2c. gcc or cc with f77.                 -            f77 with vcc works; but missing link magic for f77 I/O.     -            NO fort. None of gcc, cc or vcc generate required names.    - f2c/g77:   Use #define    f2cFortran, or cc -Df2cFortran               - gfortran:  Use #define    gFortran,   or cc -DgFortran                              (also necessary for g77 with -fno-f2c option)               - NAG f90: Use #define NAGf90Fortran, or cc -DNAGf90Fortran              - Absoft UNIX F77: Use #define AbsoftUNIXFortran or cc -DAbsoftUNIXFortran     - Absoft Pro Fortran: Use #define AbsoftProFortran     - Portland Group Fortran: Use #define pgiFortran     - Intel Fortran: Use #define INTEL_COMPILER"
```

That's the same error as https://github.com/EESSI/software-layer/pull/373#issuecomment-1821121542.

**Comment by bedroge** [comment]
This is the piece of code in CDO's `cfortran.h` that's throwing the error:

```
/* Split #if into 2 because some HP-UX can't handle long #if */
#if !(defined(NAGf90Fortran) || defined(f2cFortran) || defined(hpuxFortran) || defined(apolloFortran) || defined(sunFortran) \
      || defined(IBMR2Fortran) || defined(CRAYFortran))
#if !(defined(mipsFortran) || defined(DECFortran) || defined(vmsFortran) || defined(CONVEXFortran) || defined(PowerStationFortran) \
      || defined(AbsoftUNIXFortran) || defined(AbsoftProFortran) || defined(SXFortran))
/* If your compiler barfs on ' #error', replace # with the trigraph for #     */
#error "cfortran.h:  Can't find your environment among:\
    - GNU gcc (gfortran) on Linux.                                       \
    - MIPS cc and f77 2.0. (e.g. Silicon Graphics, DECstations, ...)     \
    - IBM AIX XL C and FORTRAN Compiler/6000 Version 01.01.0000.0000     \
    - VAX   VMS CC 3.1 and FORTRAN 5.4.                                  \
    - Alpha VMS DEC C 1.3 and DEC FORTRAN 6.0.                           \
    - Alpha OSF DEC C and DEC Fortran for OSF/1 AXP Version 1.2          \
    - Apollo DomainOS 10.2 (sys5.3) with f77 10.7 and cc 6.7.            \
    - CRAY                                                               \
    - NEC SX-4 SUPER-UX                                                  \
    - CONVEX                                                             \
    - Sun                                                                \
    - PowerStation Fortran with Visual C++                               \
    - HP9000s300/s700/s800 Latest test with: HP-UX A.08.07 A 9000/730    \
    - LynxOS: cc or gcc with f2c.                                        \
    - VAXUltrix: vcc,cc or gcc with f2c. gcc or cc with f77.             \
    -            f77 with vcc works; but missing link magic for f77 I/O. \
    -            NO fort. None of gcc, cc or vcc generate required names.\
    - f2c/g77:   Use #define    f2cFortran, or cc -Df2cFortran           \
    - gfortran:  Use #define    gFortran,   or cc -DgFortran             \
                 (also necessary for g77 with -fno-f2c option)           \
    - NAG f90: Use #define NAGf90Fortran, or cc -DNAGf90Fortran          \
    - Absoft UNIX F77: Use #define AbsoftUNIXFortran or cc -DAbsoftUNIXFortran \
    - Absoft Pro Fortran: Use #define AbsoftProFortran \
    - Portland Group Fortran: Use #define pgiFortran \
    - Intel Fortran: Use #define INTEL_COMPILER"
/* Compiler must throw us out at this point! */
#endif
#endif
```

I don't understand why all of those are undefined though, since I'd expect the condition of this if statement (which is more to the top of the file) to be true on Arm as well?
```
#if defined(__GNUC__) && defined(linux) /* 06/21/00 PDW (CFITSIO) */
#define f2cFortran
#define gFortran /* 8/26/08 (KMCCARTY) */
#endif
```

**Comment by bedroge** [comment]
Okay, figured it out: it's the `configure` script of `CDO` that also has some logic for setting `-Dg77Fortran` or `-DgFortran` or something similar. However, it only does it for certain architectures, including `x86_64-*-linux-*|i*86-*-linux-*|*-apple-darwin*|ia64-*-linux-*|x86_64-*-freebsd*|i*86-*-freebsd*`, so `aarch64` is not included. We either have to patch the `configure` script in the easyconfig, or we can manually add `-DgFortran` to `$CXXFLAGS`.

**Comment by bedroge** [comment]
I tried a few solutions, which all worked:

- using `sed` in `preconfigopts` to replace that host line and include `aarch64-*-linux-*` (disadvantage: will have to do the same for any other architecture, e.g. `riscv64`)
- idem, but replacing `x86_64-*-linux-*` by `*-*-linux-*`, as the logic in that case statement should probably work on many Linux systems: it's just checking which compiler you're using and the contents of `$FFLAGS` (disadvantage: potentially matching systems that should not be matched?)
- set `CPPFLAGS="$CPPFLAGS -DgFortran"` in `configopts`, as we know `gfortran` is used for `gompi` (potential disadvantage: will have to be reevaluated for other toolchains, while that logic is already in the `configure` script)

Which one shall I use for fixing the easyconfig?

For reference, this is the relevant bit of code in the `configure` script (the indentation makes it horrible to read...):
```
   case $host in #(
  x86_64-*-linux-*|i*86-*-linux-*|*-apple-darwin*|ia64-*-linux-*|x86_64-*-freebsd*|i*86-*-freebsd*) :
    acx_temp=`$acx_FC -V 2>&1`
      if echo "$acx_temp" | grep '^Copyright.*\(The Portland Group\|NVIDIA CORPORATION\)' >/dev/null
then :
  acx_cv_f77_cf_flag=-DgFortran
elif echo "$acx_temp" | grep '^NAG Fortran Compiler Release' >/dev/null
then :
  acx_cv_f77_cf_flag=-DNAGf90Fortran
elif echo "$acx_temp" | grep '^Intel(R) Fortran.*Compiler' >/dev/null
then :
  acx_cv_f77_cf_flag=-DgFortran
elif echo "$acx_temp" | grep '^Cray Fortran' >/dev/null
then :
  acx_cv_f77_cf_flag=-DgFortran
elif acx_temp=`$acx_FC --version 2>&1` \
         && echo $acx_temp | grep '^GNU Fortran' >/dev/null
then :
  if echo $acx_temp | grep g77 >/dev/null
then :
  acx_cv_f77_cf_flag=-Dg77Fortran
else $as_nop
              if echo "$FFLAGS" | grep '^\(.* \)*-ff2c\( .*\)*$' >/dev/null
then :
  acx_cv_f77_cf_flag=-Df2cFortran
else $as_nop
  acx_cv_f77_cf_flag=-DgFortran
fi
fi
elif acx_temp=`$acx_FC -v 2>&1` \
         && echo $acx_temp | grep '^f2c'
then :
  acx_cv_f77_cf_flag=-Df2cFortran
fi ;; #(
  *-ibm-aix*) :
          if $CC -qversion 2>&1 | grep '^IBM XL C' >/dev/null
then :

else $as_nop
           acx_cv_f77_cf_flag=-DIBMR2Fortran
fi
      ;; #(
  *-*-hpux*) :
    acx_cv_f77_cf_flag=-DhpuxFortran ;; #(
  sx*-*-*|es*-*-*) :
          acx_cv_f77_cf_flag=-DSXFortran ;; #(
  *) :
     ;;
esac
```

**Comment by boegel** [comment]
@bedroge I would go with the `CPPFLAGS` approach, since that's a general fix we can also include upstream in EasyBuild, and we know which compiler we're dealing with, so bypassing the logic in `configure` makes sense to me...

If this needs to be revised for other compilers, that's fine imho.

**Comment by bedroge** [comment]
bot: build arch:aarch64/generic repo:eessi.io-2023.06-software
bot: build arch:x86_64/generic repo:eessi.io-2023.06-software

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512

**Comment by bedroge** [comment]
Note: we should wait with ingesting/merging this until https://github.com/easybuilders/easybuild-easyconfigs/pull/19735 has been merged.

**Review by ocaisa — APPROVED** [review]

**Pull request merged**
