### PR TITLE
{2023.06][foss/2023b] Score-P 8.4 (CPU-only)

### PR DESCRIPTION
**Pull request by bedroge**

### CODE REVIEW

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen4

**Comment by ocaisa** [comment]
IIRC Score-P installs compilers wrappers, we should be careful that those wrappers do not reference the compiler wrappers used during the build process

**Comment by bedroge** [comment]
The source tarball of PDT had to be downloaded manually (see https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/p/PDT/PDT-3.25.2-GCCcore-13.2.0.eb#L30). I've added this to the bot account, let's try again.

bot: build repo:eessi.io-2023.06-software arch:aarch64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen4

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen4

**Comment by bedroge** [comment]
Now Score-P itself fails in the configure step:
```
checking bfd.h usability... no
checking bfd.h presence... no
checking for bfd.h... no
configure: error: in `/tmp/bot/easybuild/build/ScoreP/8.4/gompi-2023b/scorep-8.4/build-mpi':
configure: error: bfd.h required
See `config.log' for more details
```

This file can be found in our compat layer, but in a bit of a non-default location: 
```
/cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64/usr/lib64/binutils/x86_64-pc-linux-gnu/2.40/include/bfd.h
```
So I guess we need some patching here...

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen4

**Comment by bedroge** [comment]
> New job on instance `eessi-bot-mc-aws` for CPU micro-architecture `aarch64-generic` for repository `eessi.io-2023.06-software` in job dir `/project/def-users/SHARED/jobs/2024.10/pr_797/25236`
> 
> date	job status	comment
> Oct 25 15:24:19 UTC 2024	submitted	job id `25236` awaits release by job manager
> Oct 25 15:24:44 UTC 2024	released	job awaits launch by Slurm scheduler
> Oct 25 15:25:47 UTC 2024	running	job `25236` is running
> Oct 25 15:33:57 UTC 2024	finished	
> 😢 FAILURE _(click triangle for details)_
> Oct 25 15:33:57 UTC 2024	test result	
> 😁 SUCCESS _(click triangle for details)_

This one actually failed in SIONlib due to an unsupported aarch64 flag:

```
++++++++++ LIBS +++++++++++++++++++++++++++++++
make[3]: Entering directory '/tmp/bot/easybuild/build/SIONlib/1.7.7/GCCcore-13.2.0-tools/sionlib/build-linux-gomp10-nompi/build/lib'
gcc -std=c99 -m64 -g -O0 -Wall -fPIC -D_SION_LINUX    -DSION_PTHREADS       -I.  -I../parlib  -I../cppinterface   -c -o sion_common.o sion_common.c
gcc -std=c99 -m64 -g -O0 -Wall -fPIC -D_SION_LINUX    -DSION_PTHREADS       -I.  -I../parlib  -I../cppinterface -c sion_fd.c
gcc -std=c99 -m64 -g -O0 -Wall -fPIC -D_SION_LINUX    -DSION_PTHREADS       -I.  -I../parlib  -I../cppinterface -c sion_filedesc.c
gcc -std=c99 -m64 -g -O0 -Wall -fPIC -D_SION_LINUX    -DSION_PTHREADS       -I.  -I../parlib  -I../cppinterface -c sion_file.c
gcc -std=c99 -m64 -g -O0 -Wall -fPIC -D_SION_LINUX    -DSION_PTHREADS       -I.  -I../parlib  -I../cppinterface -c sion_metadata.c
gcc -std=c99 -m64 -g -O0 -Wall -fPIC -D_SION_LINUX    -DSION_PTHREADS       -I.  -I../parlib  -I../cppinterface -c sion_tools.c
gcc -std=c99 -m64 -g -O0 -Wall -fPIC -D_SION_LINUX    -DSION_PTHREADS       -I.  -I../parlib  -I../cppinterface -c sion_debug.c
gcc -std=c99 -m64 -g -O0 -Wall -fPIC -D_SION_LINUX    -DSION_PTHREADS       -I.  -I../parlib  -I../cppinterface   -c -o sion_error_handler.o sion_error_handler.c
gcc -std=c99 -m64 -g -O0 -Wall -fPIC -D_SION_LINUX    -DSION_PTHREADS       -I.  -I../parlib  -I../cppinterface -c sion_printts.c
gcc -std=c99 -m64 -g -O0 -Wall -fPIC -D_SION_LINUX    -DSION_PTHREADS       -I.  -I../parlib  -I../cppinterface -c sion_internal.c
gcc -std=c99 -m64 -g -O0 -Wall -fPIC -D_SION_LINUX    -DSION_PTHREADS       -I.  -I../parlib  -I../cppinterface -c sion_internal_seek.c
gcc -std=c99 -m64 -g -O0 -Wall -fPIC -D_SION_LINUX    -DSION_PTHREADS       -I.  -I../parlib  -I../cppinterface -c sion_internal_collstat.c
gcc -std=c99 -m64 -g -O0 -Wall -fPIC -D_SION_LINUX    -DSION_PTHREADS       -I.  -I../parlib  -I../cppinterface -c sion_internal_startptr.c
gcc -std=c99 -m64 -g -O0 -Wall -fPIC -D_SION_LINUX    -DSION_PTHREADS       -I.  -I../parlib  -I../cppinterface -c sion_convert.c
gcc -std=c99 -m64 -g -O0 -Wall -fPIC -D_SION_LINUX    -DSION_PTHREADS       -I.  -I../parlib  -I../cppinterface   -c -o sion_buffer.o sion_buffer.c
gcc -std=c99 -m64 -g -O0 -Wall -fPIC -D_SION_LINUX    -DSION_PTHREADS       -I.  -I../parlib  -I../cppinterface   -c sion_hints.c
gcc: error: unrecognized command-line option -m64
```

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic

**Comment by bedroge** [comment]
> New job on instance `eessi-bot-mc-aws` for CPU micro-architecture `aarch64-generic` for repository `eessi.io-2023.06-software` in job dir `/project/def-users/SHARED/jobs/2024.10/pr_797/25767`
> 
> date	job status	comment
> Oct 28 10:02:50 UTC 2024	submitted	job id `25767` awaits release by job manager
> Oct 28 10:03:22 UTC 2024	released	job awaits launch by Slurm scheduler
> Oct 28 10:09:25 UTC 2024	running	job `25767` is running
> Oct 28 10:26:50 UTC 2024	finished	
> 😢 FAILURE _(click triangle for details)_
> Oct 28 10:26:50 UTC 2024	test result	
> 😁 SUCCESS _(click triangle for details)_


The `configure` step failed because of:
```configure: error: Both, --with-libbfd-lib and --with-libbfd-include require a <path>.
configure: error: ./configure failed for build-mpi
```

But it's using:
```
--with-libbfd-lib=/cvmfs/software.eessi.io/versions/2023.06/compat/linux/aarch64/usr/lib64/binutils/aarch64-unknown-linux-gnu/2.40  --with-libbfd-include=/cvmfs/software.eessi.io/versions/2023.06/compat/linux/aarch64/usr/lib64/binutils/aarch64-unknown-linux-gnu/2.40/include
```

Those look like (valid) paths to me... :man_shrugging:  Trying this interactively now.

**Comment by bedroge** [comment]
> 
> The `configure` step failed because of:
> 
> ```
> configure: error: Both, --with-libbfd-lib and --with-libbfd-include require a <path>.
> configure: error: ./configure failed for build-mpi
> ```
> 
> But it's using:
> 
> ```
> --with-libbfd-lib=/cvmfs/software.eessi.io/versions/2023.06/compat/linux/aarch64/usr/lib64/binutils/aarch64-unknown-linux-gnu/2.40  --with-libbfd-include=/cvmfs/software.eessi.io/versions/2023.06/compat/linux/aarch64/usr/lib64/binutils/aarch64-unknown-linux-gnu/2.40/include
> ```
> 
> Those look like (valid) paths to me... 🤷‍♂️ Trying this interactively now.

Okay, I found it, and this is a really sad one... The failing check in the configure script is:
```
    case ${with_libbfd_lib}${with_libbfd_include} in #(
  *yes*|*no*) :
    as_fn_error $? "Both, --with-libbfd-lib and --with-libbfd-include require a <path>. " "$LINENO" 5 ;; #(
  *) :

```

Instead of simply just checking for a `yes` or `no`, it's now matching any value that contains `yes` or `no` somewhere... The bfd path for aarch64 contains `aarch64-unknown-linux-gnu` (unk**NO**wn), and hence this condition is true... The one for x86_64 has `x86_64-pc-linux-gnu`, so it worked fine...
I'll open a PR and make the check a bit more strict.

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen4
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512

**Review by ocaisa — APPROVED** [review]

**Pull request merged**
