### PR TITLE
{2023.06}[GCCcore/11.3.0] BWA-0.7.17-GCCcore-11.3.0

### PR DESCRIPTION
**Pull request by kErica**
adding BWA 0.7.17 with GCCcore-11.3.0 to EESSI pilot 2023.06 2022a toolchain

### CODE REVIEW

**Comment by kErica** [comment]
bot: help

**Comment by kErica** [comment]
bot: help

**Comment by kErica** [comment]
bot: build arch:x86_64/generic repo:eessi-hpc.org-2023.06-software

**Comment by kErica** [comment]
bot: build arch:aarch64/generic repo:eessi-hpc.org-2023.06-software

**Comment by kErica** [comment]
bot: build repo:eessi-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi-2023.06-software arch:x86_64/intel/skylake_avx512
bot: build repo:eessi-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi-2023.06-software arch:x86_64/amd/zen3

**Comment by kErica** [comment]
bot: build arch:x86_64/amd/zen2 repo:eessi-hpc.org-2023.06-software

**Comment by boegel** [comment]
@trz42 Do you have a minute to check why the bot isn't doing what it should be here?

**Comment by trz42** [comment]
> @trz42 Do you have a minute to check why the bot isn't doing what it should be here?

Sorry, for late reply. It's the same issue as in https://github.com/EESSI/software-layer/pull/360#issuecomment-1806340409

**Comment by boegel** [comment]
@kErica The problems with the bot seem to be resolved, please try again

**Comment by kErica** [comment]
bot: build repo:eessi-2023.06-software arch:x86_64/intel/haswell

**Comment by kErica** [comment]
bot: build arch:aarch64/generic repo:eessi-hpc.org-2023.06-software

**Comment by kErica** [comment]
bot: build arch:x86_64/intel/haswell repo:eessi-2023.06-software

**Comment by kErica** [comment]
bot: build arch:x86_64/intel/haswell repo:eessi-hpc.org-2023.06-software

**Comment by kErica** [comment]
bot: build repo:eessi-hpc.org-2023.06-software arch:x86_64/intel/skylake_avx512
bot: build repo:eessi-hpc.org-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi-hpc.org-2023.06-software arch:x86_64/amd/zen3

**Comment by bedroge** [comment]
I just inspected the build log for the failing `aarch64` build, and it's failing due to:
```
ksw.c:29:10: fatal error: emmintrin.h: No such file or directory
   29 | #include <emmintrin.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
```
That's happening on this line https://github.com/lh3/bwa/blob/v0.7.17/ksw.c#L29, and this basically isn't supported on Arm systems. This has been fixed on their `master` branch though (by this PR: https://github.com/lh3/bwa/pull/359), but it looks like they're not really releasing new versions anymore... also see https://github.com/lh3/bwa/issues/401.

@kErica do you need this for a particular use case? In that case, maybe it's best to open an issue in our support portal, and we can work on and keep track of a solution. We could take the fix from the PR, add it as a patch file to the `easybuild-easyconfigs` repo, and then try again.

**Comment by kErica** [comment]
Hi @bedroge, 
I saw the same error - checking on the github repo from BWA the latest commit (from last year) should help with the compatibility to ARM.

I saw there is a PR (https://github.com/easybuilders/easybuild-easyconfigs/pull/19273) to upgrade the toolchain and I asked the author to change the source to the latest commit and see if that will work.

I will open an issue in the support portal to track it - [eessi/support - issue23](https://gitlab.com/eessi/support/-/issues/23)

There is no specific use case, I want to start add genomic related apps to EESSI, which are missing at the moment, so that more users can use EESSI provided apps ;)

**Comment by boegel** [comment]
To get actual patch file that you can try to apply to 0.7.17 release, use this URL https://github.com/lh3/bwa/pull/359.diff

The 0.7.17 releases is from 2017 though, so I wouldn't hold my breath for a new release.

Maybe we should switch to datestamp of latest commit for BWA (and tweak the `PACKAGE_VERSION` bit in `main.c`, see https://github.com/lh3/bwa/blob/139f68fc4c3747813783a488aef2adc86626b01b/main.c#L33)?

**Comment by kErica** [comment]
bot: build  repo:eessi-hpc.org-2023.06-software arch:x86_64/intel/skylake_avx512
bot: build arch:aarch64/generic  repo:eessi-hpc.org-2023.06-software

**Comment by kErica** [comment]
closing PR: new PR https://github.com/EESSI/software-layer/pull/429
- latest commit from BWA
- newer toolchain
- patch for ARM

**Pull request closed without merging**
