### PR TITLE
fix installation of ReFrame 4.2.0 (include `hpctestlib`) in EESSI pilot 2023.06

### PR DESCRIPTION
**Pull request by satishskamath**
* This pull request must not be merged.

### CODE REVIEW

**Comment by satishskamath** [comment]
bot: build repo:eessi-2023.06-software

**Comment by satishskamath** [comment]
bot: build repo:eessi-2023.06-software

**Comment by satishskamath** [comment]
bot: build repo:eessi-2023.06-software arch:x86_64/amd/zen2

**Comment by satishskamath** [comment]
bot: build repo:eessi-2023.06-software arch:x86_64/amd/zen2

**Comment by satishskamath** [comment]
Tried both:
```
...
options:
     from-pr: xxxx
     rebuild:
```
and 
```
...
options:
     from-pr: xxxx
     rebuild
```
And both of them didn't work. So what is the correct of specifying this option? Without the logs it is hard to see how the bot interprets the above formats.

**Comment by bedroge** [comment]
> Tried both:
> 
> ```
> ...
> options:
>      from-pr: xxxx
>      rebuild:
> ```
> 
> and
> 
> ```
> ...
> options:
>      from-pr: xxxx
>      rebuild
> ```
> 
> And both of them didn't work. So what is the correct of specifying this option? Without the logs it is hard to see how the bot interprets the above formats.

I think you need `rebuild: True`.

**Comment by satishskamath** [comment]
Thanks @bedroge :)

**Comment by satishskamath** [comment]
bot: build repo:eessi-2023.06-software arch:x86_64/amd/zen2

**Comment by satishskamath** [comment]
bot: build repo:eessi-2023.06-software arch:x86_64/amd/zen2

**Comment by satishskamath** [comment]
Easybuild crashed because it could not `chown/chmod` some `/cvmfs/...` paths. Most likely this is only while the bot is rebuilding something otherwise this error would have been seen while we build anything.
[easybuild-9ukb1c3n.log](https://github.com/EESSI/software-layer/files/12129610/easybuild-9ukb1c3n.log)

**Comment by satishskamath** [comment]
bot: build repo:eessi-2023.06-software

**Comment by satishskamath** [comment]
Checking if the above error was random. The Easystack file is not parsing properly.

**Comment by bedroge** [comment]
In order to be able to install/merge this, I've just removed the current version of ReFrame from the 2023.06 pilot:
```
/cvmfs/pilot.eessi-hpc.org/versions/2023.06/software/linux/aarch64/generic/software/ReFrame
/cvmfs/pilot.eessi-hpc.org/versions/2023.06/software/linux/aarch64/generic/modules/all/ReFrame
/cvmfs/pilot.eessi-hpc.org/versions/2023.06/software/linux/aarch64/generic/modules/devel/ReFrame
/cvmfs/pilot.eessi-hpc.org/versions/2023.06/software/linux/aarch64/neoverse_n1/software/ReFrame
/cvmfs/pilot.eessi-hpc.org/versions/2023.06/software/linux/aarch64/neoverse_n1/modules/all/ReFrame
/cvmfs/pilot.eessi-hpc.org/versions/2023.06/software/linux/aarch64/neoverse_n1/modules/devel/ReFrame
/cvmfs/pilot.eessi-hpc.org/versions/2023.06/software/linux/aarch64/neoverse_v1/software/ReFrame
/cvmfs/pilot.eessi-hpc.org/versions/2023.06/software/linux/aarch64/neoverse_v1/modules/all/ReFrame
/cvmfs/pilot.eessi-hpc.org/versions/2023.06/software/linux/aarch64/neoverse_v1/modules/devel/ReFrame
/cvmfs/pilot.eessi-hpc.org/versions/2023.06/software/linux/x86_64/generic/software/ReFrame
/cvmfs/pilot.eessi-hpc.org/versions/2023.06/software/linux/x86_64/generic/modules/all/ReFrame
/cvmfs/pilot.eessi-hpc.org/versions/2023.06/software/linux/x86_64/generic/modules/devel/ReFrame
/cvmfs/pilot.eessi-hpc.org/versions/2023.06/software/linux/x86_64/amd/zen2/software/ReFrame
/cvmfs/pilot.eessi-hpc.org/versions/2023.06/software/linux/x86_64/amd/zen2/modules/all/ReFrame
/cvmfs/pilot.eessi-hpc.org/versions/2023.06/software/linux/x86_64/amd/zen2/modules/devel/ReFrame
/cvmfs/pilot.eessi-hpc.org/versions/2023.06/software/linux/x86_64/amd/zen3/software/ReFrame
/cvmfs/pilot.eessi-hpc.org/versions/2023.06/software/linux/x86_64/amd/zen3/modules/all/ReFrame
/cvmfs/pilot.eessi-hpc.org/versions/2023.06/software/linux/x86_64/amd/zen3/modules/devel/ReFrame
/cvmfs/pilot.eessi-hpc.org/versions/2023.06/software/linux/x86_64/intel/haswell/software/ReFrame
/cvmfs/pilot.eessi-hpc.org/versions/2023.06/software/linux/x86_64/intel/haswell/modules/all/ReFrame
/cvmfs/pilot.eessi-hpc.org/versions/2023.06/software/linux/x86_64/intel/haswell/modules/devel/ReFrame
/cvmfs/pilot.eessi-hpc.org/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/software/ReFrame
/cvmfs/pilot.eessi-hpc.org/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/modules/all/ReFrame
/cvmfs/pilot.eessi-hpc.org/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/modules/devel/ReFrame
```

**Comment by boegel** [comment]
`ReFrame` will get reinstalled as a part of #326 (but not correctly, since `--from-pr` won't get used there).

Let's deal with #326 first, and then get back to `ReFrame` once's that's merged...

**Comment by boegel** [comment]
bot: build repo:eessi-2023.06-software

**Comment by boegel** [comment]
all staging PRs merged for deployment...

**Review by boegel — APPROVED** [review]

**Pull request merged**
