### PR TITLE
{2023.06}[foss/2022b] Qt5 v5.15.7

### PR DESCRIPTION
**Pull request by TopRichard**

### CODE REVIEW

**Comment by TopRichard** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1

**Comment by bedroge** [comment]
```
36 out of 88 required modules missing:

* gperf/3.1-GCCcore-12.2.0 (gperf-3.1-GCCcore-12.2.0.eb)
* re2c/3.0-GCCcore-12.2.0 (re2c-3.0-GCCcore-12.2.0.eb)
* PCRE2/10.40-GCCcore-12.2.0 (PCRE2-10.40-GCCcore-12.2.0.eb)
* libpng/1.6.38-GCCcore-12.2.0 (libpng-1.6.38-GCCcore-12.2.0.eb)
* Python/2.7.18-GCCcore-12.2.0-bare (Python-2.7.18-GCCcore-12.2.0-bare.eb)
* graphite2/1.3.14-GCCcore-12.2.0 (graphite2-1.3.14-GCCcore-12.2.0.eb)
* double-conversion/3.2.1-GCCcore-12.2.0 (double-conversion-3.2.1-GCCcore-12.2.0.eb)
* DBus/1.15.2-GCCcore-12.2.0 (DBus-1.15.2-GCCcore-12.2.0.eb)
* pixman/0.42.2-GCCcore-12.2.0 (pixman-0.42.2-GCCcore-12.2.0.eb)
* Brotli/1.0.9-GCCcore-12.2.0 (Brotli-1.0.9-GCCcore-12.2.0.eb)
* freetype/2.12.1-GCCcore-12.2.0 (freetype-2.12.1-GCCcore-12.2.0.eb)
* fontconfig/2.14.1-GCCcore-12.2.0 (fontconfig-2.14.1-GCCcore-12.2.0.eb)
* libiconv/1.17-GCCcore-12.2.0 (libiconv-1.17-GCCcore-12.2.0.eb)
* intltool/0.51.0-GCCcore-12.2.0 (intltool-0.51.0-GCCcore-12.2.0.eb)
* Doxygen/1.9.5-GCCcore-12.2.0 (Doxygen-1.9.5-GCCcore-12.2.0.eb)
* Meson/0.64.0-GCCcore-12.2.0 (Meson-0.64.0-GCCcore-12.2.0.eb)
* GLib/2.75.0-GCCcore-12.2.0 (GLib-2.75.0-GCCcore-12.2.0.eb)
* X11/20221110-GCCcore-12.2.0 (X11-20221110-GCCcore-12.2.0.eb)
* cairo/1.17.4-GCCcore-12.2.0 (cairo-1.17.4-GCCcore-12.2.0.eb)
* GObject-Introspection/1.74.0-GCCcore-12.2.0 (GObject-Introspection-1.74.0-GCCcore-12.2.0.eb)
* HarfBuzz/5.3.1-GCCcore-12.2.0 (HarfBuzz-5.3.1-GCCcore-12.2.0.eb)
* NASM/2.15.05-GCCcore-12.2.0 (NASM-2.15.05-GCCcore-12.2.0.eb)
* Mako/1.2.4-GCCcore-12.2.0 (Mako-1.2.4-GCCcore-12.2.0.eb)
* libjpeg-turbo/2.1.4-GCCcore-12.2.0 (libjpeg-turbo-2.1.4-GCCcore-12.2.0.eb)
* snappy/1.1.9-GCCcore-12.2.0 (snappy-1.1.9-GCCcore-12.2.0.eb)
* NSPR/4.35-GCCcore-12.2.0 (NSPR-4.35-GCCcore-12.2.0.eb)
* NSS/3.85-GCCcore-12.2.0 (NSS-3.85-GCCcore-12.2.0.eb)
* JasPer/4.0.0-GCCcore-12.2.0 (JasPer-4.0.0-GCCcore-12.2.0.eb)
* libdrm/2.4.114-GCCcore-12.2.0 (libdrm-2.4.114-GCCcore-12.2.0.eb)
* nodejs/18.12.1-GCCcore-12.2.0 (nodejs-18.12.1-GCCcore-12.2.0.eb)
* libglvnd/1.6.0-GCCcore-12.2.0 (libglvnd-1.6.0-GCCcore-12.2.0.eb)
* libunwind/1.6.2-GCCcore-12.2.0 (libunwind-1.6.2-GCCcore-12.2.0.eb)
* LLVM/15.0.5-GCCcore-12.2.0 (LLVM-15.0.5-GCCcore-12.2.0.eb)
* Mesa/22.2.4-GCCcore-12.2.0 (Mesa-22.2.4-GCCcore-12.2.0.eb)
* libGLU/9.0.2-GCCcore-12.2.0 (libGLU-9.0.2-GCCcore-12.2.0.eb)
* Qt5/5.15.7-GCCcore-12.2.0 (Qt5-5.15.7-GCCcore-12.2.0.eb)
```

Note that this has some overlap with #419, but that's okay, since that one is still having issues on `SciPy-bundle`.

**Comment by bedroge** [comment]
@TopRichard It's failing because of a known issue with HarfBuzz, which is fixed in https://github.com/easybuilders/easybuild-easyconfigs/pull/19339. We had the same issue for 2023a, see: https://github.com/EESSI/software-layer/blob/2023.06-software.eessi.io/easystacks/software.eessi.io/2023.06/eessi-2023.06-eb-4.8.2-2023a.yml#L21.

**Comment by TopRichard** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic

**Comment by TopRichard** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic

**Comment by TopRichard** [comment]
Failed earlier as the we have to --from-pr for the failing package ,HarfBuzz..., separately within the easystack file.

**Comment by TopRichard** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1

**Comment by bedroge** [comment]
@TopRichard It looks like you didn't trigger a build for `neoverse_v1`?

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1

**Comment by TopRichard** [comment]
@bedroge I don't think i missed that one :roll_eyes: : https://github.com/EESSI/software-layer/pull/422#issuecomment-1859471799

**Comment by bedroge** [comment]
> @bedroge I don't think i missed that one 🙄 : [#422 (comment)](https://github.com/EESSI/software-layer/pull/422#issuecomment-1859471799)

That's `neoverse_n1` instead of `neoverse_v1` :wink:

**Review by bedroge — APPROVED** [review]
Thanks @TopRichard!

**Pull request merged**
