### PR TITLE
{2023.06}[foss/2021b] TensorFlow 2.8.4

### PR DESCRIPTION
**Pull request by laraPPr**
14 out of 69 required modules missing:

* Zip/3.0-GCCcore-11.2.0 (Zip-3.0-GCCcore-11.2.0.eb)
* protobuf/3.17.3-GCCcore-11.2.0 (protobuf-3.17.3-GCCcore-11.2.0.eb)
* dill/0.3.4-GCCcore-11.2.0 (dill-0.3.4-GCCcore-11.2.0.eb)
* pkgconfig/1.5.5-GCCcore-11.2.0-python (pkgconfig-1.5.5-GCCcore-11.2.0-python.eb)
* Bazel/4.2.2-GCCcore-11.2.0 (Bazel-4.2.2-GCCcore-11.2.0.eb)
* giflib/5.2.1-GCCcore-11.2.0 (giflib-5.2.1-GCCcore-11.2.0.eb)
* flatbuffers/2.0.0-GCCcore-11.2.0 (flatbuffers-2.0.0-GCCcore-11.2.0.eb)
* JsonCpp/1.9.4-GCCcore-11.2.0 (JsonCpp-1.9.4-GCCcore-11.2.0.eb)
* LMDB/0.9.29-GCCcore-11.2.0 (LMDB-0.9.29-GCCcore-11.2.0.eb)
* nsync/1.24.0-GCCcore-11.2.0 (nsync-1.24.0-GCCcore-11.2.0.eb)
* h5py/3.6.0-foss-2021b (h5py-3.6.0-foss-2021b.eb)
* protobuf-python/3.17.3-GCCcore-11.2.0 (protobuf-python-3.17.3-GCCcore-11.2.0.eb)
* flatbuffers-python/2.0-GCCcore-11.2.0 (flatbuffers-python-2.0-GCCcore-11.2.0.eb)
* TensorFlow/2.8.4-foss-2021b (TensorFlow-2.8.4-foss-2021b.eb)

### CODE REVIEW

**Comment by laraPPr** [comment]
bot: build repo:eessi-2023.06-software arch:x86_64/generic

**Comment by boegel** [comment]
I've just cancelled job 7586, we should retry with the hook included in #321

**Comment by laraPPr** [comment]
bot: build repo:eessi-2023.06-software arch:aarch64/neoverse_v1

**Comment by boegel** [comment]
Hmm, looks like there's lilttle hope with TensorFlow v4.8.1 on `aarch64` as well?
```
external/XNNPACK/src/qu8-igemm/gen/4x16c4-minmax-fp32-aarch64-neondot-ld128.S: Assembler messages:
external/XNNPACK/src/qu8-igemm/gen/4x16c4-minmax-fp32-aarch64-neondot-ld128.S:123: Error: selected processor does not support `udot v12.4s,v8.16b,v0.16b'
```

Let's see if `x86_64` works at least...

bot: build repo:eessi-2023.06-software arch:x86_64/generic
bot: build repo:eessi-2023.06-software arch:x86_64/amd/zen2

**Comment by laraPPr** [comment]
> Hmm, looks like there's lilttle hope with TensorFlow v4.8.1 on `aarch64` as well?
> 
> ```
> external/XNNPACK/src/qu8-igemm/gen/4x16c4-minmax-fp32-aarch64-neondot-ld128.S: Assembler messages:
> external/XNNPACK/src/qu8-igemm/gen/4x16c4-minmax-fp32-aarch64-neondot-ld128.S:123: Error: selected processor does not support `udot v12.4s,v8.16b,v0.16b'
> ```
> 
> Let's see if `x86_64` works at least...
> 
> bot: build repo:eessi-2023.06-software arch:x86_64/generic bot: build repo:eessi-2023.06-software arch:x86_64/amd/zen2

```
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/XNNPACK/archive/113092317754c7dea47bfb3cb49c4f59c3c1fa10.zip failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
```
I found this in the logs which to me seems the main cause of the crash.

**Comment by boegel** [comment]
@laraPPr Oh, I overlooked that part...
In that case, we can also give it another try on `aarch64` I think

**Comment by boegel** [comment]
Well, since it's a 404 error, it looks like it's not a temporary error, but something that actually got removed and is no longer available. In that case, I expect to see the same problem pop up for `x86_64` as well...

The URL is definitely broken with `mirror.tensorflow.org`, but the direct URL (https://github.com/google/XNNPACK/archive/113092317754c7dea47bfb3cb49c4f59c3c1fa10.zip) works just fine... So this may be patcheable.

**Comment by laraPPr** [comment]
mirror.tensorflow.org this url is not broken anymore which also explains why build succeeded for `x86_64-amd-zen2` and `x86_64-generic`. So I'm retrying build for `aarch64-neoverse_v1`

**Comment by laraPPr** [comment]
`HTTP Error 403: rate limit exceeded`
Restarting on aarch64-neoverse_v1

**Comment by laraPPr** [comment]
bot: build repo:eessi-2023.06-software arch:aarch64/neoverse_v1

**Comment by laraPPr** [comment]
`WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/c3e082762b7664bbc7ffd2c39e86464928e27c0c.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Foun`

**Comment by boegel** [comment]
Yeah, those mirrors don't seem to be very stable...

Again works fine with the direct URL (https://github.com/tensorflow/runtime/archive/c3e082762b7664bbc7ffd2c39e86464928e27c0c.tar.gz).

@Flamefire Do you happen to know what this downloading via `mirror.tensorflow.org` shenanigans is about?

**Comment by Flamefire** [comment]
> @Flamefire Do you happen to know what this downloading via `mirror.tensorflow.org` shenanigans is about?

They have (and require) a mirror for the stuff they download and try that first. I'm not sure it ever succeeded for me so maybe it is somewhere reachable internally from Google only, so we can just ignore those.

**Comment by boegel** [comment]
OK, so then I think that this is really the problem we're hitting on `aarch64` with this TensorFlow version:

```
external/XNNPACK/src/qs8-gemm/gen/4x16c4-minmax-fp32-aarch64-neondot-ld128.S: Assembler messages:
external/XNNPACK/src/qs8-gemm/gen/4x16c4-minmax-fp32-aarch64-neondot-ld128.S:102: Error: selected processor does not support `sdot v16.4s,v4.16b,v0.4b[0]'
```

**Comment by boegel** [comment]
I've opened PRs to check whether we're still seeing problems with newer TensorFlow versions on `aarch64`:

* #346
* #347

**Comment by boegel** [comment]
I've opened a dedicated issue in the EasyBuild repo for the problem on `aarch64/*`, since this is in no way specific to EESSI: https://github.com/easybuilders/easybuild-easyconfigs/issues/18899

**Pull request closed without merging**
