### PR TITLE
{2023.06}[2023a] Extrae 4.0.6 (WIP)

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1

**Comment by boegel** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic

**Comment by boegel** [comment]
`./configure ...` is failing with:
```
checking for binutils... notfound
configure: libbfd library directory: /usr/lib/x86_64-linux-gnu
configure: Warning! Cannot find the libiberty library in the given binutils home. Please, make sure that the binutils packages is correctly installed. If you have installed the binutils package by hand from their source code, make sure that libiberty is installed. Some releases of the binutils package do not install the libibery even invoking make install. The library should be within the libiberty directory within the binutils source tree.
checking for bfd.h... no
configure: error: You have asked to gather call-site information through --with-unwind which must be translated using binutils, but either libbfd or libiberty are not found. Please make sure that the binutils-dev package is installed and specify where to find these libraries through --with-binutils. The latest source can be downloaded from http://www.gnu.org/software/binutils
```

Despite the patch added in https://github.com/easybuilders/easybuild-easyconfigs/pull/20153, it's not able yet to find the binutils from the EESSI compat layer. I had this working somehow during the EuroHPC Summit week, but perhaps I had an extra change/fix somewhere back then which I didn't keep track of...

**Comment by boegel** [comment]
Including this in the `Extrae` easyconfig (which should be done either in the custom easyblock for Extra, or in the hooks we use in EESSI) helps:
```python
configopts = "--with-binutils=%(sysroot)s/usr/lib*/binutils/x86_64-pc-linux-gnu/2.*/"
```

but then there's a problem in the build step, I don't recall hitting this one before...

```
configure: error: Cannot find given ${MPIF77}. Please give the full path for the MPI F77 compiler
```

<details>

```
checking for mpicc compiler default binary type... 64-bit
configure: cannot locate multiarch triplet
checking for mpicxx compiler default binary type... 64-bit
configure: cannot locate multiarch triplet
checking for MPI installation... /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/software/OpenMPI/4.1.5-GCC-12.3.0
checking for MPI binaries directory... /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/software/OpenMPI/4.1.5-GCC-12.3.0/bin
checking for MPI includes directory... /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/software/OpenMPI/4.1.5-GCC-12.3.0/include
checking for MPI libraries directory... /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/software/OpenMPI/4.1.5-GCC-12.3.0/lib64
checking for MPI shared library folder... no
checking for MPI multiarch library folder... no
checking for MPI valid installation... yes
checking for mpi.h... yes
checking for MPICH2 defined... no
checking for MPI library... /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/software/OpenMPI/4.1.5-GCC-12.3.0/lib64, -lmpi
checking for shared MPI library... yes
checking for fortran MPI library... not found,
checking for MPI C compiler... mpicc
checking for MPI F77 compiler... Illegal option --
./configure: line 11789: test: too many arguments
configure: error: Cannot find given ${MPIF77}. Please give the full path for the MPI F77 compiler
make: *** [Makefile:1240: config.status] Error 2
```

</details>

**Comment by boegel** [comment]
The issue with `$MPIF77` is caused by the use of `which` in Extrae's `configure` script:

```shell
         if test -x `which ${MPIF77}` ; then
                { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: ${MPIF77}" >&5
printf "%s\n" "${MPIF77}" >&6; }
         else
                as_fn_error $? "Cannot find given \${MPIF77}. Please give the full path for the MPI F77 compiler" "$LINENO" 5
         fi
```

That fails in the EESSI build container, because `which` doesn't work there:

```
{EESSI 2023.06} Apptainer> which ls
Illegal option --
Usage: /usr/bin/which [-a] args
```

`command -v` can be used instead:

```
{EESSI 2023.06} Apptainer> command -v ls
/cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64/bin/ls
```

**Comment by boegel** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512

**Comment by boegel** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1

**Comment by boegel** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512

**Comment by boegel** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512

**Comment by ocaisa** [comment]
We should be able to update this now for https://github.com/easybuilders/easybuild-easyconfigs/pull/20690 and easyblock PR 3339

**Comment by ocaisa** [comment]
Closing this in favour of #640 where we are much closer to a working build

**Pull request closed without merging**
