### PR TITLE
{2023.06}[2023b] CUDA 12.4.0 and UCX-CUDA 1.15.0

### PR DESCRIPTION
**Pull request by bedroge**
Clone of #817, where I accidentally triggered a build for the CPU-only stack as well.

### CODE REVIEW

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2 accel:nvidia/cc80
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3 accel:nvidia/cc80

**Comment by bedroge** [comment]
Just to make sure that this PR includes the changes from https://github.com/EESSI/software-layer/pull/810 and doesn't overwrite some of the modified scripts with old versions, I've synced this with the 2023.06-software.eessi.io branch and I'm doing another build.

bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2 accel:nvidia/cc80
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3 accel:nvidia/cc80

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2 accel:nvidia/cc80
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3 accel:nvidia/cc80

**Review by trz42 — APPROVED** [review]
lgtm

**Comment by trz42** [comment]
all fine. re-ran CI succeeded.

**Pull request merged**
