### PR TITLE
{2023.03} foss/2023a

### PR DESCRIPTION
**Pull request by boegel**
```
32 out of 34 required modules missing:

* GCCcore/12.3.0 (GCCcore-12.3.0.eb)
* GCC/12.3.0 (GCC-12.3.0.eb)
* pkgconf/1.9.5-GCCcore-12.3.0 (pkgconf-1.9.5-GCCcore-12.3.0.eb)
* FFTW/3.3.10-GCC-12.3.0 (FFTW-3.3.10-GCC-12.3.0.eb)
* Perl/5.36.1-GCCcore-12.3.0 (Perl-5.36.1-GCCcore-12.3.0.eb)
* numactl/2.0.16-GCCcore-12.3.0 (numactl-2.0.16-GCCcore-12.3.0.eb)
* UnZip/6.0-GCCcore-12.3.0 (UnZip-6.0-GCCcore-12.3.0.eb)
* UCX/1.14.1-GCCcore-12.3.0 (UCX-1.14.1-GCCcore-12.3.0.eb)
* libxml2/2.11.4-GCCcore-12.3.0 (libxml2-2.11.4-GCCcore-12.3.0.eb)
* cURL/8.0.1-GCCcore-12.3.0 (cURL-8.0.1-GCCcore-12.3.0.eb)
* libevent/2.1.12-GCCcore-12.3.0 (libevent-2.1.12-GCCcore-12.3.0.eb)
* libarchive/3.6.2-GCCcore-12.3.0 (libarchive-3.6.2-GCCcore-12.3.0.eb)
* CMake/3.26.3-GCCcore-12.3.0 (CMake-3.26.3-GCCcore-12.3.0.eb)
* libfabric/1.18.0-GCCcore-12.3.0 (libfabric-1.18.0-GCCcore-12.3.0.eb)
* libffi/3.4.4-GCCcore-12.3.0 (libffi-3.4.4-GCCcore-12.3.0.eb)
* make/4.4.1-GCCcore-12.3.0 (make-4.4.1-GCCcore-12.3.0.eb)
* Tcl/8.6.13-GCCcore-12.3.0 (Tcl-8.6.13-GCCcore-12.3.0.eb)
* SQLite/3.42.0-GCCcore-12.3.0 (SQLite-3.42.0-GCCcore-12.3.0.eb)
* Python/3.11.3-GCCcore-12.3.0 (Python-3.11.3-GCCcore-12.3.0.eb)
* BLIS/0.9.0-GCC-12.3.0 (BLIS-0.9.0-GCC-12.3.0.eb)
* OpenBLAS/0.3.23-GCC-12.3.0 (OpenBLAS-0.3.23-GCC-12.3.0.eb)
* FlexiBLAS/3.3.1-GCC-12.3.0 (FlexiBLAS-3.3.1-GCC-12.3.0.eb)
* xorg-macros/1.20.0-GCCcore-12.3.0 (xorg-macros-1.20.0-GCCcore-12.3.0.eb)
* libpciaccess/0.17-GCCcore-12.3.0 (libpciaccess-0.17-GCCcore-12.3.0.eb)
* hwloc/2.9.1-GCCcore-12.3.0 (hwloc-2.9.1-GCCcore-12.3.0.eb)
* PMIx/4.2.4-GCCcore-12.3.0 (PMIx-4.2.4-GCCcore-12.3.0.eb)
* UCC/1.2.0-GCCcore-12.3.0 (UCC-1.2.0-GCCcore-12.3.0.eb)
* OpenMPI/4.1.5-GCC-12.3.0 (OpenMPI-4.1.5-GCC-12.3.0.eb)
* gompi/2023a (gompi-2023a.eb)
* FFTW.MPI/3.3.10-gompi-2023a (FFTW.MPI-3.3.10-gompi-2023a.eb)
* ScaLAPACK/2.2.0-gompi-2023a-fb (ScaLAPACK-2.2.0-gompi-2023a-fb.eb)
* foss/2023a (foss-2023a.eb)
```

### CODE REVIEW

**Comment by boegel** [comment]
bot: build repo:eessi-2023.06-software arch:x86_64/generic
bot: build repo:eessi-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi-2023.06-software arch:x86_64/intel/skylake_avx512
bot: build repo:eessi-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi-2023.06-software arch:x86_64/amd/zen3
bot: build repo:eessi-2023.06-software arch:aarch64/generic
bot: build repo:eessi-2023.06-software arch:aarch64/neoverse_n1
bot: build repo:eessi-2023.06-software arch:aarch64/neoverse_v1

**Comment by boegel** [comment]
Hmm, job `7322` and `7323` are still running, that's taking way too long, will take a look.

**Comment by boegel** [comment]
bot: build repo:eessi-2023.06-software arch:x86_64/generic
bot: build repo:eessi-2023.06-software arch:x86_64/intel/haswell

**Comment by boegel** [comment]
Same test was hanging again in job 7331, so I killed that process (1734551):

```
bot      1722690  0.0  0.0   6812  2848 ?        S    Sep14   0:00      |       |   |                       \_ make tests BINARY=64 CC=gcc FC=gfortran MAKE_NB_JOBS=-1 USE_OPENMP=1 USE_THREAD=1
bot      1733964  0.0  0.0   6916  2996 ?        S    Sep14   0:00      |       |   |                           \_ make -C utest all
bot      1734551  795  0.1 17009432 40060 ?      Rl   Sep14 8285:21      |       |   |                               \_ ./openblas_utest
```

Looks like that made the OpenBLAS installation fail (no surprise I guess)

**Comment by boegel** [comment]
Looks like we may be hitting https://github.com/xianyi/OpenBLAS/issues/4017, which got fixed in https://github.com/xianyi/OpenBLAS/pull/4163

**Comment by boegel** [comment]
I've also cancelled job 7330, will try again using patch added in https://github.com/easybuilders/easybuild-easyconfigs/pull/18790

**Comment by boegel** [comment]
bot: build repo:eessi-2023.06-software arch:x86_64/generic
bot: build repo:eessi-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi-2023.06-software arch:x86_64/intel/skylake_avx512
bot: build repo:eessi-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi-2023.06-software arch:x86_64/amd/zen3
bot: build repo:eessi-2023.06-software arch:aarch64/generic
bot: build repo:eessi-2023.06-software arch:aarch64/neoverse_n1
bot: build repo:eessi-2023.06-software arch:aarch64/neoverse_v1

**Comment by boegel** [comment]
bot: build repo:eessi-2023.06-software arch:x86_64/generic

**Comment by boegel** [comment]
```
                        -->   LAPACK TESTING SUMMARY  <--
SUMMARY                 nb test run     numerical error         other error
================        ===========     =================       ================
REAL                    1326267         2       (0.000%)        0       (0.000%)
DOUBLE PRECISION        1327545         1       (0.000%)        1       (0.000%)
COMPLEX                 786943          3       (0.000%)        0       (0.000%)
COMPLEX16               786918          26      (0.003%)        0       (0.000%)

--> ALL PRECISIONS      4227673         32      (0.001%)        1       (0.000%)


== 2023-09-15 22:50:01,320 openblas.py:116 INFO 4227673 LAPACK tests run - 32 failed due to numerical errors - 1 failed due to other errors
```

**Comment by laraPPr** [comment]
```
Testing COMPLEX16          Nonsymmetric-Generalized-Eigenvalue-Problem-driver-EIG/xeigtstz < zgd.in > zgd.out  ZGV drivers:     18 out of   1092 tests failed to pass the threshold

 passed: 9390

failing to pass the threshold: 18

```
```
Testing COMPLEX16          Nonsymmetric-Eigenvalue-EIG/xeigtstz < zed.in > zed.out  ZEV:    8 out of  1100 tests failed to pass the threshold

 passed: 12988

failing to pass the threshold: 8
```
```
Testing COMPLEX           Nonsymmetric-Generalized-Eigenvalue-Problem-driver-EIG/xeigtstc < cgd.in > cgd.out  CGV drivers:      3 out of   1092 tests failed to pass the threshold

 passed: 9390

failing to pass the threshold: 3

```

```
Testing DOUBLE PRECISION Nonsymmetric-Generalized-Eigenvalue-Problem-driver-EIG/xeigtstd < dgd.in > dgd.out  DDRGES3: DGGES3 returned INFO=     9.

  DGS drivers:      1 out of   1555 tests failed to pass the threshold

 passed: 8922

failing to pass the threshold: 1

Info Error: 1
```
```
Testing REAL              Nonsymmetric-Eigenvalue-Problem-EIG/xeigtsts < nep.in > snep.out  SHS:    2 out of  2016 tests failed to pass the threshold

 passed: 8064

failing to pass the threshold: 2
```

**Comment by boegel** [comment]
@laraPPr The "`DDRGES3: DGGES3 returned INFO=     9.`" suggests that a test segfaulted there (signal 9 is usually a segfault). Is there any more info available on that in the log?

May be related to https://github.com/xianyi/OpenBLAS/issues/4032

**Comment by laraPPr** [comment]
```
== 2023-09-15 22:14:00,058 run.py:724 DEBUG Using default regular expression: (?<![(,-]|\w)(?:error|segmentation fault|failed)(?![(,-]|\.?\w)

== 2023-09-15 22:14:00,061 run.py:699 WARNING Found 22 potential errors (some may be harmless) in output of  make test :

        ==== cmdAH-24.20.1 Tcl_FileObjCmd: atime 64-bit time_t, bug [4718b41c56] FAILED

        ==== cmdAH-24.20.1 FAILED

        ==== cmdAH-24.20.2 Tcl_FileObjCmd: mtime 64-bit time_t, bug [4718b41c56] FAILED

        ==== cmdAH-24.20.2 FAILED

        ==== cmdAH-25.3 Tcl_FileObjCmd: owned FAILED

        ==== cmdAH-25.3 FAILED

        all.tcl:        Total   34591   Passed  31408   Skipped 3180    Failed  3

        all.tcl:        Total   792     Passed  726     Skipped 66      Failed  0

        all.tcl:        Total   1       Passed  1       Skipped 0       Failed  0

        all.tcl:        Total   13      Passed  13      Skipped 0       Failed  0

        Test file error: couldn't load file "libmysql.so.15": libmysql.so.15: cannot open shared object file: No such file or directory

        all.tcl:        Total   0       Passed  0       Skipped 0       Failed  0

        Test file error: couldn't load file "libiodbc.so": libiodbc.so: cannot open shared object file: No such file or directory

        all.tcl:        Total   0       Passed  0       Skipped 0       Failed  0

        Test file error: couldn't load file "libiodbc.so": libiodbc.so: cannot open shared object file: No such file or directory

        all.tcl:        Total   0       Passed  0       Skipped 0       Failed  0

        Test file error: couldn't load file "libiodbc.so": libiodbc.so: cannot open shared object file: No such file or directory

        all.tcl:        Total   0       Passed  0       Skipped 0       Failed  0

        Test file error: couldn't load file "libpq.so.5": libpq.so.5: cannot open shared object file: No such file or directory

        all.tcl:        Total   0       Passed  0       Skipped 0       Failed  0

        all.tcl:        Total   161     Passed  158     Skipped 3       Failed  0

        all.tcl:        Total   138     Passed  122     Skipped 16      Failed  0

```

**Comment by laraPPr** [comment]
> @laraPPr The "`DDRGES3: DGGES3 returned INFO= 9.`" suggests that a test segfaulted there (signal 9 is usually a segfault). Is there any more info available on that in the log?
> 
> May be related to [xianyi/OpenBLAS#4032](https://github.com/xianyi/OpenBLAS/issues/4032)

I looked at the issue and one of the things that was suggested was to switch out `-ftree-vectorize` with `-fno-tree-vectorize` CFLAGS because het suggests that there have been problems with the flag. But when I go through our logging it seems that both of these flags have been set.

**Comment by laraPPr** [comment]
Sorry I mentioned the wrong pr so the mention above can be ignored

**Comment by martin-frbg** [comment]
no the return code 9 is not SIGSEGV but LAPACK's internal INFO numbering  - in that particular case it is 3 for "reordering of the Schur decomposition failed in DTGSEN" plus the number of eigenvalues expected by the calling DGGES3...

**Comment by boegel** [comment]
bot: build repo:eessi-2023.06-software arch:x86_64/generic

**Comment by boegel** [comment]
last attempt failed due to a download fluke for `make-4.4.1.tar.gz`, trying again...

bot: build repo:eessi-2023.06-software arch:x86_64/generic

**Comment by boegel** [comment]
bot: build repo:eessi-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi-2023.06-software arch:x86_64/intel/skylake_avx512
bot: build repo:eessi-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi-2023.06-software arch:x86_64/amd/zen3
bot: build repo:eessi-2023.06-software arch:aarch64/generic
bot: build repo:eessi-2023.06-software arch:aarch64/neoverse_n1
bot: build repo:eessi-2023.06-software arch:aarch64/neoverse_v1

**Review by bedroge — APPROVED** [review]

**Pull request merged**
