### PR TITLE
{2023.06}[gompi/2023a] netCDF 4.9.2

### PR DESCRIPTION
**Pull request by Neves-P**
First installing `netCDF` v4.9.2 as a necessary dependency of #404

```
1 out of 30 required modules missing:

* netCDF/4.9.2-gompi-2023a (netCDF-4.9.2-gompi-2023a.eb)
```

### CODE REVIEW

**Comment by Neves-P** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1

**Comment by Neves-P** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1

**Comment by Neves-P** [comment]
All builds succeeded!

**Comment by Neves-P** [comment]
On second thought, how did `neoverse_v1` work without the hook?

> New job on instance `eessi-bot-mc-aws` for architecture `aarch64-neoverse_v1` for repository `eessi.io-2023.06-software` in job dir `/project/def-users/SHARED/jobs/2023.12/pr_431/2628`
> date 	job status 	comment
> Dec 19 11:06:30 UTC 2023 	submitted 	job id `2628` awaits release by job manager
> Dec 19 11:06:56 UTC 2023 	released 	job awaits launch by Slurm scheduler
> Dec 19 11:12:35 UTC 2023 	running 	job `2628` is running
> Dec 19 11:21:33 UTC 2023 	finished 	
> 😁 SUCCESS _(click triangle for details)_
> Dec 19 11:21:33 UTC 2023 	test result 	_(no tests yet)_

I forgot to add the hook that skips `netCDF` tests on `neoverse_v1`, which was causing the builds to fail in #404, but now the same thing works without skipping tests? 😵

**Comment by ocaisa** [comment]
Who knows, it could have been some funny side effect of the overlay. IIRC it also worked (unexpectedly) in another PR...I vote we open an issue but move ahead with merging this PR...at the end of the day skipping the test won't change the installation

**Comment by Neves-P** [comment]
That's a very good point and I agree with merging then as is as indeed skipping tests in `neoverse_v1` shouldn't change the installation 👍 To keep the information in the same place I've added a comment on the issue I opened when I made the hook in the first place #425. Happy to open a new one or change #425 if needed too.

**Review by bedroge — APPROVED** [review]

**Review by bedroge — APPROVED** [review]

**Pull request merged**
