### PR TITLE
{2023.06}[foss/2023a] QuantumESPRESSO 7.3

### PR DESCRIPTION
**Pull request by Crivella**
Added Quantum Espresso 7.3 using easyconfig from 

https://github.com/easybuilders/easybuild-easyconfigs/pull/20105 (updated to https://github.com/easybuilders/easybuild-easyconfigs/pull/20306 to allow a single test failure)

and easyblock from

https://github.com/easybuilders/easybuild-easyblocks/pull/3241 (updated to https://github.com/easybuilders/easybuild-easyblocks/pull/3258)

### CODE REVIEW

**Comment by ocaisa** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3

**Comment by ocaisa** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3

**Comment by ocaisa** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3

**Comment by ocaisa** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1

**Comment by ocaisa** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic

**Comment by ocaisa** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1

**Comment by ocaisa** [comment]
For https://github.com/EESSI/software-layer/pull/504#issuecomment-2039049562 I see a single (unexpected) failure in the tests:
```
== 2024-04-05 08:53:37,657 run.py:247 INFO running cmd: cd /tmp/bot/easybuild/build/QuantumESPRESSO/7.3/foss-2023a/qe-7.3/test-suite && NPROCS=1 make run-tests-epw 
== 2024-04-05 10:17:14,824 quantumespresso.py:620 INFO epw: Passed 134 out of 135  (99.26%)
== 2024-04-05 10:17:14,825 quantumespresso.py:639 WARNING epw_2D - epw5.in (arg(s): 5): **FAILED**.
== 2024-04-05 10:17:14,825 quantumespresso.py:644 WARNING |   mobnewx
== 2024-04-05 10:17:14,825 quantumespresso.py:644 WARNING |       ERROR: relative error 1.25e-01 greater than 1.00e-01. (Test: 41.4208.  Benchmark: 47.338.)
== 2024-04-05 10:17:14,825 quantumespresso.py:644 WARNING |   mobnewx
== 2024-04-05 10:17:14,825 quantumespresso.py:644 WARNING |       ERROR: relative error 1.25e-01 greater than 1.00e-01. (Test: 41.8993.  Benchmark: 47.8849.)
== 2024-04-05 10:17:14,825 quantumespresso.py:644 WARNING |   hall
== 2024-04-05 10:17:14,825 quantumespresso.py:644 WARNING |       ERROR: absolute error 3.37e-02 greater than 1.00e-03. (Test: 1.23036.  Benchmark: 1.26404.)
== 2024-04-05 10:17:14,825 quantumespresso.py:644 WARNING |       ERROR: relative error 2.66e-02 greater than 1.00e-03. (Test: 1.23036.  Benchmark: 1.26404.)
== 2024-04-05 10:17:14,825 quantumespresso.py:644 WARNING |   hall
== 2024-04-05 10:17:14,825 quantumespresso.py:644 WARNING |       ERROR: absolute error 1.30e-02 greater than 1.00e-03. (Test: 1.24065.  Benchmark: 1.25365.)
== 2024-04-05 10:17:14,825 quantumespresso.py:644 WARNING |       ERROR: relative error 1.04e-02 greater than 1.00e-03. (Test: 1.24065.  Benchmark: 1.25365.)
== 2024-04-05 10:17:14,825 quantumespresso.py:644 WARNING |   mobnewy
== 2024-04-05 10:17:14,826 quantumespresso.py:644 WARNING |       ERROR: relative error 1.25e-01 greater than 1.00e-01. (Test: 41.4208.  Benchmark: 47.338.)
== 2024-04-05 10:17:14,826 quantumespresso.py:644 WARNING |   mobnewy
== 2024-04-05 10:17:14,826 quantumespresso.py:644 WARNING |       ERROR: relative error 1.25e-01 greater than 1.00e-01. (Test: 41.8993.  Benchmark: 47.8849.)
== 2024-04-05 10:17:14,826 quantumespresso.py:654 INFO Total tests passed 526 out of 531  (99.06%)
== 2024-04-05 10:17:14,826 quantumespresso.py:656 WARNING The following tests failed:
== 2024-04-05 10:17:14,826 quantumespresso.py:658 WARNING |   epw_2D - epw5.in (arg(s): 5): **FAILED**.
== 2024-04-05 10:17:14,906 build_log.py:171 ERROR EasyBuild crashed with an error (at easybuild/tools/build_log.py:111 in caller_info): Test suite failed with 1 failures (0 failures permitted) (at easybuild/easyblocks/quantumespresso.py:664 in test_step)
```
and for https://github.com/EESSI/software-layer/pull/504#issuecomment-2039049474 I see a different failing test (which seems ignorable)
```
== 2024-04-05 09:00:52,571 run.py:247 INFO running cmd: cd /tmp/bot/easybuild/build/QuantumESPRESSO/7.3/foss-2023a/qe-7.3/test-suite && NPROCS=1 make run-tests-epw 
== 2024-04-05 10:33:17,369 quantumespresso.py:620 INFO epw: Passed 134 out of 135  (99.26%)
== 2024-04-05 10:33:17,369 quantumespresso.py:639 WARNING epw_plrn - epw2.in (arg(s): 3): **FAILED**.
== 2024-04-05 10:33:17,370 quantumespresso.py:644 WARNING |   eplrn
== 2024-04-05 10:33:17,370 quantumespresso.py:644 WARNING |       ERROR: relative error 1.01e-02 greater than 1.00e-02. (Test: -2.039899.  Benchmark: -2.0195773.)
== 2024-04-05 10:33:17,370 quantumespresso.py:654 INFO Total tests passed 526 out of 531  (99.06%)
== 2024-04-05 10:33:17,370 quantumespresso.py:656 WARNING The following tests failed:
== 2024-04-05 10:33:17,370 quantumespresso.py:658 WARNING |   epw_plrn - epw2.in (arg(s): 3): **FAILED**.
== 2024-04-05 10:33:17,445 build_log.py:171 ERROR EasyBuild crashed with an error (at easybuild/tools/build_log.py:111 in caller_info): Test suite failed with 1 failures (0 failures permitted) (at easybuild/easyblocks/quantumespresso.py:664 in test_step)
```

I'll make a PR to allow a single failed test as we will move to a CMake build of QE for 7.3.1 (which is now preferred by the devels) and can try to work directly with the deveolpers there to address issues in the tests.

**Comment by ocaisa** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell

**Comment by maxim-masterov** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1

**Comment by ocaisa** [comment]
I'm closing this since we have a working PR with QE 7.3.1 almost ready (and 7.3 has known bugs)...but it's good to know that it worked as the test suite for the easyblock is currently more extensive in the autotools-based build.

**Pull request closed without merging**
