### PR TITLE
{2023.06}[foss/2023a] grpcio v1.57.0

### PR DESCRIPTION
**Pull request by trz42**
grpcio/1.57.0 is a missing dependency for builds in #603 / #585

It may require some tweaks to `preinstallopts` which we don't use initially (to confirm that those are needed).

### CODE REVIEW

**Comment by trz42** [comment]
Do a few builds initially only...

bot: build repo:eessi.io-2023.06-software arch:zen3
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic
bot: build repo:eessi.io-2023.06-software arch:zen4

**Comment by trz42** [comment]
Two builds failed with the `zlib` issue. One failed due to full disk. Enabled the `zlib` parse hook fix and cleaned up disk...

bot: build repo:eessi.io-2023.06-software arch:zen3
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic
bot: build repo:eessi.io-2023.06-software arch:zen4

**Comment by ocaisa** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1

**Review by ocaisa — APPROVED** [review]
LGTM

**Review by ocaisa — APPROVED** [review]

**Pull request merged**
