### PR TITLE
add zen4 / AMD Genoa

### PR DESCRIPTION
**Pull request by hmeiland**
updated tests and config files;

### CODE REVIEW

**Comment by ocaisa** [comment]
I don't think we've actually thought about what to do if someone wants to introduce a new architecture into EESSI production. This is another use case for a development repo that sits on top of production EESSI, you figure out how far you can get there and then when things are mature you can rebuild them into production.

**Comment by boegel** [comment]
@hmeiland Somehow there's a merge conflict now here...

**Comment by boegel** [comment]
> I don't think we've actually thought about what to do if someone wants to introduce a new architecture into EESSI production. This is another use case for a development repo that sits on top of production EESSI, you figure out how far you can get there and then when things are mature you can rebuild them into production.

That's totally orthogonal to this PR, no?

Let's follow up on that in https://gitlab.com/eessi/support/-/issues/37

**Comment by ocaisa** [comment]
> That's totally orthogonal to this PR, no?
> 
> Let's follow up on that in https://gitlab.com/eessi/support/-/issues/37

Almost orthogonal but not quite, current CI assumes that if something is supported (in CI) by archdetect, then there should be a corresponding software directory. It was a bit looser before (checking that it had to be available in _some_ EESSI version, which is to accommodate the deprecation of Power).

**Comment by hmeiland** [comment]
moved to #451

**Pull request closed without merging**
