### PR TITLE
Rebuild hatchling-1.18.0-GCCcore-12.3.0

### PR DESCRIPTION
**Pull request by Neves-P**
Following from: https://gitlab.com/eessi/support/-/issues/85

### CODE REVIEW

**Comment by Neves-P** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1

**Comment by Neves-P** [comment]
> New job on instance `eessi-bot-mc-aws` for architecture `aarch64-neoverse_n1` for repository `eessi.io-2023.06-software` in job dir `/project/def-users/SHARED/jobs/2024.08/pr_669/16216`
> date 	job status 	comment
> Aug 14 15:17:45 UTC 2024 	submitted 	job id `16216` awaits release by job manager
> Aug 14 15:18:14 UTC 2024 	released 	job awaits launch by Slurm scheduler
> Aug 14 15:23:17 UTC 2024 	running 	job `16216` is running
> Aug 14 15:59:53 UTC 2024 	finished 	
> 😢 FAILURE _(click triangle for details)_
> 
> _Details_
>     ✅ job output file `slurm-16216.out`
>     ❌ found message matching `ERROR: `
>     ❌ found message matching `FAILED: `
>     ❌ found message matching ` required modules missing:`
>     ❌ no message matching `No missing installations`
>     ✅ found message matching `.tar.gz created!`
> _Artefacts_
> 
> Aug 14 15:59:53 UTC 2024 	test result 	
> 😁 SUCCESS _(click triangle for details)_

Looking at the build log we see
``` 
ERROR: Could not install packages due to an OSError.
Consider using the `--user` option or check the permissions.
Traceback (most recent call last):
  ...
  File "/cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/neoverse_n1/software/Python/3.11.3-GCCcore-12.3.0/lib/python3.11/site-packages/pip/_vendor/distlib/scripts.py", line 293, in _write_script
    self._fileop.write_binary_file(outname, script_bytes)
  File "/cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/neoverse_n1/software/Python/3.11.3-GCCcore-12.3.0/lib/python3.11/site-packages/pip/_vendor/distlib/util.py", line 555, in write_binary_file
    os.remove(path)
PermissionError: [Errno 13] Permission denied: '/cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/neoverse_n1/software/hatchling/1.18.0-GCCcore-12.3.0/bin/hatchling'
 (at easybuild/tools/run.py:682 in parse_cmd_output)
```

This is almost certainly the same @bedroge solved here: https://github.com/EESSI/software-layer/pull/555#issuecomment-2085462158

**Comment by Neves-P** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1

**Comment by Neves-P** [comment]
Failed test:

```
================================================================================
SUMMARY OF FAILURES
--------------------------------------------------------------------------------
FAILURE INFO for EESSI_LAMMPS_lj %scale=1_node %device_type=cpu %module_name=LAMMPS/2Aug2023_update2-foss-2023a-kokkos (run: 1/1)
  * Description:
  * System partition: BotBuildTests:default
  * Environment: default
  * Stage directory: /project/60006/SHARED/jobs/2024.08/pr_669/event_47bfab50-5bb0-11ef-89f6-9f388b4fa992/run_000/linux_aarch64_neoverse_n1/eessi.io-2023.06-software/reframe_runs/stage/BotBuildTests/default/default/EESSI_LAMMPS_lj_04ff9ece
  * Node list: aarch64-neoverse-n1-node1.int.aws-rocky88-202310
  * Job type: local (id=27215)
  * Dependencies (conceptual): []
  * Dependencies (actual): []
  * Maintainers: []
  * Failing phase: sanity
  * Rerun with '-n /04ff9ece -p default --system BotBuildTests:default -r'
  * Reason: sanity error: 4.340000000002675e-05 >= 1e-06
--- rfm_job.out (first 10 lines) ---
LAMMPS (2 Aug 2023 - Update 2)
  using 1 OpenMP thread(s) per MPI task
Lattice spacing in x,y,z = 1.6795962 1.6795962 1.6795962
Created orthogonal box = (0 0 0) to (33.591924 33.591924 33.591924)
  2 by 2 by 4 MPI processor grid
Created 32000 atoms
  using lattice units in orthogonal box = (0 0 0) to (33.591924 33.591924 33.591924)
  create_atoms CPU = 0.001 seconds
Generated 0 of 0 mixed pair_coeff terms from geometric mixing rule
Neighbor list info ...
--- rfm_job.out ---
--- rfm_job.err (first 10 lines) ---
--- rfm_job.err ---
--------------------------------------------------------------------------------
```

**Comment by Neves-P** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1

**Comment by Neves-P** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512

**Comment by Neves-P** [comment]
My mistake, did not add write permissions recursively.

bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512

**Comment by Neves-P** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512

**Comment by Neves-P** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell

**Comment by boegel** [comment]
Hmm, I only see this in build log:
```
== hatchling/1.18.0-GCCcore-12.3.0 is already installed (module found), skipping
```

Aren't we missing a `--rebuild` option here?

**Comment by Neves-P** [comment]
> Aren't we missing a `--rebuild` option here?

Interesting, I figured just adding the easyconfig to the rebuild easystack would trigger it as a rebuild in zen4 as well 🤔 Maybe I'm missing a step...

**Comment by casparvl** [comment]
I dont think it should be different for zen4. Dont have time to check logs now, but we should check if it goes into the `else` statement correctly here: https://github.com/EESSI/software-layer/blob/1fc0cb75a076a37184b9abddba2093118bdcfca6/bot/build.sh#L188

This should remove the installation in the overlay. Since the same overlay is then used at Build time (or should be, at least), we don't actually need `--rebuild`: the previous installation is gone when easybuild is invoked on the easy stack file.

**Comment by casparvl** [comment]
Checked the logs, the removal step fails, since some `fakeroot`-related dir doesn't exist:

```
Executing command to remove software:
./eessi_container.sh --verbose --access rw --mode run --container docker://ghcr.io/eessi/build-node:debian11 --repository eessi.io-2023.06-software --save /project/60006/SHARED/jobs/2024.08/pr_669/event_aa65ed90-5c15-11ef-9f64-c9653d7e0953/run_000/linux_x86_64_amd_zen4/eessi.io-2023.06
-software/previous_tmp/removal_step --storage /tmp/bot/EESSI --fakeroot
                     -- ./EESSI-remove-software.sh "" "" 2>&1 | tee -a remove.outerr.yEdX
checking for duplicates: 'eessi.io-2023.06-software' and 'eessi.io-2023.06-software'
repo 'eessi.io-2023.06-software' is not an EESSI CVMFS repository...
Using /tmp/bot/EESSI/eessi.vxf0XHi8WL as tmp directory (to resume session add '--resume /tmp/bot/EESSI/eessi.vxf0XHi8WL').
EESSI_TMPDIR=/tmp/bot/EESSI/eessi.vxf0XHi8WL
HOST_INJECTIONS=/tmp/bot/EESSI/eessi.vxf0XHi8WL/opt-eessi
SINGULARITY_CACHEDIR=/project/def-users/bot/.cache/containers/x86_64
Pulling container image from docker://ghcr.io/eessi/build-node:debian11 to /tmp/bot/EESSI/eessi.vxf0XHi8WL/ghcr.io_eessi_build_node_debian11.sif
INFO:    Environment variable SINGULARITY_TMPDIR is set, but APPTAINER_TMPDIR is preferred
INFO:    Environment variable SINGULARITY_CACHEDIR is set, but APPTAINER_CACHEDIR is preferred
INFO:    Using cached SIF image
CONTAINER=/tmp/bot/EESSI/eessi.vxf0XHi8WL/ghcr.io_eessi_build_node_debian11.sif
EESSI_CVMFS_VAR_LIB=/tmp/bot/EESSI/eessi.vxf0XHi8WL/var-lib-cvmfs
EESSI_CVMFS_VAR_RUN=/tmp/bot/EESSI/eessi.vxf0XHi8WL/var-run-cvmfs
SINGULARITY_HOME=/project/60006/SHARED/jobs/2024.08/pr_669/event_aa65ed90-5c15-11ef-9f64-c9653d7e0953/run_000/linux_x86_64_amd_zen4/eessi.io-2023.06-software:/eessi_bot_job
BIND_PATHS=/tmp/bot/EESSI/eessi.vxf0XHi8WL/var-lib-cvmfs:/var/lib/cvmfs,/tmp/bot/EESSI/eessi.vxf0XHi8WL/var-run-cvmfs:/var/run/cvmfs,/tmp/bot/EESSI/eessi.vxf0XHi8WL/opt-eessi:/opt/eessi,/tmp/bot/EESSI/eessi.vxf0XHi8WL:/tmp

BIND_PATHS before processing REPOSITORIES
  BIND_PATHS=/tmp/bot/EESSI/eessi.vxf0XHi8WL/var-lib-cvmfs:/var/lib/cvmfs,/tmp/bot/EESSI/eessi.vxf0XHi8WL/var-run-cvmfs:/var/run/cvmfs,/tmp/bot/EESSI/eessi.vxf0XHi8WL/opt-eessi:/opt/eessi,/tmp/bot/EESSI/eessi.vxf0XHi8WL:/tmp

process CVMFS repo spec 'eessi.io-2023.06-software'
default.local --> /etc/cvmfs/default.local
eessi.io/eessi.io.pub --> /etc/cvmfs/keys/eessi.io/eessi.io.pub
eessi.io.conf --> /etc/cvmfs/domain.d/eessi.io.conf
BIND_PATHS after processing 'eessi.io-2023.06-software'
  BIND_PATHS=/tmp/bot/EESSI/eessi.vxf0XHi8WL/var-lib-cvmfs:/var/lib/cvmfs,/tmp/bot/EESSI/eessi.vxf0XHi8WL/var-run-cvmfs:/var/run/cvmfs,/tmp/bot/EESSI/eessi.vxf0XHi8WL/opt-eessi:/opt/eessi,/tmp/bot/EESSI/eessi.vxf0XHi8WL:/tmp,/tmp/bot/EESSI/eessi.vxf0XHi8WL/repos_cfg/default.local:/etc/cvmfs/default.local,/tmp/bot/EESSI/eessi.vxf0XHi8WL/repos_cfg/eessi.io/eessi.io.pub:/etc/cvmfs/keys/eessi.io/eessi.io.pub,/tmp/bot/EESSI/eessi.vxf0XHi8WL/repos_cfg/eessi.io.conf:/etc/cvmfs/domain.d/eessi.io.conf

add fusemount options for CVMFS repo 'eessi.io-2023.06-software'
repo 'eessi.io-2023.06-software' is not an EESSI CVMFS repository...
TMP directory contents:
total 369488
-rwxr-xr-x. 1 bot bot 378355712 Aug 16 21:27 ghcr.io_eessi_build_node_debian11.sif
drwxr-xr-x. 2 bot bot         6 Aug 16 21:27 opt-eessi
drwxr-xr-x. 3 bot bot        81 Aug 16 21:27 repos_cfg
drwxr-xr-x. 4 bot bot        47 Aug 16 21:27 software.eessi.io
drwxr-xr-x. 2 bot bot         6 Aug 16 21:27 var-lib-cvmfs
drwxr-xr-x. 2 bot bot         6 Aug 16 21:27 var-run-cvmfs
SINGULARITY_BIND=/project/def-users/SHARED/build-logs,/project/def-users/bot/shared,/tmp/bot/EESSI/eessi.vxf0XHi8WL/var-lib-cvmfs:/var/lib/cvmfs,/tmp/bot/EESSI/eessi.vxf0XHi8WL/var-run-cvmfs:/var/run/cvmfs,/tmp/bot/EESSI/eessi.vxf0XHi8WL/opt-eessi:/opt/eessi,/tmp/bot/EESSI/eessi.vxf0XHi8WL:/tmp,/tmp/bot/EESSI/eessi.vxf0XHi8WL/repos_cfg/default.local:/etc/cvmfs/default.local,/tmp/bot/EESSI/eessi.vxf0XHi8WL/repos_cfg/eessi.io/eessi.io.pub:/etc/cvmfs/keys/eessi.io/eessi.io.pub,/tmp/bot/EESSI/eessi.vxf0XHi8WL/repos_cfg/eessi.io.conf:/etc/cvmfs/domain.d/eessi.io.conf
Launching container with command (next line):
singularity  run --fakeroot --fusemount container:cvmfs2 cvmfs-config.cern.ch /cvmfs/cvmfs-config.cern.ch --fusemount container:cvmfs2 software.eessi.io /cvmfs_ro/software.eessi.io --fusemount container:fuse-overlayfs -o lowerdir=/cvmfs_ro/software.eessi.io -o upperdir=/tmp/software.eessi.io/overlay-upper -o workdir=/tmp/software.eessi.io/overlay-work /cvmfs/software.eessi.io /tmp/bot/EESSI/eessi.vxf0XHi8WL/ghcr.io_eessi_build_node_debian11.sif ./EESSI-remove-software.sh
INFO:    Environment variable SINGULARITY_BIND is set, but APPTAINER_BIND is preferred
INFO:    Environment variable SINGULARITY_HOME is set, but APPTAINER_HOME is preferred
INFO:    Environment variable SINGULARITY_TMPDIR is set, but APPTAINER_TMPDIR is preferred
INFO:    User not listed in /etc/subuid, trying root-mapped namespace
INFO:    Environment variable SINGULARITY_BIND is set, but APPTAINER_BIND is preferred
INFO:    Environment variable SINGULARITY_HOME is set, but APPTAINER_HOME is preferred
INFO:    Environment variable SINGULARITY_TMPDIR is set, but APPTAINER_TMPDIR is preferred
INFO:    Using fakeroot command combined with root-mapped namespace
unknown argument ignored: lazytime
CernVM-FS: pre-mounted on file descriptor 3
CernVM-FS: pre-mounted on file descriptor 3
FATAL:   exec /.singularity.d/libs/fakeroot failed: fork/exec /.singularity.d/libs/fakeroot: no such file or directory
Saved contents of tmp directory '/tmp/bot/EESSI/eessi.vxf0XHi8WL' to tarball '/project/60006/SHARED/jobs/2024.08/pr_669/event_aa65ed90-5c15-11ef-9f64-c9653d7e0953/run_000/linux_x86_64_amd_zen4/eessi.io-2023.06-software/previous_tmp/removal_step/-1723843637.tgz' (to resume session add '--resume /project/60006/SHARED/jobs/2024.08/pr_669/event_aa65ed90-5c15-11ef-9f64-c9653d7e0953/run_000/linux_x86_64_amd_zen4/eessi.io-2023.06-software/previous_tmp/removal_step/-1723843637.tgz')
```

**Comment by boegel** [comment]
Workaround has been put in place to fix `fakeroot` problem (see https://github.com/apptainer/apptainer/issues/2189) for now

**Comment by boegel** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen4

**Comment by boegel** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/a64fx

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Hmm, also seeing this when rebuilding `hatchling` for `a64fx`:
```
== hatchling/1.18.0-GCCcore-12.3.0 is already installed (module found), skipping
```

Same problem as we saw with `zen4`:
```
FATAL:   could not use fakeroot: no mapping entry found in /etc/subuid for kehoste
```

Problem is this time there's no easy fix, since we don't have control over the configuration of the workernode on which we're running...

So it seems like we need to re-visit the use of `--fakeroot`, since we can't/shouldn't assume it works everywhere?

Thoughts here @casparvl?

**Comment by boegel** [comment]
@Neves-P has manually removed `` for A64FX, so rebuilding should work now, so we can wrap this up (and follow up on the `--fakeroot` issues later)

bot: build repo:eessi.io-2023.06-software arch:aarch64/a64fx

**Review by boegel — APPROVED** [review]
lgtm

**Comment by Neves-P** [comment]
Manually removed old tarballs and added new ones. Procedure:

``` bash
#!/bin/bash

# Remove and replace hatchling 1.18.0 GCCcore-12.3.0 PR 669 - Pedro Santos Neves

# Remove existing installs (A64FX was removed previously in order to build)
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/hatchling/1.18.0-GCCcore-12.3.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/hatchling/1.18.0-GCCcore-12.3.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen4/software/hatchling/1.18.0-GCCcore-12.3.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/hatchling/1.18.0-GCCcore-12.3.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/software/hatchling/1.18.0-GCCcore-12.3.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/generic/software/hatchling/1.18.0-GCCcore-12.3.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/generic/software/hatchling/1.18.0-GCCcore-12.3.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/neoverse_n1/software/hatchling/1.18.0-GCCcore-12.3.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/neoverse_v1/software/hatchling/1.18.0-GCCcore-12.3.0

# Move to software dir
cd /cvmfs/software.eessi.io/versions

# Unpack tarballs
tar xvzf /srv/tmp/tarballs/eessi-2023.06-software-linux-aarch64-a64fx-1724259587.tar.gz
tar xvzf /srv/tmp/tarballs/eessi-2023.06-software-linux-x86_64-amd-zen4-1724152985.tar.gz
tar xvzf /srv/tmp/tarballs/eessi-2023.06-software-linux-x86_64-intel-haswell-1723819673.tar.gz
tar xvzf /srv/tmp/tarballs/eessi-2023.06-software-linux-x86_64-amd-zen3-1723819613.tar.gz
tar xvzf /srv/tmp/tarballs/eessi-2023.06-software-linux-x86_64-amd-zen2-1723819605.tar.gz
tar xvzf /srv/tmp/tarballs/eessi-2023.06-software-linux-x86_64-generic-1723819622.tar.gz
tar xvzf /srv/tmp/tarballs/eessi-2023.06-software-linux-aarch64-neoverse_v1-1723819484.tar.gz
tar xvzf /srv/tmp/tarballs/eessi-2023.06-software-linux-aarch64-generic-1723819504.tar.gz
tar xvzf /srv/tmp/tarballs/eessi-2023.06-software-linux-x86_64-intel-skylake_avx512-1723817335.tar.gz
tar xvzf /srv/tmp/tarballs/eessi-2023.06-software-linux-aarch64-neoverse_n1-1723805793.tar.gz
```
Looks as expected AFAICS.

If everything looks good, PR can be closed (or merged?)

**Comment by boegel** [comment]
Verified, looks good:
```
$ ls -ld /cvmfs/software.eessi.io/versions/2023.06/software/linux/*/*/software/hatchling/*/lib/python3.11/site-packages/* | grep requirements
dr-xr-xr-x  3 cvmfs cvmfs   60 Aug 21 18:57 /cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/a64fx/software/hatchling/1.18.0-GCCcore-12.3.0/lib/python3.11/site-packages/hatch_requirements_txt
dr-xr-xr-x  3 cvmfs cvmfs  146 Aug 21 18:57 /cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/a64fx/software/hatchling/1.18.0-GCCcore-12.3.0/lib/python3.11/site-packages/hatch_requirements_txt-0.4.1.dist-info
dr-xr-xr-x  3 cvmfs cvmfs   60 Aug 16 16:44 /cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/generic/software/hatchling/1.18.0-GCCcore-12.3.0/lib/python3.11/site-packages/hatch_requirements_txt
dr-xr-xr-x  3 cvmfs cvmfs  146 Aug 16 16:44 /cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/generic/software/hatchling/1.18.0-GCCcore-12.3.0/lib/python3.11/site-packages/hatch_requirements_txt-0.4.1.dist-info
dr-xr-xr-x  3 cvmfs cvmfs   60 Aug 16 12:55 /cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/neoverse_n1/software/hatchling/1.18.0-GCCcore-12.3.0/lib/python3.11/site-packages/hatch_requirements_txt
dr-xr-xr-x  3 cvmfs cvmfs  146 Aug 16 12:55 /cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/neoverse_n1/software/hatchling/1.18.0-GCCcore-12.3.0/lib/python3.11/site-packages/hatch_requirements_txt-0.4.1.dist-info
dr-xr-xr-x  3 cvmfs cvmfs   60 Aug 16 16:44 /cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/neoverse_v1/software/hatchling/1.18.0-GCCcore-12.3.0/lib/python3.11/site-packages/hatch_requirements_txt
dr-xr-xr-x  3 cvmfs cvmfs  146 Aug 16 16:44 /cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/neoverse_v1/software/hatchling/1.18.0-GCCcore-12.3.0/lib/python3.11/site-packages/hatch_requirements_txt-0.4.1.dist-info
dr-xr-xr-x  3 cvmfs cvmfs   60 Aug 16 16:46 /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/generic/software/hatchling/1.18.0-GCCcore-12.3.0/lib/python3.11/site-packages/hatch_requirements_txt
dr-xr-xr-x  3 cvmfs cvmfs  146 Aug 16 16:46 /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/generic/software/hatchling/1.18.0-GCCcore-12.3.0/lib/python3.11/site-packages/hatch_requirements_txt-0.4.1.dist-info
```

**Pull request merged**
