### PR TITLE
{2023.06}[foss/2022b] data-lang

### PR DESCRIPTION
**Pull request by TopRichard**
missing packages :
```
bokeh/3.2.1-foss-2022b
dask/2023.7.1-foss-2022b
meson-python/0.11.0-GCCcore-12.2.0
netcdf4-python/1.6.3-foss-2022b
Ruby/3.2.2-GCCcore-12.2.0
setuptools/64.0.3-GCCcore-12.2.0
```

### CODE REVIEW

**Comment by TopRichard** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic

**Comment by TopRichard** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
all staging PRs merged...

**Pull request merged**
