### PR TITLE
Allow EESSI-extend to work even when LMOD_EXACT_MATCH is set

### LINKED ISSUE #746: EESSI-extend doesn't load on systems which have `LMOD_EXACT_MATCH=yes`
EESSI-extend just tries to load the default EasyBuild version. This doesn't work when a system requires `LMOD_EXACT_MATCH=yes`

```
{EESSI 2023.06} [casparl@tcn1 software-layer]$ module load EESSI-extend/2023.06-easybuild
-- Using /tmp/$USER as a temporary working directory for installations, you can override this by setting the environment variable WORKING_DIR and reloading the module (e.g., /dev/shm is a common option)
Configuring for use of EESSI_USER_INSTALL under /home/casparl/eessi
-- To create installations for EESSI, you _must_ have write permissions to /home/casparl/eessi/versions/2023.06/software/linux/x86_64/amd/zen2
-- You may wish to configure a sources directory for EasyBuild (for example, via setting the environment variable EASYBUILD_SOURCEPATH) to allow you to reuse existing sources for packages.
Lmod has detected the following error:  These module(s) or extension(s) exist but cannot be loaded as requested: "EasyBuild"
   Try: "module spider EasyBuild" to see how to load the module(s).

Executing this command requires loading "EasyBuild" which failed while processing the following module(s):

    Module fullname                 Module Filename
    ---------------                 ---------------
    EESSI-extend/2023.06-easybuild  /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/modules/all/EESSI-extend/2023.06-easybuild.lua
```

(we enforce this on our system since we got tired of people relying on defaults and then complaining that their code ran differently when we installed some new version - and they simply weren't aware :))

One option would be to have the EasyBuild version as a suffix - in which case there would be multiple EESSI-extend modules. Alternatively, maybe the module can still be convinced to load a default (can a module change lmod config on the fly...?) version. Or at least print a somewhat more clear error.

Note that as a workaroud, I load an EasyBuild module first, then load `EESSI-extend`. That way, it works

### PR DESCRIPTION
**Pull request by ocaisa**
Fixes #746

### CODE REVIEW

**Comment by ocaisa** [comment]
bot: build repo:eessi.io-2023.06-software arch:zen3
bot: build repo:eessi.io-2023.06-software arch:zen2
bot: build repo:eessi.io-2023.06-software arch:skylake_512
bot: build repo:eessi.io-2023.06-software arch:haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic
bot: build repo:eessi.io-2023.06-software arch:neoverse_n1
bot: build repo:eessi.io-2023.06-software arch:neoverse_v1

**Comment by ocaisa** [comment]
bot: build repo:eessi.io-2023.06-software arch:zen4

**Comment by casparvl** [comment]
bot: build repo:eessi.io-2023.06-software arch:zen3
bot: build repo:eessi.io-2023.06-software arch:zen2
bot: build repo:eessi.io-2023.06-software arch:skylake_512
bot: build repo:eessi.io-2023.06-software arch:haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic
bot: build repo:eessi.io-2023.06-software arch:neoverse_n1
bot: build repo:eessi.io-2023.06-software arch:neoverse_v1

**Comment by ocaisa** [comment]
bot: build repo:eessi.io-2023.06-software arch:skylake_avx512

**Comment by casparvl** [comment]
```
== 2024-09-25 13:48:25,495 build_log.py:171 ERROR EasyBuild crashed with an error (at easybuild/tools/build_log.py:111 in caller_info): Failed to write to /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/EESSI-extend/2023.06-easybuild/easybuild/EESSI-ex
tend-2023.06-easybuild-easybuild-devel: [Errno 13] Permission denied: '/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/EESSI-extend/2023.06-easybuild/easybuild/EESSI-extend-2023.06-easybuild-easybuild-devel' (at easybuild/tools/filetools.py:295 in writ
e_file)
```
Hm... maybe the removal step didn't (completely) succeed or something?

**Comment by casparvl** [comment]
Hm, the removal step prints:
```
ESC[33mRemoving /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/EESSI-extend/2023.06-easybuild and /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/modules/all/EESSI-extend/2023.06-easybuild.lua...ESC[0m
```
So that seems to have removed the correct path? I don't know what's going wrong here :\

**Comment by casparvl** [comment]
A bit larger context:
```
== 2024-09-25 13:48:25,432 easyconfig.py:2647 DEBUG Determining full module name for EESSI-extend EasyConfig @ /project/60006/SHARED/jobs/2024.09/pr_747/event_92300d70-7b44-11ef-8b71-eda159d337f8/run_000/linux_x86_64_amd_zen3/eessi.io-2023.06-software/EESSI-extend-2023.06-easybuild.eb (force_visible: False)
== 2024-09-25 13:48:25,432 easyconfig.py:2624 DEBUG No alternative software name specified to determine module name with
== 2024-09-25 13:48:25,433 utilities.py:115 DEBUG Module name EESSI-extend/2023.06-easybuild validated
== 2024-09-25 13:48:25,433 easyconfig.py:2655 DEBUG Obtained valid full module name EESSI-extend/2023.06-easybuild
== 2024-09-25 13:48:25,433 easyblock.py:1247 DEBUG Writing devel module to /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/EESSI-extend/2023.06-easybuild/easybuild/EESSI-extend-2023.06-easybuild-easybuild-devel
== 2024-09-25 13:48:25,433 filetools.py:250 INFO Overwriting existing file /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/EESSI-extend/2023.06-easybuild/easybuild/EESSI-extend-2023.06-easybuild-easybuild-devel
== 2024-09-25 13:48:25,433 filetools.py:1943 DEBUG Not creating existing path /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/EESSI-extend/2023.06-easybuild/easybuild
== 2024-09-25 13:48:25,495 build_log.py:171 ERROR EasyBuild crashed with an error (at easybuild/tools/build_log.py:111 in caller_info): Failed to write to /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/EESSI-extend/2023.06-easybuild/easybuild/EESSI-extend-2023.06-easybuild-easybuild-devel: [Errno 13] Permission denied: '/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/EESSI-extend/2023.06-easybuild/easybuild/EESSI-extend-2023.06-easybuild-easybuild-devel' (at easybuild/tools/filetools.py:295 in write_file)
```
It does say "Overwriting existing file ...". I'm really not sure how that file can exist. It should't.

**Comment by ocaisa** [comment]
@bedroge @trz42  Is this an issue with the build container? It sounds a little familiar

**Comment by bedroge** [comment]
I've seen similar issues before where the files would suddenly reappear although they had been removed. In all cases this was with (Python) bundles, and I really don't know why it's only happening for those... As a workaround I could make this installation directory writable again on the repo.

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen4

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512

**Comment by bedroge** [comment]
Last attempt before I give up...

bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512

**Comment by bedroge** [comment]
That one also failed. I don't know what's going on here. I've added write permissions (for everyone), changed the ownership to first the eessi user and later the user id of the bot, but nothing seems to work. Usually this does solve those issues...

**Comment by bedroge** [comment]
If we want to get this ingested/merged soon, the only other workaround that I can think of is removing the entire `easybuild` directory in the installation directories. That should be harmless (users only need the module file, right?), and it's the directory it's complaining about in the errors, so I'd hope that would solve the issue.

**Comment by casparvl** [comment]
@bedroge as in: you'd do that manually, right? Maybe make a tarball first, so we can restore it if we want (or can you undo such a transaction in some way?). Then, go right ahead. I haven't seen this issue before, I really don't understand what's special about this case that we see it here. But if we can apply a workaround, I would. (if it pops up once more in another PR, we should investigate further and solve the root cause)

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen4
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512

**Comment by bedroge** [comment]
> @bedroge as in: you'd do that manually, right? Maybe make a tarball first, so we can restore it if we want (or can you undo such a transaction in some way?). Then, go right ahead. I haven't seen this issue before, I really don't understand what's special about this case that we see it here. But if we can apply a workaround, I would. (if it pops up once more in another PR, we should investigate further and solve the root cause)

Yes, it's a manual operation and we can easily roll back if necessary. I've just done this, hopefully the rebuilds will succeed this time...

It definitely happened before, so I'd really like to have this fixed, but I've been looking into this before and I really have no clue what's going on and why it's only happening in some cases.

See https://github.com/EESSI/software-layer/issues/556. While just going through that issue again, I actually found that we hit the same issue before with EESSI-extend, and I also had to remove some files manually. For Python bundles, just changing the permissions is usually sufficient.

**Review by bedroge — APPROVED** [review]

**Pull request merged**
