### PR TITLE
Run test suite

### PR DESCRIPTION
**Pull request by casparvl**
First attempt at actually trying to run the test suite in the `test.sh` step from the bot _and_ having the result checked in the `check-test.sh` step.

My understanding of how the bot executes these steps is a bit limited though, so this will probably take a bit of trial and error before it does what it should do :)

### CODE REVIEW

**Comment by casparvl** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2

**Comment by casparvl** [comment]
Well, it _did_ run. But clearly I have to change things :D
```
bot/test.sh script found in '/project/60006/SHARED/jobs/2024.02/pr_466/event_201af980-c1ee-11ee-826f-092bb38801c8/run_000/linux_x86_64_amd_zen2/eessi.io-2023.06-software', so running it!
bot/test.sh: line 18: module: command not found
FAILED to load the ReFrame module
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'hpctestlib'
FAILED to load hpctestlib
Cloning into 'EESSI-test-suite'...
bot/test.sh: line 38: reframe: command not found
FAILED to run ReFrame
bot/test.sh: line 42: reframe: command not found
FAILED to list ReFrame tests
bot/test.sh: line 45: reframe: command not found
bot/test.sh finished
bot/check-test.sh script found in '/project/60006/SHARED/jobs/2024.02/pr_466/event_201af980-c1ee-11ee-826f-092bb38801c8/run_000/linux_x86_64_amd_zen2/eessi.io-2023.06-software', so running it!
check test step finished
```

That's clearly my Friday afternoon brain. Of course, if I want to use the EESSI environment, I should execute this stuff in the EESSI container. Point of attention here: I'll need to start the container in such a way that it picks up the installations it just created in the build step. I.e. with the correct workdir and everything.

In the meantime: it should have reported failure for the test step, but I was grepping for too strict a pattern `(\[\s+FAILED\s+\])`. In the test script, we just echo `FAILED` if a step there fails. In this case, the `module load ReFrame/4.3.3` failed. The test step should correctly report back that it failed (even if it was not a test from the test suite, but the whole workflow that failed). I've changed the pattern to `grep` for simply to `FAILED`.

**Comment by casparvl** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2

**Comment by casparvl** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2

**Comment by casparvl** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2

**Comment by boegel** [comment]
@casparvl How does this related to #467 exactly?

**Comment by casparvl** [comment]
Closing in favour of https://github.com/EESSI/software-layer/pull/467

**Pull request closed without merging**
