### PR TITLE
Show Lmod warning when ESPResSo v4.2.1 is loaded

### PR DESCRIPTION
**Pull request by Neves-P**
This PR adds a `Lmod` warning that should be displayed when ESPResSo v4.2.2 is released and v4.2.1 is deprecated and removed from package managers.

We will not remove v4.2.1 from EESSI, however, we notify users that this version should **not** be used in production in most cases (e.g., reproducing old results) as v4.2.2 fixes the problem described in https://github.com/espressomd/espresso/issues/4856.

### CODE REVIEW

**Comment by Neves-P** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic

**Comment by Neves-P** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic

**Comment by Neves-P** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic

**Comment by Neves-P** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic

**Comment by Neves-P** [comment]
After doing:

```
cd /project/def-users/SHARED/jobs/2024.05/pr_560/11289
./bot/inspect.sh -r previous_tmp/test_step/eessi.io-2023.06-software-1716467140.tgz
```

And then:
```
pedro@login1 /project/def-users/SHARED/jobs/2024.05/pr_560/11289 $ ml ESPResSo/4.2.1-foss-2023a
Lmod Warning:
ESPReSso v4.2.1 has known issues and has been deprecated. Prefer versions >= 4.2.2 which include important bugfixes.
For details see https://github.com/espressomd/espresso/releases/tag/4.2.2
Use version 4.2.1 at your own risk!
n
While processing the following module(s):
    Module fullname            Module Filename
    ---------------            ---------------
    ESPResSo/4.2.1-foss-2023a  /cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/generic/modules/all/ESPResSo/4.2.1-foss-2023a.lua
```

There is a typo that adds a single line with "n", fixing that now.

**Comment by Neves-P** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512

**Review by ocaisa — APPROVED** [review]
Seems to work as advertised
```
alanc@~/EESSI/software-layer(override_lmod_gpu_check)$ module purge
alanc@~/EESSI/software-layer(override_lmod_gpu_check)$ module load ESPResSo
Lmod Warning: 
ESPResSo v4.2.1 has known issues and has been deprecated. Prefer versions >= 4.2.2 which include important bugfixes.
For details see https://github.com/espressomd/espresso/releases/tag/4.2.2
Use version 4.2.1 at your own risk!

While processing the following module(s):
    Module fullname            Module Filename
    ---------------            ---------------
    ESPResSo/4.2.1-foss-2023a  /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/generic/modules/all/ESPResSo/4.2.1-foss-2023a.lua

alanc@~/EESSI/software-layer(override_lmod_gpu_check)$ module list

Currently Loaded Modules:
  1) GCCcore/12.3.0                    17) gompi/2023a                                33) lz4/1.9.4-GCCcore-12.3.0           49) LLVM/16.0.6-GCCcore-12.3.0
  2) GCC/12.3.0                        18) FFTW.MPI/3.3.10-gompi-2023a                34) zstd/1.5.5-GCCcore-12.3.0          50) Mesa/23.1.4-GCCcore-12.3.0
  3) numactl/2.0.16-GCCcore-12.3.0     19) ScaLAPACK/2.2.0-gompi-2023a-fb             35) ICU/73.2-GCCcore-12.3.0            51) GSL/2.7-GCC-12.3.0
  4) libxml2/2.11.4-GCCcore-12.3.0     20) foss/2023a                                 36) Boost.MPI/1.82.0-gompi-2023a       52) OpenPGM/5.2.122-GCCcore-12.3.0
  5) libpciaccess/0.17-GCCcore-12.3.0  21) Tcl/8.6.13-GCCcore-12.3.0                  37) Szip/2.1.1-GCCcore-12.3.0          53) libsodium/1.0.18-GCCcore-12.3.0
  6) hwloc/2.9.1-GCCcore-12.3.0        22) SQLite/3.42.0-GCCcore-12.3.0               38) HDF5/1.14.0-gompi-2023a            54) ZeroMQ/4.3.4-GCCcore-12.3.0
  7) OpenSSL/1.1                       23) libffi/3.4.4-GCCcore-12.3.0                39) expat/2.5.0-GCCcore-12.3.0         55) libxslt/1.1.38-GCCcore-12.3.0
  8) libevent/2.1.12-GCCcore-12.3.0    24) Python/3.11.3-GCCcore-12.3.0               40) libpng/1.6.39-GCCcore-12.3.0       56) lxml/4.9.2-GCCcore-12.3.0
  9) UCX/1.14.1-GCCcore-12.3.0         25) gfbf/2023a                                 41) Brotli/1.0.9-GCCcore-12.3.0        57) hatchling/1.18.0-GCCcore-12.3.0
 10) libfabric/1.18.0-GCCcore-12.3.0   26) cffi/1.15.1-GCCcore-12.3.0                 42) freetype/2.13.0-GCCcore-12.3.0     58) BeautifulSoup/4.12.2-GCCcore-12.3.0
 11) PMIx/4.2.4-GCCcore-12.3.0         27) cryptography/41.0.1-GCCcore-12.3.0         43) fontconfig/2.14.2-GCCcore-12.3.0   59) IPython/8.14.0-GCCcore-12.3.0
 12) UCC/1.2.0-GCCcore-12.3.0          28) virtualenv/20.23.1-GCCcore-12.3.0          44) xorg-macros/1.20.0-GCCcore-12.3.0  60) typing-extensions/4.9.0-GCCcore-12.3.0
 13) OpenMPI/4.1.5-GCC-12.3.0          29) Python-bundle-PyPI/2023.06-GCCcore-12.3.0  45) X11/20230603-GCCcore-12.3.0        61) Pint/0.23-GCCcore-12.3.0
 14) OpenBLAS/0.3.23-GCC-12.3.0        30) pybind11/2.11.1-GCCcore-12.3.0             46) libdrm/2.4.115-GCCcore-12.3.0      62) ESPResSo/4.2.1-foss-2023a
 15) FlexiBLAS/3.3.1-GCC-12.3.0        31) SciPy-bundle/2023.07-gfbf-2023a            47) libglvnd/1.6.0-GCCcore-12.3.0
 16) FFTW/3.3.10-GCC-12.3.0            32) gzip/1.12-GCCcore-12.3.0                   48) libunwind/1.6.2-GCCcore-12.3.0
```

**Comment by ocaisa** [comment]
All staging PRs merged

**Pull request merged**
