### PR TITLE
{2023.06}[2023a] X11 20230603

### PR DESCRIPTION
**Pull request by Neves-P**
Needed for #406 and #404 
```
 7 out of 25 required modules missing:

* Bison/3.8.2-GCCcore-12.3.0 (Bison-3.8.2-GCCcore-12.3.0.eb)
* libiconv/1.17-GCCcore-12.3.0 (libiconv-1.17-GCCcore-12.3.0.eb)
* Brotli/1.0.9-GCCcore-12.3.0 (Brotli-1.0.9-GCCcore-12.3.0.eb)
* Doxygen/1.9.7-GCCcore-12.3.0 (Doxygen-1.9.7-GCCcore-12.3.0.eb)
* freetype/2.13.0-GCCcore-12.3.0 (freetype-2.13.0-GCCcore-12.3.0.eb)
* fontconfig/2.14.2-GCCcore-12.3.0 (fontconfig-2.14.2-GCCcore-12.3.0.eb)
* X11/20230603-GCCcore-12.3.0 (X11-20230603-GCCcore-12.3.0.eb)
```

### CODE REVIEW

**Comment by Neves-P** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3

**Comment by boegel** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1

**Comment by Neves-P** [comment]
All the jobs succeeded 🥳 
Seems ready to deploy?

**Review by bedroge — APPROVED** [review]

**Comment by boegel** [comment]
All staging PRs merged

**Pull request merged**
