### PR TITLE
{2023.06}[foss/2023a] ESPResSo 4.2.2 w/ CUDA 12.1.1

### PR DESCRIPTION
**Pull request by Neves-P**

### CODE REVIEW

**Comment by Neves-P** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2 accel:nvidia/cc80

**Comment by boegel** [comment]
I checked the tarball, looks good to me:

* configure output shows that ESPResSo is picking up the correct CUDA:
```
-- Found CUDA: /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/accel/nvidia/cc80/software/CUDA/12.1.1 (found suitable version "12.1", minimum required is "10.0")
```

RPATH section in `ESPResSo/4.2.2-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages/espressomd/cuda_init.so` also looks good to me.

We should try and make the CI happy here though... @bedroge?

**Comment by Neves-P** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3 accel:nvidia/cc80

**Comment by ocaisa** [comment]
We'll have to hardcode a fix for CI now until `archdetect` has support for GPU (and an override given there will be no GPU in CI)

**Comment by boegel** [comment]
I tested this build on our AMD Milan A100 GPU cluster, results (interactive Slurm job with 1x A100, 12 CPU cores):

P3M benchmark (see [here](https://github.com/espressomd/espresso/tree/4.2.2/maintainer/benchmarks)): `pypresso benchmarks/p3m.py`

* `ESPResSo/4.2.2-foss-2023a` module:
  * `--no-gpu` option: ~2.5ms
  * `--gpu` option: error (expected): `Missing features CUDA`
* `ESPResSo/4.2.2-foss-2023a-CUDA-12.1.1` module:
  * `--no-gpu` option: ~2.6ms
  * `--gpu` option: ~0.4ms

😎 :shipit:

**Review by boegel — APPROVED** [review]
lgtm

**Pull request merged**
