### PR TITLE
{2023.06}[foss/2023b] python-casacore 3.5.2 + libspatialindex 1.9.3

### PR DESCRIPTION
**Pull request by t1mk1k**

### CODE REVIEW

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1

**Comment by bedroge** [comment]
It's failing because of:
```
  g++ -shared -L/cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/neoverse_v1/software/FFTW/3.3.10-GCC-13.2.0/lib64 -L/cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/neoverse_v1/software/FFTW/3.3.10-GCC-13.2.0/lib -L/cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/neoverse_v1/software/ScaLAPACK/2.2.0-gompi-2023b-fb/lib64 -L/cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/neoverse_v1/software/ScaLAPACK/2.2.0-gompi-2023b-fb/lib -L/cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/neoverse_v1/software/FlexiBLAS/3.3.1-GCC-13.2.0/lib64 -L/cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/neoverse_v1/software/FlexiBLAS/3.3.1-GCC-13.2.0/lib -L/cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/neoverse_v1/software/GCCcore/13.2.0/lib64 -L/cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/neoverse_v1/software/GCCcore/13.2.0/lib -O2 -ftree-vectorize -mcpu=native -fno-math-errno -I/cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/neoverse_v1/software/FFTW/3.3.10-GCC-13.2.0/include -I/cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/neoverse_v1/software/FlexiBLAS/3.3.1-GCC-13.2.0/include -I/cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/neoverse_v1/software/FlexiBLAS/3.3.1-GCC-13.2.0/include/flexiblas build/temp.linux-aarch64-cpython-311/src/fit.o build/temp.linux-aarch64-cpython-311/src/fitting.o -L/cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/neoverse_v1/software/Python/3.11.5-GCCcore-13.2.0/lib -lcasa_scimath -lcasa_scimath_f -lboost_python-py311-mt -lcasa_python3 -o build/lib.linux-aarch64-cpython-311/casacore/fitting/_fitting.cpython-311-aarch64-linux-gnu.so
  /cvmfs/software.eessi.io/versions/2023.06/compat/linux/aarch64/usr/bin/ld: cannot find -lboost_python-py311-mt: No such file or directory
  collect2: error: ld returned 1 exit status
  error: command '/tmp/eb-zqmf_waz/eb-i3hfwmjh/tmp3hqdnuyh/rpath_wrappers/gxx_wrapper/g++' failed with exit code 1
  error: subprocess-exited-with-error
  
   python setup.py bdist_wheel did not run successfully.
   exit code: 1
```

In the `Boost.Python` installation dir I only see the following ones:
```
$ ls /cvmfs/software.eessi.io/versions/2023.06/software/linux/aarch64/neoverse_v1/software/Boost.Python/1.83.0-GCC-13.2.0/lib
cmake                             libboost_python311-mt-a64.a
libboost_python311.a              libboost_python311-mt-a64.so
libboost_python311-a64.a          libboost_python311-mt-a64.so.1.83.0
libboost_python311-a64.so         libboost_python311.so
libboost_python311-a64.so.1.83.0  libboost_python311.so.1.83.0
```

**Comment by bedroge** [comment]
Actually, it seems like it cannot find Boost and Casacore:
```
  Could not find a Python boost library! Please use your package manager to install boost.

  Or install it manually:

  http://boostorg.github.io/python/doc/html/index.html

    warnings.warn(no_boost_error)
  /tmp/bot/easybuild/build/pythoncasacore/3.5.2/foss-2023b/pythoncasacore/python-casacore-3.5.2/setup.py:154: UserWarning: Could not find Casacore!

  Casacore is a critical requirement. Please install Casacore using a package manager or install it manually.
  You can find installation instructions on:

   https://github.com/casacore/casacore

  If you have Casacore installed in a non default location, you need to specify the location:

  $ python setup.py build_ext -I/opt/casacore/include:/other/include/path -L/opt/casacore/lib

  Don't give up!
```

**Comment by bedroge** [comment]
It looks like it's trying to use `$LD_LIBRARY_PATH` to find the location of the required libraries:
https://github.com/casacore/python-casacore/blob/master/setup.py#L54
But in EESSI we don't use/set `$LD_LIBRARY_PATH`, so we'll have to provide the locations in some other way.

**Comment by ocaisa** [comment]
A quick fix would be to (temporarily) set `LD_LIBRARY_PATH=$LIBRARY_PATH`

**Comment by t1mk1k** [comment]
> A quick fix would be to (temporarily) set `LD_LIBRARY_PATH=$LIBRARY_PATH`

Should I change that in the easyconfig? Or is this something that can be set in the easystack file (if so, I'm not sure which EB argument to use)?

**Comment by ocaisa** [comment]
I would do it in the easyconfig, you could do that in a forgiving way:
```
if [[ -z "$LD_LIBRARY_PATH" ]]; then export LD_LIBRARY_PATH="$LIBRARY_PATH"; fi 
```

**Comment by bedroge** [comment]
> I would do it in the easyconfig, you could do that in a forgiving way:
> 
> ```
> if [[ -z "$LD_LIBRARY_PATH" ]]; then export LD_LIBRARY_PATH="$LIBRARY_PATH"; fi 
> ```
> 
> and I think you need it placed like https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/t/torchvf/torchvf-0.1.3-foss-2022a-CUDA-11.7.0.eb#L34

I just tried this interactively on the build cluster by adding:
```
        'preinstallopts': 'if [[ -z "$LD_LIBRARY_PATH" ]]; then export LD_LIBRARY_PATH="$LIBRARY_PATH"; fi && '
```
and then the build completed without any issues. I agree it would be best to add this to the easyconfig, as other people may run into this as well.

**Comment by t1mk1k** [comment]
> > I would do it in the easyconfig, you could do that in a forgiving way:
> > ```
> > if [[ -z "$LD_LIBRARY_PATH" ]]; then export LD_LIBRARY_PATH="$LIBRARY_PATH"; fi 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and I think you need it placed like https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/t/torchvf/torchvf-0.1.3-foss-2022a-CUDA-11.7.0.eb#L34
> 
> I just tried this interactively on the build cluster by adding:
> 
> ```
>         'preinstallopts': 'if [[ -z "$LD_LIBRARY_PATH" ]]; then export LD_LIBRARY_PATH="$LIBRARY_PATH"; fi && '
> ```
> 
> and then the build completed without any issues. I agree it would be best to add this to the easyconfig, as other people may run into this as well.

Thanks for testing! I've created a PR in easybuild-easyconfigs: https://github.com/easybuilders/easybuild-easyconfigs/pull/20089

**Comment by ocaisa** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512

**Review by bedroge — APPROVED** [review]

**Comment by bedroge** [comment]
> Thanks for testing! I've created a PR in easybuild-easyconfigs: [easybuilders/easybuild-easyconfigs#20089](https://github.com/easybuilders/easybuild-easyconfigs/pull/20089)

Thanks for the quick fix!

**Pull request merged**
