### PR TITLE
{2023.06}[foss/2023a] GROMACS v2023.4

### PR DESCRIPTION
**Pull request by bedroge**

### CODE REVIEW

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3

**Comment by bedroge** [comment]
While I was debugging #401 interactively, I also tried installing 2023.4, and then that version did work fine. But now the build with the bot does show the same test failure again :disappointed:
```
-------------------------------------------------------
Program:     gmxapi-mpi-test, version 2023.4-EasyBuild_4.9.0
Source file: src/gromacs/utility/futil.cpp (line 454)
MPI rank:    1 (out of 2)

File input/output error:
/tmp/bot/easybuild/build/GROMACS/2023.4/foss-2023a/easybuild_obj/api/gmxapi/cpp/tests/Testing/Temporary/GmxApiTest_RunnerChainedMD.trr

For more information and tips for troubleshooting, please check the GROMACS
website at https://manual.gromacs.org/current/user-guide/run-time-errors.html
-------------------------------------------------------

-------------------------------------------------------
Program:     gmxapi-mpi-test, version 2023.4-EasyBuild_4.9.0
Source file: src/gromacs/utility/futil.cpp (line 454)
MPI rank:    0 (out of 2)

File input/output error:
/tmp/bot/easybuild/build/GROMACS/2023.4/foss-2023a/easybuild_obj/api/gmxapi/cpp/tests/Testing/Temporary/GmxApiTest_RunnerChainedMD.trr

For more information and tips for troubleshooting, please check the GROMACS
website at https://manual.gromacs.org/current/user-guide/run-time-errors.html
-------------------------------------------------------
```

**Comment by boegel** [comment]
@bedroge Some time to blame `fuse-overlayfs`? Or doesn't that come into play here yet (since this is pre-install test suite)?

**Comment by bedroge** [comment]
> @bedroge Some time to blame `fuse-overlayfs`? Or doesn't that come into play here yet (since this is pre-install test suite)?

It's using `/tmp` inside the container, which shouldn't use `fuse-overlayfs`. I'm not entirely sure which host directory is bind mounted as `/tmp`, but if that's a shared filesystem (not entirely sure, but don't think that's the case?), it could explain things.

**Comment by boegel** [comment]
> > @bedroge Some time to blame `fuse-overlayfs`? Or doesn't that come into play here yet (since this is pre-install test suite)?
> 
> It's using `/tmp` inside the container, which shouldn't use `fuse-overlayfs`. I'm not entirely sure which host directory is bind mounted as `/tmp`, but if that's a shared filesystem (not entirely sure, but don't think that's the case?), it could explain things.

A unique subdirectory of `/tmp` is bind-mounted as `/tmp` in the build container I think, definitely not a shared filesystem (we would've seen problems already in that case).

**Comment by bedroge** [comment]
I've tried building this version a few more times now, and it's failing all the time on that same test. For some reason, it worked the very first time, though :confused:

**Comment by TopRichard** [comment]
@bedroge  Gromacs v2023.4 works for NESSI: https://github.com/NorESSI/software-layer/pull/273 but with deb10 container on certain architectures.

**Comment by bedroge** [comment]
> @bedroge @boegel Gromacs v2023.4 works for NESSI: [NorESSI#273](https://github.com/NorESSI/software-layer/pull/273) but with deb10 container on certain architectures.

Oh, that's really interesting... Now we did have weird behaviour for both 2023.3 and 2023.4, where it occasionally does work, but for e.g. haswell it's failing (almost) all the time, I think. Doesn't look like NESSI builds for haswell (?), so maybe I can try doing that interactively with our old debian10 container.

**Comment by bedroge** [comment]
> > @bedroge @boegel Gromacs v2023.4 works for NESSI: [NorESSI#273](https://github.com/NorESSI/software-layer/pull/273) but with deb10 container on certain architectures.
> 
> Oh, that's really interesting... Now we did have weird behaviour for both 2023.3 and 2023.4, where it occasionally does work, but for e.g. haswell it's failing (almost) all the time, I think. Doesn't look like NESSI builds for haswell (?), so maybe I can try doing that interactively with our old debian10 container.

@TopRichard I tried it on a haswell node with our old Debian 10 build container (https://github.com/EESSI/filesystem-layer/pkgs/container/build-node/40951724?tag=debian10), but it has been stuck in the test step for several hours now, so I think it hangs (and we saw the same thing before). Is there any other significant difference in your Debian 10 container compared to the Debian 11 container?

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3

**Comment by bedroge** [comment]
This actually completed:
```
== COMPLETED: Installation ended successfully (took 36 mins 48 secs)
== Results of the build can be found in the log file(s) /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/GROMACS/2023.4-foss-2023a/easybuild/easybuild-GROMACS-2023.4-20240327.162926.log.bz2
== Build succeeded for 1 out of 1
```

But then failed in the missing software check (I guess because the easyconfig hasn't been merged yet?):
```
ERROR: One or more files not found: GROMACS-2023.4-foss-2023a.eb (search paths: /tmp/tmp.LSEuf7NgOB/easyconfigs/easybuild/easyconfigs)
```

So, let's try building for the other architectures as well.

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512

**Comment by bedroge** [comment]
Quick summary of the status of the builds:
```
# Job 8721 on neoverse v1:
The following tests FAILED:
         15 - GmxlibTests (Subprocess aborted)
         45 - SimdUnitTests (Failed)
         80 - MdrunFEPTests (Failed)

# Job 8723 on zen2:
The following tests FAILED:
          2 - GmxapiMpiTests (Failed)

# Job 8724 on haswell:
Stuck, killed it manually
```

All the other ones actually completed successfully, but failed in the check for missing installations.

Regarding the haswell build, I saw the following processes running on the node:
```
bot        31437   31427  0 09:26 ?        00:00:00 orted --hnp --set-sid --report-uri 14 --singleton-died-pipe 15 -mca state_novm_select 1 -mca ess hnp -mca pmix ^s1,s2,cray,isolated
bot        31438   31436  0 09:26 ?        00:00:00 orted --hnp --set-sid --report-uri 14 --singleton-died-pipe 15 -mca state_novm_select 1 -mca ess hnp -mca pmix ^s1,s2,cray,isolated
```
I'm guessing this may be a similar issue as what we are seeing in #508 and #456.

**Comment by marconetto** [comment]
Hi folks, I would like to use gromacs from the eessi prod repo. I understand this is the PR to generate gromacs in prod repo right?

**Comment by bedroge** [comment]
> Hi folks, I would like to use gromacs from the eessi prod repo. I understand this is the PR to generate gromacs in prod repo right?

Hi @marconetto, yes, that's correct. Unfortunately, we're seeing weird test failures on a few CPU types, and these are quite hard to figure out. We'd really like to make GROMACS available, but we also really want to be sure that the builds are fine before we actually add them to the repository. So we'll keep working on them (we also have open PRs for version 2023.3 in #401 and 2024.1 in #499, but all with similar issues), and hopefully we will be able to resolve the issues soon.

**Comment by marconetto** [comment]
thanks @bedroge for the clarification!

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell

**Comment by bedroge** [comment]
The haswell build is not getting stuck anymore (because of the Lmod hook that we added to the bot environment), but it does still fail due to one failing test:
```
          2 - GmxapiMpiTests (Failed)
```

**Comment by boegel** [comment]
superseded by #499

**Comment by bedroge** [comment]
> Hi folks, I would like to use gromacs from the eessi prod repo. I understand this is the PR to generate gromacs in prod repo right?

HI @marconetto, GROMACS 2024.1 is now available in the production repo. Does that version suit your needs, or did you have a specific need for version 2023.4?

**Comment by marconetto** [comment]
Hi @bedroge , this is great news! Thanks for you and your team by putting this together. This version is fine, thanks a lot! I will test it next week and let you know if something is not working as expected.

**Pull request closed without merging**
