### PR TITLE
{2023.06}[foss/2022a] CDO v2.0.6

### PR DESCRIPTION
**Pull request by TopRichard**

### CODE REVIEW

**Comment by TopRichard** [comment]
bot: build repo:eessi-hpc.org-2023.06-software arch:x86_64/generic

**Comment by TopRichard** [comment]
bot: build repo:eessi-hpc.org-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi-hpc.org-2023.06-software arch:x86_64/intel/skylake_avx512
bot: build repo:eessi-hpc.org-2023.06-software arch:x86_64/amd/zen3
bot: build repo:eessi-hpc.org-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi-hpc.org-2023.06-software arch:aarch64/generic
bot: build repo:eessi-hpc.org-2023.06-software arch:aarch64/neoverse_v1
bot: build repo:eessi-hpc.org-2023.06-software arch:aarch64/neoverse_n1

**Comment by bedroge** [comment]
I had a look at the build log, and it's failing due to some weird Fortran issue:
```
cfortran.h:193:2: warning: #warning "Please specify the fortran compiler using -D flags. Try to guess the compiler used" [-Wcpp]
  193 | #warning "Please specify the fortran compiler using -D flags. Try to guess the compiler used"
      |  ^~~~~~~
cfortran.h:265:2: error: #error "cfortran.h:  Can't find your environment among:    - GNU gcc (gfortran) on Linux.                                           - MIPS cc and f7
7 2.0. (e.g. Silicon Graphics, DECstations, ...)         - IBM AIX XL C and FORTRAN Compiler/6000 Version 01.01.0000.0000         - VAX   VMS CC 3.1 and FORTRAN 5.4.        
                              - Alpha VMS DEC C 1.3 and DEC FORTRAN 6.0.                               - Alpha OSF DEC C and DEC Fortran for OSF/1 AXP Version 1.2           
   - Apollo DomainOS 10.2 (sys5.3) with f77 10.7 and cc 6.7.                - CRAY                                                                   - NEC SX-4 SUPER-UX     
                                                 - CONVEX                                                                 - Sun                                              
                      - PowerStation Fortran with Visual C++                                   - HP9000s300/s700/s800 Latest test with: HP-UX A.08.07 A 9000/730        - Lyn
xOS: cc or gcc with f2c.                                            - VAXUltrix: vcc,cc or gcc with f2c. gcc or cc with f77.                 -            f77 with vcc works;
 but missing link magic for f77 I/O.     -            NO fort. None of gcc, cc or vcc generate required names.    - f2c/g77:   Use #define    f2cFortran, or cc -Df2cFortran 
              - gfortran:  Use #define    gFortran,   or cc -DgFortran                              (also necessary for g77 with -fno-f2c option)               - NAG f90: Us
e #define NAGf90Fortran, or cc -DNAGf90Fortran              - Absoft UNIX F77: Use #define AbsoftUNIXFortran or cc -DAbsoftUNIXFortran     - Absoft Pro Fortran: Use #define 
AbsoftProFortran     - Portland Group Fortran: Use #define pgiFortran     - Intel Fortran: Use #define INTEL_COMPILER"
  265 | #error "cfortran.h:  Can't find your environment among:\
      |  ^~~~~
```

Not sure why this only pops up on Arm, but for some reason it can't figure out which Fortran compiler has to be used, if I understand things correctly. Based on a quick test, setting `CXXFLAGS = "$CXXFLAGS -DgFortran"` seems to solve the issue though.

**Comment by laraPPr** [comment]
Can this pr be closed since a new pr was opened for CDO (https://github.com/EESSI/software-layer/pull/427)?

**Pull request closed without merging**
