### PR TITLE
{2023.06}[foss/2023a] Add libxc 6.2.2 and ELPA 2023.05.001 

### PR DESCRIPTION
**Pull request by ocaisa**

### CODE REVIEW

**Comment by ocaisa** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1

**Comment by ocaisa** [comment]
This is to provide the dependencies of #504 since they are slow to build and seem to work everywhere

**Comment by bedroge** [comment]
> New job on instance `eessi-bot-mc-aws` for architecture `x86_64-intel-haswell` for repository `eessi.io-2023.06-software` in job dir `/project/def-users/SHARED/jobs/2024.03/pr_508/8357`
> 
> date	job status	comment
> Mar 20 22:29:30 UTC 2024	submitted	job id `8357` awaits release by job manager
> Mar 20 22:30:00 UTC 2024	released	job awaits launch by Slurm scheduler
> Mar 20 22:36:31 UTC 2024	running	job `8357` is running

@ocaisa The haswell build seems to hang, have you observed this before in #504?

**Comment by ocaisa** [comment]
No, first time I've seen it, and I've done a lot of builds lately

**Comment by bedroge** [comment]
> No, first time I've seen it, and I've done a lot of builds lately

I'll cancel the job (and check if there's anything useful in the output file), and then restart the build.

**Comment by bedroge** [comment]
These processes were running on the node:
```
bot       130963    3582  0 mrt20 ?        00:00:00 /bin/bash ./configure --prefix=/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/ELPA/2023.05.001-foss-2023a --enable-openmp --enable-shared --enable-generic --enable-single-precision --enable-avx --enable-avx2 --disable-avx512 --disable-vsx --enable-sse --enable-sse-assembly --with-mpi=yes LIBS=-lscalapack -lflexiblas -lgfortran
bot       136252  130963  0 mrt20 ?        00:00:00 /bin/bash ./configure --prefix=/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/ELPA/2023.05.001-foss-2023a --enable-openmp --enable-shared --enable-generic --enable-single-precision --enable-avx --enable-avx2 --disable-avx512 --disable-vsx --enable-sse --enable-sse-assembly --with-mpi=yes LIBS=-lscalapack -lflexiblas -lgfortran
bot       136253  136252  0 mrt20 ?        00:00:00 ./conftest
bot       136255  136253  0 mrt20 ?        00:00:00 orted --hnp --set-sid --report-uri 11 --singleton-died-pipe 12 -mca state_novm_select 1 -mca ess hnp -mca pmix ^s1,s2,cray,isolated
```

And this is the last bit of output in ELPA's `config.log`:
```
configure:14228: **************************************************************************************************************************
configure:14230: * Please notice if the following step hangs or aborts abnormaly then you cannot run a short MPI-program during configure *
configure:14232: * In this case please re-run configure with '--without-threading-support-check-during-build' _AND_ follow the hints in   *
configure:14234: * the INSTALL and USER_GUIDE documents!                                                                                  *
configure:14236: * In case you get some other warnings about threading support follow on of the steps detailed there                      *
configure:14238: **************************************************************************************************************************
configure:14240: checking what threading level is supported by the MPI library
configure:14269: mpifort -o conftest  -O2 -ftree-vectorize -march=native -fno-math-errno -fopenmp -lm -L/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/Perl/5.36.1-GCCcore-12.3.0/lib64 -L/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/Perl/5.36.1-GCCcore-12.3.0/lib -L/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/Python/3.11.3-GCCcore-12.3.0/lib64 -L/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/Python/3.11.3-GCCcore-12.3.0/lib -L/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/FFTW.MPI/3.3.10-gompi-2023a/lib64 -L/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/FFTW.MPI/3.3.10-gompi-2023a/lib -L/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/ScaLAPACK/2.2.0-gompi-2023a-fb/lib64 -L/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/ScaLAPACK/2.2.0-gompi-2023a-fb/lib -L/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/FlexiBLAS/3.3.1-GCC-12.3.0/lib64 -L/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/FlexiBLAS/3.3.1-GCC-12.3.0/lib -L/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/GCCcore/12.3.0/lib64 -L/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/GCCcore/12.3.0/lib  conftest.F90 -lscalapack -lscalapack -lflexiblas -lgfortran >&5
configure:14269: $? = 0
configure:14269: ./conftest
x86-64-intel-haswell-node1.int.aws-rocky88-202310.eessi.io:pid132837: PSM3 can't open nic unit: 0 (err=23)
x86-64-intel-haswell-node1.int.aws-rocky88-202310.eessi.io:pid132837: PSM3 can't open nic unit: 0 (err=23)
```

**Comment by ocaisa** [comment]
Ah, perhaps it is related to OpenMPI (we still haven't deployed the bugfix)

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell

**Comment by bedroge** [comment]
It's stuck again at the same command. Trying it one more time...

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell

**Comment by bedroge** [comment]
It happened again (on a different node this time). It looks like it the same issue as https://github.com/EESSI/software-layer/issues/456, but I don't understand why it's suddenly popping up now.

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell

**Comment by bedroge** [comment]
Tried again with the OpenMPI fix deployed, but it doesn't solve the issue unfortunately, still seeing:
```
configure:14187: result: yes
configure:14228: **************************************************************************************************************************
configure:14230: * Please notice if the following step hangs or aborts abnormaly then you cannot run a short MPI-program during configure *
configure:14232: * In this case please re-run configure with '--without-threading-support-check-during-build' _AND_ follow the hints in   *
configure:14234: * the INSTALL and USER_GUIDE documents!                                                                                  *
configure:14236: * In case you get some other warnings about threading support follow on of the steps detailed there                      *
configure:14238: **************************************************************************************************************************
configure:14240: checking what threading level is supported by the MPI library
configure:14269: mpifort -o conftest  -O2 -ftree-vectorize -march=native -fno-math-errno -fopenmp -lm -L/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/Perl/5.36.1-GCCcore-12.3.0/lib64 -L/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/Perl/5.36.1-GCCcore-12.3.0/lib -L/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/Python/3.11.3-GCCcore-12.3.0/lib64 -L/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/Python/3.11.3-GCCcore-12.3.0/lib -L/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/FFTW.MPI/3.3.10-gompi-2023a/lib64 -L/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/FFTW.MPI/3.3.10-gompi-2023a/lib -L/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/ScaLAPACK/2.2.0-gompi-2023a-fb/lib64 -L/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/ScaLAPACK/2.2.0-gompi-2023a-fb/lib -L/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/FlexiBLAS/3.3.1-GCC-12.3.0/lib64 -L/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/FlexiBLAS/3.3.1-GCC-12.3.0/lib -L/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/GCCcore/12.3.0/lib64 -L/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/GCCcore/12.3.0/lib  conftest.F90 -lscalapack -lscalapack -lflexiblas -lgfortran >&5
configure:14269: $? = 0
configure:14269: ./conftest
x86-64-intel-haswell-node3.int.aws-rocky88-202310.eessi.io:pid132857: PSM3 can't open nic unit: 0 (err=23)
x86-64-intel-haswell-node3.int.aws-rocky88-202310.eessi.io:pid132857: PSM3 can't open nic unit: 0 (err=23)
```

**Comment by ocaisa** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell

**Review by bedroge — APPROVED** [review]

**Pull request merged**
