### PR TITLE
{2023.06,zen4} foss/2023a

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen4

**Comment by boegel** [comment]
@trz42 Build of GCC failed with:
```
g++: fatal error: Killed signal terminated program cc1plus
```

That tells me there's not enough memory in the Slurm jobs, so we need to tweak how to bot submits jobs on the Slurm cluster in Azure...

**Comment by boegel** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen4

**Comment by boegel** [comment]
bot: show_config

**Comment by boegel** [comment]
build of `foss/2023a` for `zen4` complete, ready to deploy!

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen4

**Comment by boegel** [comment]
rebuild is needed because tarball produced by job `82` also includes changes in `init/*`, which is fallout from #371 being deployed but not merged yet

**Comment by boegel** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen4

**Comment by boegel** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen4

**Comment by ocaisa** [comment]
Ok, I think I found it. The change in #569 is not allowing us to do builds for Zen4:
```
ESC[33mSticking to x86_64/amd/zen3 for now, since optimized installations for AMD Genoa (Zen4) are a work in progress, see https://gitlab.com/eessi/support/-/issues/37 for more informationESC[0m
ESC[31mERROR: Values for EESSI_SOFTWARE_SUBDIR_OVERRIDE (x86_64/amd/zen4) and EESSI_SOFTWARE_SUBDIR (x86_64/amd/zen3) differ!ESC[0m

```

**Comment by boegel** [comment]
> Ok, I think I found it. The change in #569 is not allowing us to do builds for Zen4:
> 
> ```
> ESC[33mSticking to x86_64/amd/zen3 for now, since optimized installations for AMD Genoa (Zen4) are a work in progress, see https://gitlab.com/eessi/support/-/issues/37 for more informationESC[0m
> ESC[31mERROR: Values for EESSI_SOFTWARE_SUBDIR_OVERRIDE (x86_64/amd/zen4) and EESSI_SOFTWARE_SUBDIR (x86_64/amd/zen3) differ!ESC[0m
> ```

Fixed by #573, so time to try again...

**Comment by boegel** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen4

**Review by bedroge — APPROVED** [review]

**Pull request merged**
