### PR TITLE
{2023.06}[GCCcore/12.2.0] libs-tools

### PR DESCRIPTION
**Pull request by TopRichard**
missing packages:

```
Archive-Zip/1.68-GCCcore-12.2.0
jemalloc/5.3.0-GCCcore-12.2.0
Judy/1.0.5-GCCcore-12.2.0
libaio/0.3.113-GCCcore-12.2.0
tbb/2021.10.0-GCCcore-12.2.0
Z3/4.12.2-GCCcore-12.2.0
Zip/3.0-GCCcore-12.2.0
```

### CODE REVIEW

**Comment by TopRichard** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic

**Comment by TopRichard** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
all staging PRs merged

**Pull request merged**
