### PR TITLE
{2023.06}[2021b] OpenMPI v4.1.1

### PR DESCRIPTION
**Pull request by laraPPr**

### CODE REVIEW

**Comment by laraPPr** [comment]
bot: build arch:x86_64/generic repo:eessi-2023.06-software
bot: build arch:x86_64/intel/haswell repo:eessi-2023.06-software
bot: build arch:x86_64/intel/skylake_avx512 repo:eessi-2023.06-software
bot: build arch:x86_64/amd/zen2 repo:eessi-2023.06-software
bot: build arch:x86_64/amd/zen3 repo:eessi-2023.06-software
bot: build arch:aarch64/generic repo:eessi-2023.06-software
bot: build arch:aarch64/neoverse_n1 repo:eessi-2023.06-software
bot: build arch:aarch64/neoverse_v1 repo:eessi-2023.06-software

**Comment by laraPPr** [comment]
bot: build arch:x86_64/generic repo:eessi-2023.06-software

**Comment by laraPPr** [comment]
bot: build arch:x86_64/intel/haswell repo:eessi-2023.06-software
bot: build arch:x86_64/intel/skylake_avx512 repo:eessi-2023.06-software
bot: build arch:x86_64/amd/zen2 repo:eessi-2023.06-software
bot: build arch:x86_64/amd/zen3 repo:eessi-2023.06-software
bot: build arch:aarch64/generic repo:eessi-2023.06-software
bot: build arch:aarch64/neoverse_n1 repo:eessi-2023.06-software
bot: build arch:aarch64/neoverse_v1 repo:eessi-2023.06-software

**Comment by boegel** [comment]
All tarballs ingested.

**Review by boegel — APPROVED** [review]

**Pull request merged**
