### PR TITLE
{2023.06}[foss/2023b] GROMACS 2024.3

### PR DESCRIPTION
**Pull request by bedroge**

### CODE REVIEW

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen4
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512

**Comment by bedroge** [comment]
> New job on instance `eessi-bot-mc-aws` for architecture `x86_64-intel-haswell` for repository `eessi.io-2023.06-software` in job dir `/project/def-users/SHARED/jobs/2024.09/pr_709/18873`
> 
> date	job status	comment
> Sep 17 14:19:42 UTC 2024	submitted	job id `18873` awaits release by job manager
> Sep 17 14:20:38 UTC 2024	released	job awaits launch by Slurm scheduler
> Sep 17 14:21:57 UTC 2024	running	job `18873` is running
> Sep 17 15:03:56 UTC 2024	finished	
> 😢 FAILURE _(click triangle for details)_
> Sep 17 15:03:56 UTC 2024	test result	
> 😢 FAILURE _(click triangle for details)_

```
File input/output error:
/tmp/bot/easybuild/build/GROMACS/2024.3/foss-2023b/easybuild_obj/api/gmxapi/cpp/tests/Testing/Temporary/GmxApiTest_RunnerChainedMD.trr
```

Same error as we've seen before, and also the same as I just saw on the EB test cluster (https://github.com/easybuilders/easybuild-easyconfigs/pull/21430#issuecomment-2355814261). It doesn't happen consistently, so let's try again...

bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell

**Comment by boegel** [comment]
> > New job on instance `eessi-bot-mc-aws` for architecture `x86_64-intel-haswell` for repository `eessi.io-2023.06-software` in job dir `/project/def-users/SHARED/jobs/2024.09/pr_709/18873`
> > date	job status	comment
> > Sep 17 14:19:42 UTC 2024	submitted	job id `18873` awaits release by job manager
> > Sep 17 14:20:38 UTC 2024	released	job awaits launch by Slurm scheduler
> > Sep 17 14:21:57 UTC 2024	running	job `18873` is running
> > Sep 17 15:03:56 UTC 2024	finished
> > 😢 FAILURE _(click triangle for details)_
> > Sep 17 15:03:56 UTC 2024	test result
> > 😢 FAILURE _(click triangle for details)_
> 
> ```
> File input/output error:
> /tmp/bot/easybuild/build/GROMACS/2024.3/foss-2023b/easybuild_obj/api/gmxapi/cpp/tests/Testing/Temporary/GmxApiTest_RunnerChainedMD.trr
> ```
> 
> Same error as we've seen before, and also the same as I just saw on the EB test cluster ([easybuilders/easybuild-easyconfigs#21430 (comment)](https://github.com/easybuilders/easybuild-easyconfigs/pull/21430#issuecomment-2355814261)). It doesn't happen consistently, so let's try again...
> 
> bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell

see also https://gitlab.com/eessi/support/-/issues/47#note_1763083132, looks like there's still a problem that hasn't been resolved by https://gitlab.com/gromacs/gromacs/-/merge_requests/4066 then?

**Comment by bedroge** [comment]
> see also https://gitlab.com/eessi/support/-/issues/47#note_1763083132, looks like there's still a problem that hasn't been resolved by https://gitlab.com/gromacs/gromacs/-/merge_requests/4066 then?

Looks like it, yeah. Though it's strange that it only seems to happen on haswell (?)), and it's almost like every second attempt does work 🤯😅

**Comment by boegel** [comment]
> > see also https://gitlab.com/eessi/support/-/issues/47#note_1763083132, looks like there's still a problem that hasn't been resolved by https://gitlab.com/gromacs/gromacs/-/merge_requests/4066 then?
> 
> Looks like it, yeah. Though it's strange that it only seems to happen on haswell (?)), and it's almost like every second attempt does work 🤯😅

Could be more likely to happen on slower CPUs, perhaps? 2nd attempt is just sheer luck

**Pull request merged**
