### PR TITLE
{2023.06}[foss/2021b] R 4.2.0

### PR DESCRIPTION
**Pull request by laraPPr**
```
25 out of 107 required modules missing:

* nettle/3.7.3-GCCcore-11.2.0 (nettle-3.7.3-GCCcore-11.2.0.eb)
* jbigkit/2.1-GCCcore-11.2.0 (jbigkit-2.1-GCCcore-11.2.0.eb)
* NLopt/2.7.0-GCCcore-11.2.0 (NLopt-2.7.0-GCCcore-11.2.0.eb)
* LibTIFF/4.3.0-GCCcore-11.2.0 (LibTIFF-4.3.0-GCCcore-11.2.0.eb)
* Tk/8.6.11-GCCcore-11.2.0 (Tk-8.6.11-GCCcore-11.2.0.eb)
* Xvfb/1.20.13-GCCcore-11.2.0 (Xvfb-1.20.13-GCCcore-11.2.0.eb)
* libogg/1.3.5-GCCcore-11.2.0 (libogg-1.3.5-GCCcore-11.2.0.eb)
* FLAC/1.3.3-GCCcore-11.2.0 (FLAC-1.3.3-GCCcore-11.2.0.eb)
* libvorbis/1.3.7-GCCcore-11.2.0 (libvorbis-1.3.7-GCCcore-11.2.0.eb)
* libsndfile/1.0.31-GCCcore-11.2.0 (libsndfile-1.0.31-GCCcore-11.2.0.eb)
* UDUNITS/2.2.28-GCCcore-11.2.0 (UDUNITS-2.2.28-GCCcore-11.2.0.eb)
* GSL/2.7-GCC-11.2.0 (GSL-2.7-GCC-11.2.0.eb)
* GLPK/5.0-GCCcore-11.2.0 (GLPK-5.0-GCCcore-11.2.0.eb)
* Ghostscript/9.54.0-GCCcore-11.2.0 (Ghostscript-9.54.0-GCCcore-11.2.0.eb)
* nodejs/14.17.6-GCCcore-11.2.0 (nodejs-14.17.6-GCCcore-11.2.0.eb)
* LittleCMS/2.12-GCCcore-11.2.0 (LittleCMS-2.12-GCCcore-11.2.0.eb)
* libgit2/1.1.1-GCCcore-11.2.0 (libgit2-1.1.1-GCCcore-11.2.0.eb)
* GEOS/3.9.1-GCC-11.2.0 (GEOS-3.9.1-GCC-11.2.0.eb)
* PROJ/8.1.0-GCCcore-11.2.0 (PROJ-8.1.0-GCCcore-11.2.0.eb)
* libgeotiff/1.7.0-GCCcore-11.2.0 (libgeotiff-1.7.0-GCCcore-11.2.0.eb)
* ImageMagick/7.1.0-4-GCCcore-11.2.0 (ImageMagick-7.1.0-4-GCCcore-11.2.0.eb)
* libtirpc/1.3.2-GCCcore-11.2.0 (libtirpc-1.3.2-GCCcore-11.2.0.eb)
* HDF/4.2.15-GCCcore-11.2.0 (HDF-4.2.15-GCCcore-11.2.0.eb)
* GDAL/3.3.2-foss-2021b (GDAL-3.3.2-foss-2021b.eb)
* R/4.2.0-foss-2021b (R-4.2.0-foss-2021b.eb)
```

### CODE REVIEW

**Comment by laraPPr** [comment]
the following test failed and I don't really understand why pilot (`2023.06, aarch64/neoverse_n1, eessi-2023.06-eb-4.7.2-2022b.yml`)

This is probably not relevant for for this version of R so I am triggering the bot.

**Comment by laraPPr** [comment]
bot: build arch:x86_64/generic repo:eessi-2023.06-software

**Comment by laraPPr** [comment]
```
== 2023-09-18 15:13:38,989 build_log.py:171 ERROR EasyBuild crashed with an error (at easybuild/tools/build_log.py:111 in caller_info): cmd "cp -a xvfb-run /cvmfs/pilot.eessi-hpc.org/versions/2023.06/software/linux/x86_64/generic/software/Xvfb/1.20.13-GCCcore-11.2.0/bin/ && chmod u+x  /cvmfs/pilot.eessi-hpc.org/versions/2023.06/software/linux/x86_64/generic/software/Xvfb/1.20.13-GCCcore-11.2.0/bin/xvfb-run" exited with exit code 1 and output:

cp: preserving permissions for /cvmfs/pilot.eessi-hpc.org/versions/2023.06/software/linux/x86_64/generic/software/Xvfb/1.20.13-GCCcore-11.2.0/bin/xvfb-run: Permission denied

 (at easybuild/tools/run.py:681 in parse_cmd_output)
```

**Comment by laraPPr** [comment]
bot: build arch:x86_64/generic repo:eessi-2023.06-software

**Comment by laraPPr** [comment]
```
ERROR EasyBuild crashed with an error (at easybuild/tools/build_log.py:111 in caller_info): Failed to get data for PR #2248 from easybuilders/easybuild-easyblocks (HTTP Error 403: rate limit exceeded)

Please check PR #, account and repo. (at easybuild/tools/github.py:2401 in fetch_pr_data)

```

**Comment by laraPPr** [comment]
bot: build arch:x86_64/generic repo:eessi-2023.06-software

**Comment by laraPPr** [comment]
```
== 2023-09-19 14:45:25,408 build_log.py:171 ERROR EasyBuild crashed with an error (at easybuild/tools/build_log.py:111 in caller_info): Couldn't find file tiff-4.3.0.tar.gz anywhere, and downloading it didn't work either...
```

**Comment by laraPPr** [comment]
bot: build arch:x86_64/generic repo:eessi-2023.06-software

**Comment by laraPPr** [comment]
bot: build repo:eessi-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi-2023.06-software arch:x86_64/intel/skylake_avx512
bot: build repo:eessi-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi-2023.06-software arch:x86_64/amd/zen3
bot: build repo:eessi-2023.06-software arch:aarch64/generic
bot: build repo:eessi-2023.06-software arch:aarch64/neoverse_n1
bot: build repo:eessi-2023.06-software arch:aarch64/neoverse_v1

**Comment by boegel** [comment]
all staging PRs merged

**Review by boegel — APPROVED** [review]

**Pull request merged**
