### PR TITLE
{2023.06}[foss/2023a] OSU-Microbenchmarks v7.2 w/ CUDA 12.1.1 (rebuild)

### PR DESCRIPTION
**Pull request by casparvl**
requires:
- [x] #720 
- [x] #719 
- [x] #750

### CODE REVIEW

**Comment by casparvl** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2 accel:nvidia/cc80

**Comment by casparvl** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2 accel:nvidia/cc80

**Comment by casparvl** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2 accel:nvidia/cc80
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3 accel:nvidia/cc80

**Comment by casparvl** [comment]
For `zen2`:

```
[casparvl@login1 20007]$ readelf -d 2023.06/software/linux/x86_64/amd/zen2/accel/nvidia/cc80/software/OSU-Micro-Benchmarks/7.2-gompi-2023a-CUDA-12.1.1/libexec/osu-micro-benchmarks/mpi/pt2pt/osu_latency | grep RPATH | grep CUDA
 0x000000000000000f (RPATH)              Library rpath: [/cvmfs/software.eessi.io/host_injections/2023.06/software/linux/x86_64/amd/zen2/rpath_overrides/OpenMPI/system/lib:/cvmfs/software.eessi.io/host_injections/2023.06/software/linux/x86_64/amd/zen2/rpath_overrides/OpenMPI/system/lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/accel/nvidia/cc80/software/OSU-Micro-Benchmarks/7.2-gompi-2023a-CUDA-12.1.1/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/accel/nvidia/cc80/software/OSU-Micro-Benchmarks/7.2-gompi-2023a-CUDA-12.1.1/lib64:$ORIGIN:$ORIGIN/../lib:$ORIGIN/../lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/accel/nvidia/cc80/software/NCCL/2.18.3-GCCcore-12.3.0-CUDA-12.1.1/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/accel/nvidia/cc80/software/CUDA/12.1.1/lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/accel/nvidia/cc80/software/UCC-CUDA/1.2.0-GCCcore-12.3.0-CUDA-12.1.1/lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/GCCcore/12.3.0/lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/GCCcore/12.3.0/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/OpenMPI/4.1.5-GCC-12.3.0/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/hwloc/2.9.1-GCCcore-12.3.0/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/libevent/2.1.12-GCCcore-12.3.0/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/GDRCopy/2.3.1-GCCcore-12.3.0/lib/../lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/UCC/1.2.0-GCCcore-12.3.0/lib/../lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/PMIx/4.2.4-GCCcore-12.3.0/lib/../lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/libfabric/1.18.0-GCCcore-12.3.0/lib/../lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/UCX/1.14.1-GCCcore-12.3.0/lib/../lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/OpenSSL/1.1/lib/../lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/libpciaccess/0.17-GCCcore-12.3.0/lib/../lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/libxml2/2.11.4-GCCcore-12.3.0/lib/../lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/numactl/2.0.16-GCCcore-12.3.0/lib/../lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/GCCcore/12.3.0/lib/gcc/x86_64-pc-linux-gnu/12.3.0:/cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64/lib/../lib64:/cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64/usr/lib/../lib64:/cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64/lib:/cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64/usr/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/GDRCopy/2.3.1-GCCcore-12.3.0/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/UCC/1.2.0-GCCcore-12.3.0/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/PMIx/4.2.4-GCCcore-12.3.0/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/libfabric/1.18.0-GCCcore-12.3.0/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/UCX/1.14.1-GCCcore-12.3.0/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/OpenSSL/1.1/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/libpciaccess/0.17-GCCcore-12.3.0/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/libxml2/2.11.4-GCCcore-12.3.0/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/numactl/2.0.16-GCCcore-12.3.0/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/accel/nvidia/cc80/software/CUDA/12.1.1/lib]
```

For `zen3`:

```
$ readelf -d 2023.06/software/linux/x86_64/amd/zen3/accel/nvidia/cc80/software/OSU-Micro-Benchmarks/7.2-gompi-2023a-CUDA-12.1.1/libexec/osu-micro-benchmarks/mpi/pt2pt/osu_latency | grep RPATH | grep CUDA
 0x000000000000000f (RPATH)              Library rpath: [/cvmfs/software.eessi.io/host_injections/2023.06/software/linux/x86_64/amd/zen3/rpath_overrides/OpenMPI/system/lib:/cvmfs/software.eessi.io/host_injections/2023.06/software/linux/x86_64/amd/zen3/rpath_overrides/OpenMPI/system/lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/accel/nvidia/cc80/software/OSU-Micro-Benchmarks/7.2-gompi-2023a-CUDA-12.1.1/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/accel/nvidia/cc80/software/OSU-Micro-Benchmarks/7.2-gompi-2023a-CUDA-12.1.1/lib64:$ORIGIN:$ORIGIN/../lib:$ORIGIN/../lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/accel/nvidia/cc80/software/NCCL/2.18.3-GCCcore-12.3.0-CUDA-12.1.1/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/accel/nvidia/cc80/software/CUDA/12.1.1/lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/accel/nvidia/cc80/software/UCC-CUDA/1.2.0-GCCcore-12.3.0-CUDA-12.1.1/lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/GCCcore/12.3.0/lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/GCCcore/12.3.0/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/OpenMPI/4.1.5-GCC-12.3.0/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/hwloc/2.9.1-GCCcore-12.3.0/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/libevent/2.1.12-GCCcore-12.3.0/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/GDRCopy/2.3.1-GCCcore-12.3.0/lib/../lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/UCC/1.2.0-GCCcore-12.3.0/lib/../lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/PMIx/4.2.4-GCCcore-12.3.0/lib/../lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/libfabric/1.18.0-GCCcore-12.3.0/lib/../lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/UCX/1.14.1-GCCcore-12.3.0/lib/../lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/OpenSSL/1.1/lib/../lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/libpciaccess/0.17-GCCcore-12.3.0/lib/../lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/libxml2/2.11.4-GCCcore-12.3.0/lib/../lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/numactl/2.0.16-GCCcore-12.3.0/lib/../lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/GCCcore/12.3.0/lib/gcc/x86_64-pc-linux-gnu/12.3.0:/cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64/lib/../lib64:/cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64/usr/lib/../lib64:/cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64/lib:/cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64/usr/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/GDRCopy/2.3.1-GCCcore-12.3.0/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/UCC/1.2.0-GCCcore-12.3.0/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/PMIx/4.2.4-GCCcore-12.3.0/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/libfabric/1.18.0-GCCcore-12.3.0/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/UCX/1.14.1-GCCcore-12.3.0/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/OpenSSL/1.1/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/libpciaccess/0.17-GCCcore-12.3.0/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/libxml2/2.11.4-GCCcore-12.3.0/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/numactl/2.0.16-GCCcore-12.3.0/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/accel/nvidia/cc80/software/CUDA/12.1.1/lib]
```
Also fine!

**Comment by boegel** [comment]
Tested on our `zen3` + A100 cluster, in a 2-GPU Slurm job.

Bandwidth:
```
$ mpirun -np 2 osu_bw -d cuda -m 33554432 D D
# OSU MPI-CUDA Bandwidth Test v7.2
# Send Buffer on DEVICE (D) and Receive Buffer on DEVICE (D)
# Size      Bandwidth (MB/s)
# Datatype: MPI_CHAR.
1                       1.01
2                       1.19
4                       2.36
8                       4.55
16                     16.65
32                     33.78
64                     67.25
128                    84.75
256                   260.92
512                   173.38
1024                  299.62
2048                  451.33
4096                  458.77
8192                  525.73
16384                3857.74
32768                7994.64
65536               15294.18
131072              27755.39
262144              44371.70
524288              61133.24
1048576             73675.19
2097152             82905.64
4194304             87543.13
8388608             90981.81
16777216            92202.43
33554432            93130.52
```

That's getting close to the max. bandwidth of 100GBs/s between two A100's with 4x NVLink (each 25GB/s):
```
$ nvidia-smi topo -m
        GPU0    GPU1    NIC0    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      NV4     SYS             3               N/A
GPU1    NV4      X      SYS             5               N/A
NIC0    SYS     SYS      X

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  ...
  NV#  = Connection traversing a bonded set of # NVLinks
```

Latency:
```
$ mpirun -np 2 osu_latency -d cuda D D
# OSU MPI-CUDA Latency Test v7.2
# Send Buffer on DEVICE (D) and Receive Buffer on DEVICE (D)
# Size          Latency (us)
# Datatype: MPI_CHAR.
1                       1.54
2                       2.39
4                       2.35
8                       2.34
16                      1.57
32                      1.54
64                      1.55
128                     2.04
256                     2.00
512                     2.94
1024                    4.91
2048                    6.27
4096                   10.38
8192                   17.47
16384                  10.11
32768                   9.86
65536                  10.42
131072                 11.27
262144                 12.48
524288                 15.34
1048576                20.84
2097152                31.89
4194304                54.41
```

**Review by boegel — APPROVED** [review]

**Comment by boegel** [comment]
> For `zen2`:
> 
> ```
> [casparvl@login1 20007]$ readelf -d 2023.06/software/linux/x86_64/amd/zen2/accel/nvidia/cc80/software/OSU-Micro-Benchmarks/7.2-gompi-2023a-CUDA-12.1.1/libexec/osu-micro-benchmarks/mpi/pt2pt/osu_latency | grep RPATH | grep CUDA
>  0x000000000000000f (RPATH)              Library rpath: [/cvmfs/software.eessi.io/host_injections/2023.06/software/linux/x86_64/amd/zen2/rpath_overrides/OpenMPI/system/lib:/cvmfs/software.eessi.io/host_injections/2023.06/software/linux/x86_64/amd/zen2/rpath_overrides/OpenMPI/system/lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/accel/nvidia/cc80/software/OSU-Micro-Benchmarks/7.2-gompi-2023a-CUDA-12.1.1/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/accel/nvidia/cc80/software/OSU-Micro-Benchmarks/7.2-gompi-2023a-CUDA-12.1.1/lib64:$ORIGIN:$ORIGIN/../lib:$ORIGIN/../lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/accel/nvidia/cc80/software/NCCL/2.18.3-GCCcore-12.3.0-CUDA-12.1.1/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/accel/nvidia/cc80/software/CUDA/12.1.1/lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/accel/nvidia/cc80/software/UCC-CUDA/1.2.0-GCCcore-12.3.0-CUDA-12.1.1/lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/GCCcore/12.3.0/lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/GCCcore/12.3.0/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/OpenMPI/4.1.5-GCC-12.3.0/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/hwloc/2.9.1-GCCcore-12.3.0/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/libevent/2.1.12-GCCcore-12.3.0/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/GDRCopy/2.3.1-GCCcore-12.3.0/lib/../lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/UCC/1.2.0-GCCcore-12.3.0/lib/../lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/PMIx/4.2.4-GCCcore-12.3.0/lib/../lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/libfabric/1.18.0-GCCcore-12.3.0/lib/../lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/UCX/1.14.1-GCCcore-12.3.0/lib/../lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/OpenSSL/1.1/lib/../lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/libpciaccess/0.17-GCCcore-12.3.0/lib/../lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/libxml2/2.11.4-GCCcore-12.3.0/lib/../lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/numactl/2.0.16-GCCcore-12.3.0/lib/../lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/GCCcore/12.3.0/lib/gcc/x86_64-pc-linux-gnu/12.3.0:/cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64/lib/../lib64:/cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64/usr/lib/../lib64:/cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64/lib:/cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64/usr/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/GDRCopy/2.3.1-GCCcore-12.3.0/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/UCC/1.2.0-GCCcore-12.3.0/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/PMIx/4.2.4-GCCcore-12.3.0/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/libfabric/1.18.0-GCCcore-12.3.0/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/UCX/1.14.1-GCCcore-12.3.0/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/OpenSSL/1.1/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/libpciaccess/0.17-GCCcore-12.3.0/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/libxml2/2.11.4-GCCcore-12.3.0/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/numactl/2.0.16-GCCcore-12.3.0/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/accel/nvidia/cc80/software/CUDA/12.1.1/lib]
> ```
> 
> For `zen3`:
> 
> ```
> $ readelf -d 2023.06/software/linux/x86_64/amd/zen3/accel/nvidia/cc80/software/OSU-Micro-Benchmarks/7.2-gompi-2023a-CUDA-12.1.1/libexec/osu-micro-benchmarks/mpi/pt2pt/osu_latency | grep RPATH | grep CUDA
>  0x000000000000000f (RPATH)              Library rpath: [/cvmfs/software.eessi.io/host_injections/2023.06/software/linux/x86_64/amd/zen3/rpath_overrides/OpenMPI/system/lib:/cvmfs/software.eessi.io/host_injections/2023.06/software/linux/x86_64/amd/zen3/rpath_overrides/OpenMPI/system/lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/accel/nvidia/cc80/software/OSU-Micro-Benchmarks/7.2-gompi-2023a-CUDA-12.1.1/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/accel/nvidia/cc80/software/OSU-Micro-Benchmarks/7.2-gompi-2023a-CUDA-12.1.1/lib64:$ORIGIN:$ORIGIN/../lib:$ORIGIN/../lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/accel/nvidia/cc80/software/NCCL/2.18.3-GCCcore-12.3.0-CUDA-12.1.1/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/accel/nvidia/cc80/software/CUDA/12.1.1/lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/accel/nvidia/cc80/software/UCC-CUDA/1.2.0-GCCcore-12.3.0-CUDA-12.1.1/lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/GCCcore/12.3.0/lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/GCCcore/12.3.0/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/OpenMPI/4.1.5-GCC-12.3.0/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/hwloc/2.9.1-GCCcore-12.3.0/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/libevent/2.1.12-GCCcore-12.3.0/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/GDRCopy/2.3.1-GCCcore-12.3.0/lib/../lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/UCC/1.2.0-GCCcore-12.3.0/lib/../lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/PMIx/4.2.4-GCCcore-12.3.0/lib/../lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/libfabric/1.18.0-GCCcore-12.3.0/lib/../lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/UCX/1.14.1-GCCcore-12.3.0/lib/../lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/OpenSSL/1.1/lib/../lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/libpciaccess/0.17-GCCcore-12.3.0/lib/../lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/libxml2/2.11.4-GCCcore-12.3.0/lib/../lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/numactl/2.0.16-GCCcore-12.3.0/lib/../lib64:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/GCCcore/12.3.0/lib/gcc/x86_64-pc-linux-gnu/12.3.0:/cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64/lib/../lib64:/cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64/usr/lib/../lib64:/cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64/lib:/cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64/usr/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/GDRCopy/2.3.1-GCCcore-12.3.0/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/UCC/1.2.0-GCCcore-12.3.0/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/PMIx/4.2.4-GCCcore-12.3.0/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/libfabric/1.18.0-GCCcore-12.3.0/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/UCX/1.14.1-GCCcore-12.3.0/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/OpenSSL/1.1/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/libpciaccess/0.17-GCCcore-12.3.0/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/libxml2/2.11.4-GCCcore-12.3.0/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/numactl/2.0.16-GCCcore-12.3.0/lib:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/accel/nvidia/cc80/software/CUDA/12.1.1/lib]
> ```
> 
> Also fine!

Just to confirm:
```
$ ldd $(which osu_bw) | grep CUDA
        libcudart.so.12 => /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/accel/nvidia/cc80/software/CUDA/12.1.1/lib64/libcudart.so.12 (0x00001493be200000)
        libnccl.so.2 => /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/accel/nvidia/cc80/software/NCCL/2.18.3-GCCcore-12.3.0-CUDA-12.1.1/lib/libnccl.so.2 (0x00001493bbb7b000)
```

**Pull request merged**
