### PR TITLE
{2023.06,zen4}[2023a] BioPerl 1.7.8

### PR DESCRIPTION
**Pull request by TopRichard**
Follow up to #658

### CODE REVIEW

**Comment by TopRichard** [comment]
bot: build repo:eessi.io-2023.06-software arch:zen4

**Comment by ocaisa** [comment]
bot: build repo:eessi.io-2023.06-software arch:zen4

**Review by ocaisa — APPROVED** [review]
LGTM

**Comment by ocaisa** [comment]
Tarball has been ingested

**Pull request merged**
