### PR TITLE
{2023.06}[foss/2023b] GROMACS 2024.4

### PR DESCRIPTION
**Pull request by bedroge**

### CODE REVIEW

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen4

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen4

**Comment by bedroge** [comment]
The zen4 cluster got reinstalled, so let's try this one more time:

bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen4

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen4

**Comment by ocaisa** [comment]
@bedroge The test suite was just hanging, no CPU usage, I killed the mpi tasks. May be a freak error so I try again:

bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen4

**Comment by bedroge** [comment]
It's stuck again in the test step, this is the last part of the process tree:
```
bot        76511  0.0  0.0   6152  2688 ?        S    11:05   0:00      |       |   |                                   \_ make -f python_packaging/sample_restraint/tests/CMakeFiles/gmxapi_extension_pytest.dir/build.make python_packaging/sample_restraint/tests/CMakeFiles/gmxapi_extension_pytest.dir/build
bot        76513  0.0  0.0   2592  1728 ?        S    11:05   0:00      |       |   |                                   |   \_ /bin/sh -c cd /tmp/bot/easybuild/build/GROMACS/2024.4/foss-2023b/easybuild_obj/python_packaging/gmxapi/gmxapi_staging && /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen4/software/CMake/3.27.6-GCCcore-13.2.0/bin/cmake -E env --unset=OMP_NUM_THREADS LD_LIBRARY_PATH= PYTHONPATH=/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen4/software/mpi4py/3.1.5-gompi-2023b/lib/python3.11/site-packages:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen4/software/networkx/3.2.1-gfbf-2023b/lib/python3.11/site-packages:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen4/software/SciPy-bundle/2023.11-gfbf-2023b/lib/python3.11/site-packages:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen4/software/pybind11/2.11.1-GCCcore-13.2.0/lib/python3.11/site-packages:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen4/software/Python/3.11.5-GCCcore-13.2.0/easybuild/python:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen4/software/scikit-build-core/0.9.3-GCCcore-13.2.0/lib/python3.11/site-packages:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen4/software/Python-bundle-PyPI/2023.10-GCCcore-13.2.0/lib/python3.11/site-packages:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen4/software/virtualenv/20.24.6-GCCcore-13.2.0/lib/python3.11/site-packages:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen4/software/cryptography/41.0.5-GCCcore-13.2.0/lib/python3.11/site-packages:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen4/software/cffi/1.15.1-GCCcore-13.2.0/lib/python3.11/site-packages:/tmp/bot/easybuild/build/GROMACS/2024.4/foss-2023b/easybuild_obj/python_packaging/gmxapi/gmxapi_staging:/tmp/bot/easybuild/build/GROMACS/2024.4/foss-2023b/easybuild_obj/lib /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen4/software/Python/3.11.5-GCCcore-13.2.0/bin/python -m pytest --log-cli-level ERROR /tmp/bot/easybuild/build/GROMACS/2024.4/foss-2023b/gromacs-2024.4/python_packaging/sample_restraint/tests
bot        76515  0.0  0.0  27768 10176 ?        S    11:05   0:00      |       |   |                                   |       \_ /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen4/software/CMake/3.27.6-GCCcore-13.2.0/bin/cmake -E env --unset=OMP_NUM_THREADS LD_LIBRARY_PATH= PYTHONPATH=/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen4/software/mpi4py/3.1.5-gompi-2023b/lib/python3.11/site-packages:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen4/software/networkx/3.2.1-gfbf-2023b/lib/python3.11/site-packages:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen4/software/SciPy-bundle/2023.11-gfbf-2023b/lib/python3.11/site-packages:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen4/software/pybind11/2.11.1-GCCcore-13.2.0/lib/python3.11/site-packages:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen4/software/Python/3.11.5-GCCcore-13.2.0/easybuild/python:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen4/software/scikit-build-core/0.9.3-GCCcore-13.2.0/lib/python3.11/site-packages:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen4/software/Python-bundle-PyPI/2023.10-GCCcore-13.2.0/lib/python3.11/site-packages:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen4/software/virtualenv/20.24.6-GCCcore-13.2.0/lib/python3.11/site-packages:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen4/software/cryptography/41.0.5-GCCcore-13.2.0/lib/python3.11/site-packages:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen4/software/cffi/1.15.1-GCCcore-13.2.0/lib/python3.11/site-packages:/tmp/bot/easybuild/build/GROMACS/2024.4/foss-2023b/easybuild_obj/python_packaging/gmxapi/gmxapi_staging:/tmp/bot/easybuild/build/GROMACS/2024.4/foss-2023b/easybuild_obj/lib /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen4/software/Python/3.11.5-GCCcore-13.2.0/bin/python -m pytest --log-cli-level ERROR /tmp/bot/easybuild/build/GROMACS/2024.4/foss-2023b/gromacs-2024.4/python_packaging/sample_restraint/tests
bot        76516  0.8  0.0 3698940 252168 ?      Sl   11:05   0:44      |       |   |                                   |           \_ /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen4/software/Python/3.11.5-GCCcore-13.2.0/bin/python -m pytest --log-cli-level ERROR /tmp/bot/easybuild/build/GROMACS/2024.4/foss-2023b/gromacs-2024.4/python_packaging/sample_restraint/tests
bot        76538  0.0  0.0  90760 19840 ?        Ssl  11:05   0:00      |       |   |                                   |               \_ orted --hnp --set-sid --report-uri 14 --singleton-died-pipe 15 -mca state_novm_select 1 -mca ess hnp -mca pmix ^s1,s2,cray,isolated
bot        76623  0.0  0.0 3421916 65776 ?       Sl   11:05   0:00      |       |   |                                   |               \_ /tmp/bot/easybuild/build/GROMACS/2024.4/foss-2023b/easybuild_obj/bin/gmx_mpi grompp -f /tmp/eb-_j823wne/eb-7tm2hwi4/pytest-of-bot/pytest-6/spc_water_box0/md.mdp -p /tmp/eb-_j823wne/eb-7tm2hwi4/pytest-of-bot/pytest-6/spc_water_box0/topology.top -c /tmp/eb-_j823wne/eb-7tm2hwi4/pytest-of-bot/pytest-6/spc_water_box0/structure.gro -po /tmp/eb-_j823wne/eb-7tm2hwi4/pytest-of-bot/pytest-6/spc_water_box0/mdout.mdp -o /tmp/eb-_j823wne/eb-7tm2hwi4/pytest-of-bot/pytest-6/spc_water_box0/topol.tpr
bot        76624  0.0  0.0  90760 20228 ?        Ssl  11:05   0:00      |       |   |                                   |                   \_ orted --hnp --set-sid --report-uri 8 --singleton-died-pipe 9 -mca state_novm_select 1 -mca ess hnp -mca pmix ^s1,s2,cray,isolated
bot        91515  0.0  0.0   6152  2688 ?        S    11:06   0:00      |       |   |                                   \_ make -f CMakeFiles/run-ctest-nophys.dir/build.make CMakeFiles/run-ctest-nophys.dir/build
bot        91518  0.0  0.0  30280 14208 ?        S    11:06   0:00      |       |   |                                       \_ /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen4/software/CMake/3.27.6-GCCcore-13.2.0/bin/ctest --output-on-failure -E physicalvalidationtests
bot        92903  0.0  0.0 408416 68828 ?        Sl   12:12   0:00      |       |   |                                           \_ /tmp/bot/easybuild/build/GROMACS/2024.4/foss-2023b/easybuild_obj/bin/pdb2gmx1-test --gtest_output=xml:/tmp/bot/easybuild/build/GROMACS/2024.4/foss-2023b/easybuild_obj/Testing/Temporary/Pdb2gmx1Test.xml
bot        92904  0.0  0.0  90760 20224 ?        Ssl  12:12   0:00      |       |   |                                               \_ orted --hnp --set-sid --report-uri 9 --singleton-died-pipe 10 -mca state_novm_select 1 -mca ess hnp -mca pmix ^s1,s2,cray,isolated
```

**Comment by ocaisa** [comment]
Let's try this once more, I was still messing around with the Zen4 cluster on Friday (though not intentionally!)

bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen4

**Comment by bedroge** [comment]
I think it's stuck again, this is the last part of the process tree:

```
bot        32821  0.0  0.0   2592  1728 ?        S    08:37   0:00      |       |   |                                       \_ /bin/sh -c cd /tmp/bot/easybuild/build/GROMACS/2024.4/foss-2023b/easybuild_obj/python_packaging/gmxapi/gmxapi_staging && /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen4/software/CMake/3.27.6-GCCcore-13.2.0/bin/cmake -E env --unset=OMP_NUM_THREADS /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen4/software/Python/3.11.5-GCCcore-13.2.0/bin/python -m pytest -rA -l --log-cli-level ERROR /tmp/bot/easybuild/build/GROMACS/2024.4/foss-2023b/gromacs-2024.4/python_packaging/gmxapi/test
bot        32822  0.0  0.0  27768 10368 ?        S    08:37   0:00      |       |   |                                           \_ /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen4/software/CMake/3.27.6-GCCcore-13.2.0/bin/cmake -E env --unset=OMP_NUM_THREADS /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen4/software/Python/3.11.5-GCCcore-13.2.0/bin/python -m pytest -rA -l --log-cli-level ERROR /tmp/bot/easybuild/build/GROMACS/2024.4/foss-2023b/gromacs-2024.4/python_packaging/gmxapi/test
bot        32824  0.0  0.0 238188 79844 ?        Sl   08:37   0:00      |       |   |                                               \_ /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen4/software/Python/3.11.5-GCCcore-13.2.0/bin/python -m pytest -rA -l --log-cli-level ERROR /tmp/bot/easybuild/build/GROMACS/2024.4/foss-2023b/gromacs-2024.4/python_packaging/gmxapi/test
bot        32834  0.0  0.0  90756 20244 ?        Ssl  08:37   0:00      |       |   |                                                   \_ orted --hnp --set-sid --report-uri 14 --singleton-died-pipe 15 -mca state_novm_select 1 -mca ess hnp -mca pmix ^s1,s2,cray,isolated
```

**Comment by bedroge** [comment]
Situation is still exactly the same, so it's really stuck. I had a look at the log files on the node, and `easybuild_obj/Testing/Temporary/LastTest.log` shows that the tests seem to have completed:
```
89/89 Testing: EnsembleBoundingPotentialPlugin.ForceCalc
89/89 Test: EnsembleBoundingPotentialPlugin.ForceCalc
Command: "/tmp/bot/easybuild/build/GROMACS/2024.4/foss-2023b/easybuild_obj/bin/gmxapi_extension_bounding-test" "--gtest_filter=EnsembleBoundingPotentialPlugin.ForceCalc"
Directory: /tmp/bot/easybuild/build/GROMACS/2024.4/foss-2023b/easybuild_obj/python_packaging/sample_restraint/tests
"EnsembleBoundingPotentialPlugin.ForceCalc" start time: Nov 25 08:39 UTC
Output:
----------------------------------------------------------
Running main() from /tmp/bot/easybuild/build/GROMACS/2024.4/foss-2023b/gromacs-2024.4/src/external/googletest/googletest/src/gtest_main.cc
Note: Google Test filter = EnsembleBoundingPotentialPlugin.ForceCalc
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from EnsembleBoundingPotentialPlugin
[ RUN      ] EnsembleBoundingPotentialPlugin.ForceCalc
[       OK ] EnsembleBoundingPotentialPlugin.ForceCalc (0 ms)
[----------] 1 test from EnsembleBoundingPotentialPlugin (0 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (0 ms total)
[  PASSED  ] 1 test.
<end of output>
Test time =   0.05 sec
----------------------------------------------------------
Test Passed.
"EnsembleBoundingPotentialPlugin.ForceCalc" end time: Nov 25 08:39 UTC
"EnsembleBoundingPotentialPlugin.ForceCalc" time elapsed: 00:00:00
----------------------------------------------------------

End testing: Nov 25 08:39 UTC

GTest =  82.01 sec*proc

IntegrationTest =  42.41 sec*proc

MpiTest =  51.55 sec*proc

QuickGpuTest =  11.36 sec*proc

SlowGpuTest =  61.33 sec*proc

SlowTest =  36.34 sec*proc

UnitTest =   3.26 sec*proc

```
So it's somehow getting stuck during the completion phase of the test suite.

**Comment by bedroge** [comment]
I've killed that `orted` process (with -9, otherwise it couldn't be killed), and now the Easybuild log shows:
```
100% tests passed, 0 tests failed out of 89

Label Time Summary:
GTest              =  82.01 sec*proc (85 tests)
IntegrationTest    =  42.41 sec*proc (28 tests)
MpiTest            =  51.55 sec*proc (21 tests)
QuickGpuTest       =  11.36 sec*proc (20 tests)
SlowGpuTest        =  61.33 sec*proc (14 tests)
SlowTest           =  36.34 sec*proc (13 tests)
UnitTest           =   3.26 sec*proc (44 tests)

Total Test time (real) =  47.23 sec
make[3]: Leaving directory '/tmp/bot/easybuild/build/GROMACS/2024.4/foss-2023b/easybuild_obj'
[100%] Built target run-ctest-nophys
make  -f tests/CMakeFiles/missing-tests-notice.dir/build.make tests/CMakeFiles/missing-tests-notice.dir/depend
make[3]: Entering directory '/tmp/bot/easybuild/build/GROMACS/2024.4/foss-2023b/easybuild_obj'
cd /tmp/bot/easybuild/build/GROMACS/2024.4/foss-2023b/easybuild_obj && /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen4/software/CMake/3.27.6-GCCcore-13.2.0/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/bot/easybuild/build/GROMACS/2024.4/foss-2023b/gromacs-2024.4 /tmp/bot/easybuild/build/GROMACS/2024.4/foss-2023b/gromacs-2024.4/tests /tmp/bot/easybuild/build/GROMACS/2024.4/foss-2023b/easybuild_obj /tmp/bot/easybuild/build/GROMACS/2024.4/foss-2023b/easybuild_obj/tests /tmp/bot/easybuild/build/GROMACS/2024.4/foss-2023b/easybuild_obj/tests/CMakeFiles/missing-tests-notice.dir/DependInfo.cmake "--color="
make[3]: Leaving directory '/tmp/bot/easybuild/build/GROMACS/2024.4/foss-2023b/easybuild_obj'
make  -f tests/CMakeFiles/missing-tests-notice.dir/build.make tests/CMakeFiles/missing-tests-notice.dir/build
make[3]: Entering directory '/tmp/bot/easybuild/build/GROMACS/2024.4/foss-2023b/easybuild_obj'
[100%] Some tests not available
cd /tmp/bot/easybuild/build/GROMACS/2024.4/foss-2023b/easybuild_obj/tests && /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen4/software/CMake/3.27.6-GCCcore-13.2.0/bin/cmake -E echo "NOTE: Regression tests have not been run. If you want to run them from the build system, get the correct version of the regression tests package and set REGRESSIONTEST_PATH in CMake to point to it, or set REGRESSIONTEST_DOWNLOAD=ON."
NOTE: Regression tests have not been run. If you want to run them from the build system, get the correct version of the regression tests package and set REGRESSIONTEST_PATH in CMake to point to it, or set REGRESSIONTEST_DOWNLOAD=ON.
make[3]: Leaving directory '/tmp/bot/easybuild/build/GROMACS/2024.4/foss-2023b/easybuild_obj'
[100%] Built target missing-tests-notice
make[3]: *** [python_packaging/gmxapi/test/CMakeFiles/gmxapi_pytest.dir/build.make:73: python_packaging/gmxapi/test/CMakeFiles/gmxapi_pytest] Error 195
make[3]: Leaving directory '/tmp/bot/easybuild/build/GROMACS/2024.4/foss-2023b/easybuild_obj'
make[2]: *** [CMakeFiles/Makefile2:7260: python_packaging/gmxapi/test/CMakeFiles/gmxapi_pytest.dir/all] Error 2
make[2]: Leaving directory '/tmp/bot/easybuild/build/GROMACS/2024.4/foss-2023b/easybuild_obj'
make[1]: *** [CMakeFiles/Makefile2:3472: CMakeFiles/check.dir/rule] Error 2
make[1]: Leaving directory '/tmp/bot/easybuild/build/GROMACS/2024.4/foss-2023b/easybuild_obj'
make: *** [Makefile:632: check] Error 2
```

**Comment by bedroge** [comment]
I've tried to  add a SitePackage.lua that sets `FI_PROVIDER="^psm3"` for the zen4 bot, let's try again.

bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen4

**Comment by bedroge** [comment]
> @bedroge Is this now ready to deploy?

Yes, I think so.

**Review by ocaisa — APPROVED** [review]

**Pull request merged**
