### PR TITLE
Put a Lmod-relevant wrapper in place for archdetect accelerator detection

### PR DESCRIPTION
**Pull request by ocaisa**

### CODE REVIEW

**Comment by ocaisa** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic

**Review by trz42 — APPROVED** [review]
Looks good to me. Maybe a bit explanation of why this is necessary and how it would be used (e.g., alone or together with `lmod_eessi_archdetect_wrapper.sh`) would help to understand/assess it more easily.

**Comment by ocaisa** [comment]
This is part of #781 , where I have a chicken egg situation (I need the script in place so they module can be tested in CI). The wrapper is required so I only take absolutely minimal changes from the called script (in my case I just want the value of result, no error codes or anything)

**Comment by trz42** [comment]
Script has become available via CernVM-FS:

```
$ cat /cvmfs/software.eessi.io/versions/2023.06/init/lmod_eessi_archdetect_wrapper_accel.sh
# This can be leveraged by the source_sh() feature of Lmod
export EESSI_ACCEL_SUBDIR=$($(dirname $(readlink -f $BASH_SOURCE))/eessi_archdetect.sh accelpath)
```

**Pull request merged**
