### PR TITLE
{2023.06}[2023a,zen4] JupyterNotebook v7.0.2

### PR DESCRIPTION
**Pull request by laraPPr**

### CODE REVIEW

**Comment by laraPPr** [comment]
bot: build repo:eessi.io-2023.06-software arch:zen4

**Comment by laraPPr** [comment]
I may have trigired this to soon because LAMMPS seems to be in the tarball as well

**Comment by laraPPr** [comment]
Should I restart the build after deploy of https://github.com/EESSI/software-layer/pull/705 is complete?

**Comment by laraPPr** [comment]
bot: build repo:eessi.io-2023.06-software arch:zen4

**Comment by boegel** [comment]
staging PR merged

**Review by boegel — APPROVED** [review]

**Pull request merged**
