### PR TITLE
add support for detecting zen4 in archspec

### PR DESCRIPTION
**Pull request by hmeiland**
zen4 feature for archdetect

### CODE REVIEW

**Comment by hmeiland** [comment]
recreated PR to fix merge conflicts... comes from #447

**Review by boegel — APPROVED** [review]

**Comment by casparvl** [comment]
@boegel You merged without deploying. Not a big deal, now the deployment of the new `init/arch_specs/eessi_arch_x86.spec` shows up in https://github.com/EESSI/software-layer/pull/530

**Comment by boegel** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3

**Comment by boegel** [comment]
Ah, bot doesn't like triggering builds for merged PRs...

**Pull request merged**
