### PR TITLE
{2023.06}[2021b] FFTW v3.3.10

### PR DESCRIPTION
**Pull request by laraPPr**

### CODE REVIEW

**Comment by laraPPr** [comment]
bot: build repo:eessi-2023.06-software

**Comment by boegel** [comment]
Installation for `aarch64-neoverse_v1` failed in test step:

<details>

```
== testing...
  >> running command:
	[started at: 2023-07-05 12:40:59]
	[working dir: /tmp/bot/easybuild/build/FFTW/3.3.10/gompi-2021b/fftw-3.3.10]
	[output logged in /tmp/eb-w27hawxe/eb-4xka33wh/eb-kx5jstfc/eb-uiwzeu3g/eb-qbfn3o2c/eb-k5wt1gpn/eb-hmt8g6_7/eb-u6gpqr89/eb-y9d8qwo2/easybuild-run_cmd-8asnqcgm.log]
	export OMPI_MCA_rmaps_base_oversubscribe=true &&   make check
  >> command completed: exit 2, ran in 00h01m04s
== ... (took 1 min 4 secs)
== FAILED: Installation ended unsuccessfully (build directory: /tmp/bot/easybuild/build/FFTW/3.3.10/gompi-2021b): build failed (first 300 chars): cmd " export OMPI_MCA_rmaps_base_oversubscribe=true &&   make check " exited with exit code 2 and output:
Making check in support
make[1]: Entering directory '/tmp/bot/easybuild/build/FFTW/3.3.10/gompi-2021b/fftw-3.3.10/support'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/t (took 6 mins 41 secs)
```

</details>

The actual problem here isn't shown, unclear which test fails, we need to make sure the EasyBuild log is retained for closer inspection...

**Comment by laraPPr** [comment]
bot: build repo:eessi-2023.06-software arch:aarch64/neoverse_v1

**Comment by laraPPr** [comment]
bot: build repo:eessi-2023.06-software arch:aarch64/neoverse_v1

**Comment by boegel** [comment]
It looks like the trouble we've been running into here on `aarch64-neoverse_v1` doesn't happen consistently, since `FFTW/3.3.10-gompi-2021b` was built without problems in #289 ...

**Comment by boegel** [comment]
More info on the failing test for `FFTW/3.3.10-gompi-2021b` on `aarch64-neoverse_v1`:

<details>

```
...
--------------------------------------------------------------
      MPI FFTW transforms passed 10 tests, 2 CPUs
--------------------------------------------------------------
perl -w ../tests/check.pl --verbose --random --maxsize=10000 -c=10  --mpi "mpirun -np 3 `pwd`/mpi-bench"
Executing "mpirun -np 3 /tmp/bot/easybuild/build/FFTW/3.3.10/gompi-2021b/fftw-3.3.10/mpi/mpi-bench --verbose=1   --verify 'obr[8x11v5' --verify 'ibr[8x11v5' --verify 'obc[8x11v5' --verify 'ibc[8x11v5' --verify 'ofc[8x11v5' --verify 'ifc[8x11v5' --verify 'obrd[10x9' --verify 'ibrd[10x9' --verify 'obcd[10x9' --verify 'ibcd[10x9' --verify 'ofcd[10x9' --verify 'ifcd[10x9' --verify 'ok]10hx10o01x13o01' --verify 'ik]10hx10o01x13o01' --verify 'obcd35' --verify 'ibcd35' --verify 'ofcd35' --verify 'ifcd35' --verify 'ok3o00x12o11x14o01x5e10' --verify 'ik3o00x12o11x14o01x5e10' --verify 'obr[5x6x2x10v3' --verify 'ibr[5x6x2x10v3' --verify 'obc[5x6x2x10v3' --verify 'ibc[5x6x2x10v3' --verify 'ofc[5x6x2x10v3' --verify 'ifc[5x6x2x10v3' --verify 'ok7e00x12e01x8e10v7' --verify 'ik7e00x12e01x8e10v7' --verify 'obrd7x13' --verify 'ibrd7x13' --verify 'ofrd7x13' --verify 'ifrd7x13' --verify 'obcd7x13' --verify 'ibcd7x13' --verify 'ofcd7x13' --verify 'ifcd7x13' --verify 'obr[8x7v17' --verify 'ibr[8x7v17' --verify 'obc[8x7v17' --verify 'ibc[8x7v17' --verify 'ofc[8x7v17' --verify 'ifc[8x7v17' --verify 'ok3o01x11e00x7e01x6e00' --verify 'ik3o01x11e00x7e01x6e00'"
obr[8x11v5 3.04679e-16 3.40848e-16 2.72795e-16
ibr[8x11v5 3.09102e-16 5.68081e-16 3.287e-16
obc[8x11v5 2.99201e-16 4.54465e-16 5.23099e-16
ibc[8x11v5 3.33118e-16 3.40848e-16 4.53802e-16
ofc[8x11v5 3.53326e-16 3.40848e-16 5.857e-16
ifc[8x11v5 3.83947e-16 5.68081e-16 5.44608e-16
obrd[10x9 2.82987e-16 5.61733e-16 3.42072e-16
ibrd[10x9 3.31574e-16 7.48978e-16 3.74729e-16
obcd[10x9 2.72087e-16 3.74489e-16 5.19925e-16
ibcd[10x9 2.67526e-16 3.74489e-16 6.12669e-16
ofcd[10x9 3.21627e-16 3.74489e-16 5.2687e-16
ifcd[10x9 2.78883e-16 5.61733e-16 5.97321e-16
ok]10hx10o01x13o01 4.16996e-16 6.29475e-15 4.66257e-16
ik]10hx10o01x13o01 4.10441e-16 8.71148e-15 4.30452e-16
obcd35 3.36549e-16 4.50389e-16 4.51235e-16
ibcd35 3.05726e-16 4.50389e-16 3.66839e-16
ofcd35 2.72084e-16 4.50389e-16 3.73605e-16
ifcd35 2.93105e-16 4.50389e-16 5.36327e-16
ok3o00x12o11x14o01x5e10 3.86285e-16 8.64926e-15 4.92189e-16
ik3o00x12o11x14o01x5e10 4.27231e-16 6.67589e-15 4.65841e-16
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 2 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
FAILED mpirun -np 3 /tmp/bot/easybuild/build/FFTW/3.3.10/gompi-2021b/fftw-3.3.10/mpi/mpi-bench:  --verify 'obr[8x11v5' --verify 'ibr[8x11v5' --verify 'obc[8x11v5' --verify 'ibc[8x11v5' --verify 'ofc[8x11v5' --verify 'ifc[8x11v5' --verify 'obrd[10x9' --verify 'ibrd[10x9' --verify 'obcd[10x9' --verify 'ibcd[10x9' --verify 'ofcd[10x9' --verify 'ifcd[10x9' --verify 'ok]10hx10o01x13o01' --verify 'ik]10hx10o01x13o01' --verify 'obcd35' --verify 'ibcd35' --verify 'ofcd35' --verify 'ifcd35' --verify 'ok3o00x12o11x14o01x5e10' --verify 'ik3o00x12o11x14o01x5e10' --verify 'obr[5x6x2x10v3' --verify 'ibr[5x6x2x10v3' --verify 'obc[5x6x2x10v3' --verify 'ibc[5x6x2x10v3' --verify 'ofc[5x6x2x10v3' --verify 'ifc[5x6x2x10v3' --verify 'ok7e00x12e01x8e10v7' --verify 'ik7e00x12e01x8e10v7' --verify 'obrd7x13' --verify 'ibrd7x13' --verify 'ofrd7x13' --verify 'ifrd7x13' --verify 'obcd7x13' --verify 'ibcd7x13' --verify 'ofcd7x13' --verify 'ifcd7x13' --verify 'obr[8x7v17' --verify 'ibr[8x7v17' --verify 'obc[8x7v17' --verify 'ibc[8x7v17' --verify 'ofc[8x7v17' --verify 'ifc[8x7v17' --verify 'ok3o01x11e00x7e01x6e00' --verify 'ik3o01x11e00x7e01x6e00'
make[3]: *** [Makefile:1001: check-local] Error 1
make[3]: Leaving directory '/tmp/bot/easybuild/build/FFTW/3.3.10/gompi-2021b/fftw-3.3.10/mpi'
make[2]: *** [Makefile:786: check-am] Error 2
make[2]: Leaving directory '/tmp/bot/easybuild/build/FFTW/3.3.10/gompi-2021b/fftw-3.3.10/mpi'
make[1]: *** [Makefile:788: check] Error 2
make[1]: Leaving directory '/tmp/bot/easybuild/build/FFTW/3.3.10/gompi-2021b/fftw-3.3.10/mpi'
make: *** [Makefile:710: check-recursive] Error 1
 (at easybuild/tools/run.py:643 in parse_cmd_output)
```

</details>

**Comment by boegel** [comment]
I'll re-trigger CI for this PR in a bit, since tarballs that include `FFTW/3.3.10-gompi-2021b` have been deployed via #289, and then close it since I don't see a need for explicitly listing `FFTW/3.3.10-gompi-2021b` in the easystack file (it's part of `foss/2021b` that was included in #289)

**Pull request closed without merging**
