### PR TITLE
{2023.06}[GCC/12.3.0] mosdepth v0.3.9

### PR DESCRIPTION
**Pull request by TopRichard**
missing packages:
```
mosdepth/0.3.9-GCC-12.3.0
Nim/2.2.0-GCCcore-12.3.0
```

### CODE REVIEW

**Comment by TopRichard** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic

**Comment by TopRichard** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1
bot: build repo:eessi.io-2023.06-software arch:zen4

**Comment by bedroge** [comment]
Discussed this a bit with @TopRichard on Slack: it looks like the paths for the failing jobs is just a little bit too long, since the ones with a slightly shorter CPU path do work:
```
# these work fine:
x86_64/generic
aarch64/generic
x86_64/amd/zenX

# these don't:
aarch64/neoverse_n1
aarch64/neoverse_v1
x86_64/intel/haswell
x86_64/intel/skylake_avx512
```

Though it would be nice to have a proper and generic solution (see #296), we could try working around it for this particular package for now by using a shorter path for the Nim cache, see https://nim-lang.org/docs/nimc.html#compiler-usage-generated-c-code-directory. We're currently using the home dir, which is set to `/eessi_bot_job` in the container, so the Nim cache will be under `/eessi_bot_job/.cache/nim`. By setting `$XDG_CACHE_HOME` to e.g. `/tmp` (in a hook), the Nim cache will be under `/tmp/nim`, which should shorten the path enough to make it work for the failing architectures.

**Comment by TopRichard** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512

**Comment by TopRichard** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell

**Comment by TopRichard** [comment]
Trying the workaround by setting `$XDG_CACHE_HOME` to  /tmp in a hook results in:
```
Error: cannot open '/tmp/nim/mosdepth_r/@m..@s..@s..@s..@s..@s..@s..@s..@scvmfs@ssoftware.eessi.io@sversions@s2023.06@ssoftware@slinux@sx86_64@sintel@sskylake_avx512@ssoftware@smosdepth@s0.3.9-GCC-12.3.0@spkgs2@sunicodedb-0.13.0-5c5fc0c8a83d270aca74fe41d33158e9042bb91a@sunicodedb@sproperties_data.nim.c'
```

**Comment by TopRichard** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1

**Pull request closed without merging**
