### PR TITLE
{2023.06}[system] EasyBuild v4.9.0

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic

**Comment by boegel** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic

**Comment by boegel** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1

**Comment by trz42** [comment]
Looks good.

Curious though, what is the intention for the additional number in the easystack file (`-001-`)?

**Comment by boegel** [comment]
> Looks good.
> 
> Curious though, what is the intention for the additional number in the easystack file (`-001-`)?

That's to make sure that that easystack file is processed first, before toolchain-specific ones like `2022b` (`system` sorts *after* `20xy` alphabetically).

```
$ ls easystacks/software.eessi.io/2023.06
...
eessi-2023.06-eb-4.8.2-001-system.yml
eessi-2023.06-eb-4.8.2-010-CUDA.yml
eessi-2023.06-eb-4.8.2-2022b.yml
eessi-2023.06-eb-4.8.2-2023a.yml
eessi-2023.06-eb-4.9.0-001-system.yml
```

That was done when adding `CUDA` in #434, because we need to make sure that `EasyBuild` is installed before `CUDA` (which is installed via a dedicated easystack file that uses `-010-` in the filename).

**Review by bedroge — APPROVED** [review]

**Pull request merged**
