### PR TITLE
{2023.06,2023a+2023b,zen4} Rebuild Python + add librosa 0.10.1

### PR DESCRIPTION
**Pull request by trz42**
Companion PR for #655 to apply changes also on `zen4`.

### CODE REVIEW

**Comment by trz42** [comment]
bot: build repo:eessi.io-2023.06-software arch:zen4

**Comment by casparvl** [comment]
https://docs.sylabs.io/guides/3.6/admin-guide/installation.html#filesystem-support-limitations

> Fakeroot / (sub)uid/gid mapping[](https://docs.sylabs.io/guides/3.6/admin-guide/installation.html#fakeroot-sub-uid-gid-mapping)
When Singularity is run using the [fakeroot](https://docs.sylabs.io/guides/3.6/admin-guide/user_namespace.html#fakeroot) option it creates a user namespace for the container, and UIDs / GIDs in that user namepace are mapped to different host UID / GIDs.

> Most local filesystems (ext4/xfs etc.) support this uid/gid mapping in a user namespace.

> Most network filesystems (NFS/Lustre/GPFS etc.) do not support this uid/gid mapping in a user namespace. Because the fileserver is not aware of the mappings it will deny many operations, with ‘permission denied’ errors. This is currently a generic problem for rootless container runtimes.

**Comment by casparvl** [comment]
Hm, maybe that's not it. Seems like in both clusters (AWS and Azure) `singularity` is installed on `xfs`

**Comment by bedroge** [comment]
We ran into the same issue last week, see https://github.com/EESSI/magic-castle-clusters/issues/28#issuecomment-2242669887. @ocaisa has a temporary workaround for it.

**Comment by ocaisa** [comment]
bot: build repo:eessi.io-2023.06-software arch:zen4

**Comment by trz42** [comment]
The last build looks good! Only the Python/3.11.* packages are rebuilt. All other packages are new (with the versions/toolchains listed, for some packages other versions exist). I took a snapshot of the directory contains for the Python packages, hence we can go on deploying the built installations.

**Comment by casparvl** [comment]
Test failure is not a big deal (for now, though we should fix it). It's trying to read the memory limit from the `cgroup` [here](https://github.com/EESSI/software-layer/blob/3f61b2b76c7b5e738cf68dbae99580b9b501c701/test_suite.sh#L160). Apparently, that fails on the azure cluster:
```
cat: /hostsys/fs/cgroup/memory/slurm/uid_60008/job_170/memory.limit_in_bytes: No such file or directory
ESC[31mERROR: Failed to get the memory limit in bytes from the current cgroupESC[0m
```

I guess we should interactively try this, and figure out why that path doesn't exist. Did the bind-mount from `/sys/fs/cgroup` to `/hostsys/fs/cgroup` fail? Does that specific subdir not exist? I currently can't seem to submit jobs, so can't figure it out right now.... 

```
$ salloc -p x86_64-amd-zen4-node
salloc: error: invalid partition specified: x86_64-amd-zen4-node
salloc: error: Job submit/allocate failed: Invalid partition name specified
```
Maybe SLURM is not configured in a way that it sets `cgroups` for the job? Although I do see `TaskPlugin=task/affinity,task/cgroup` in `slurm.conf`...

Maybe we should have a fallback: if it fails, maybe we just assume a very large memory, and hope for the best (and print a big fat warning we did this). Worst case, a test runs OOM, but in many cases, tests would probably still run fine.

**Comment by casparvl** [comment]
> The last build looks good! Only the Python/3.11.* packages are rebuilt. All other packages are new (with the versions/toolchains listed, for some packages other versions exist). I took a snapshot of the directory contains for the Python packages, hence we can go on deploying the built installations.

Agreed, the test suite failure is not an issue (and is probably there in other `zen4` builds too, I just never looked at them apparently).

**Review by ocaisa — APPROVED** [review]

**Comment by Neves-P** [comment]
Replaced and manually added the necessary tarballs on the stratum 0 following Bob's procedure. Thanks, @trz42 for the help!

Procedure:
``` bash
# Deleting only zen4 builds
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen4/software/FLAC/1.4.2-GCCcore-12.3.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen4/software/LLVM/14.0.6-GCCcore-12.3.0-llvmlite
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen4/software/LittleCMS/2.15-GCCcore-12.3.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen4/software/OpenJPEG/2.5.0-GCCcore-12.3.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen4/software/Pillow/10.0.0-GCCcore-12.3.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen4/software/Python/3.11.3-GCCcore-12.3.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen4/software/Python/3.11.5-GCCcore-13.2.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen4/software/Qhull/2020.2-GCCcore-12.3.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen4/software/Tkinter/3.11.3-GCCcore-12.3.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen4/software/cppy/1.2.1-GCCcore-12.3.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen4/software/libogg/1.3.5-GCCcore-12.3.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen4/software/libopus/1.4-GCCcore-12.3.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen4/software/librosa/0.10.1-foss-2023a
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen4/software/libsndfile/1.2.2-GCCcore-12.3.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen4/software/libvorbis/1.3.7-GCCcore-12.3.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen4/software/libwebp/1.3.1-GCCcore-12.3.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen4/software/matplotlib/3.7.2-gfbf-2023a
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen4/software/meson-python/0.13.2-GCCcore-12.3.0
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen4/software/numba/0.58.1-foss-2023a
rm -rf /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen4/software/scikit-learn/1.3.1-gfbf-2023a

# Move to software dir
cd /cvmfs/software.eessi.io/versions

# Unpack tarball
tar xvzf /srv/tmp/tarballs/eessi-2023.06-software-linux-x86_64-amd-zen4-1722586858.tar.gz
```

**Pull request merged**
