### PR TITLE
{2023.06}[foss/2023a] GROMACS v2023.3

### PR DESCRIPTION
**Pull request by boegel**
~Should first deploy & merge:~
* #403

```
1 out of 58 required modules missing:

* GROMACS/2023.3-foss-2023a (GROMACS-2023.3-foss-2023a.eb)
* ```

### CODE REVIEW

**Comment by boegel** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1

**Comment by boegel** [comment]
Doesn't work yet, `mpi4py` is also needed, I'll get builds to work in https://github.com/easybuilders/easybuild-easyconfigs/pull/19321 first.

I'll manually cancel the build jobs.

**Comment by boegel** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1

**Comment by boegel** [comment]
Hooks are missing to work around  test failures with `scipy` on `neoverse_v1`, see also https://github.com/EESSI/software-layer/pull/403#issuecomment-1829544770

**Comment by boegel** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3

**Comment by boegel** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1

**Comment by boegel** [comment]
Test suite failed on `neoverse_v1` (job 1434), some failure-related output:

```
45/85 Test #45: SimdUnitTests ................................***Failed    0.03 sec
```

```
80/85 Test #80: MdrunFEPTests ................................***Failed    1.12 sec
```

```
The following tests FAILED:
         15 - GmxlibTests (Subprocess aborted)
         45 - SimdUnitTests (Failed)
         80 - MdrunFEPTests (Failed)
```

**Comment by casparvl** [comment]
Can you manually reproduce these failures? https://www.eessi.io/docs/adding_software/debugging_failed_builds/
 
I saw the `GmxapiMpiTests` failure on Generoso was related to some I/O error. Makes me wonder if it's related to the writeable overlay somehow, or our tempdir or whatever. Would be nice to try and change those in an interactive build and see if that resolves it.

**Comment by bedroge** [comment]
> /project/def-users/SHARED/jobs/2023.11/pr_401/1431

Just tried it interactively on a `zen3` with the `bot/inspect.sh` script, and the same test failed. It indeed reports some I/O error:
```
-------------------------------------------------------
Program:     gmxapi-mpi-test, version 2023.3-EasyBuild_4.9.0
Source file: src/gromacs/utility/futil.cpp (line 454)
MPI rank:    1 (out of 2)

File input/output error:
/tmp/bedroge/easybuild/build/GROMACS/2023.3/foss-2023a/easybuild_obj/api/gmxapi/cpp/tests/Testing/Temporary/GmxApiTest_RunnerChainedMD.trr

For more information and tips for troubleshooting, please check the GROMACS
website at http://www.gromacs.org/Documentation/Errors
-------------------------------------------------------

-------------------------------------------------------
Program:     gmxapi-mpi-test, version 2023.3-EasyBuild_4.9.0
Source file: src/gromacs/utility/futil.cpp (line 454)
MPI rank:    0 (out of 2)

File input/output error:
/tmp/bedroge/easybuild/build/GROMACS/2023.3/foss-2023a/easybuild_obj/api/gmxapi/cpp/tests/Testing/Temporary/GmxApiTest_RunnerChainedMD.trr

For more information and tips for troubleshooting, please check the GROMACS
website at http://www.gromacs.org/Documentation/Errors
-------------------------------------------------------
```

That file doesn't exist, the directory only contains:
```
GmxApiTest_ApiRunnerStopSignalClient_state_prev.cpt
GmxApiTest_RunnerChainedMD.edr
GmxApiTest_RunnerChainedMD.log
GmxApiTest_RunnerChainedMD.part0002.edr
GmxApiTest_RunnerChainedMD.part0002.log
GmxApiTest_RunnerChainedMD.part0002.trr
GmxApiTest_RunnerChainedMD.tpr
GmxApiTest_RunnerChainedMD_confout.part0002.gro
GmxApiTest_RunnerChainedMD_input.mdp
GmxApiTest_RunnerChainedMD_output.mdp
GmxApiTest_RunnerChainedMD_state_prev.cpt
GmxApiTest_RunnerReinitialize_state_prev.cpt
```

**Comment by bedroge** [comment]
While looking for clues at the GROMACS gitlab, I noticed that 2023.4 is available, and figured I could give it a try in the interactive session: it worked! Can't find any clues in the release notes (https://manual.gromacs.org/current/release-notes/2023/2023.4.html) though, but I'll make a PR for the easyconfig, so we can use it here as well.

**Comment by al42and** [comment]
@bedroge:

Are you, by any chance, running tests in parallel? If so, [GROMACS does not handle that](https://gitlab.com/gromacs/gromacs/-/issues/4654). You can compile the code in parallel (`make tests -j X`), but `make check` should be run in a single thread.

**Comment by bedroge** [comment]
> @bedroge:
> 
> Are you, by any chance, running tests in parallel? If so, [GROMACS does not handle that](https://gitlab.com/gromacs/gromacs/-/issues/4654). You can compile the code in parallel (`make tests -j X`), but `make check` should be run in a single thread.

Thanks for the pointer, @al42and! We're using EasyBuild here, and from what I can see in the output and in the EasyBuild Python code that starts the tests (https://github.com/easybuilders/easybuild-easyblocks/blob/develop/easybuild/easyblocks/g/gromacs.py#L495) it does indeed run with `make check -j <number of cores>`. Let me try that with a single thread.

**Comment by boegel** [comment]
> @bedroge:
> 
> Are you, by any chance, running tests in parallel? If so, [GROMACS does not handle that](https://gitlab.com/gromacs/gromacs/-/issues/4654). You can compile the code in parallel (`make tests -j X`), but `make check` should be run in a single thread.

@al42and That's interesting... We haven't really run into trouble with this before, as far as I recall...

Is this a new requirement? Have we just been very lucky up until now?

**Comment by al42and** [comment]
> Is this a new requirement? Have we just been very lucky up until now?

IIRC, running tests in parallel was never supported explicitly, but *most* tests are safe. Furthermore, normally, CMake does not pass on the `-j` flag to `ctest`, so `make check -j20` should be safe, unlike `ctest -j20` or `make test ARGS=-j20`.

So, if you are simply running `make check -j X`, that should not cause problems and my guess was wrong (unless CMake changed their behavior between versions about it). I'm unfortunately not versed well enough in EasyBuild scripts to grasp how exactly is the command line constructed. Sorry for the noise if my suggestion was wrong.

**Comment by boegel** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1

**Comment by boegel** [comment]
I re-triggered the build to try again using EasyBuild v4.9.0, because I didn't run into failures at all with a manual build (in EESSI build container/environment) on our AMD Rome (zen2) system...

failing tests for `x86_64/amd/zen3` (job 5154):

```
99% tests passed, 1 tests failed out of 87
...
The following tests FAILED:
          2 - GmxapiMpiTests (Failed)
```

note that there were no failing tests for `x86_64/amd/zen2` this time, while in a previous attempt `GmxapiMpiTests` also failed there (see https://github.com/EESSI/software-layer/pull/401#issuecomment-1830153686)

failing tests for `aarch64/neoverse_v1` (job 5157):

```
96% tests passed, 3 tests failed out of 85
...
The following tests FAILED:
         15 - GmxlibTests (SEGFAULT)
         45 - SimdUnitTests (Failed)
         80 - MdrunFEPTests (Failed)
```

on `x86_64/intel/haswell`, test step is hanging, so looks like it's just going to time out...

<details>

```
bot         4069  0.0  0.0 222864  3304 ?        S    17:44   0:00 bash /var/spool/slurmd/job05151/slurm_script
bot         4070  0.0  0.0 223128  3556 ?        S    17:44   0:00  \_ bash bot/build.sh
bot         4267  0.0  0.0 223128  3652 ?        S    17:44   0:00      \_ /bin/bash ./eessi_container.sh --verbose --access rw --mode run --container docker://ghcr.io/eessi/build-node:debian11 --repository eessi.io-2023.06-software --save /project/60006/SHARED/jobs/2024.02/pr_401/event_4577dd40-c128-11ee-9720-d3d6dffc6b6e/run_001/linux_x86_64_intel_haswell/eessi.io-2023.06-software/previous_tmp/build_step --storage /tmp/bot/EESSI --nvidia all --host-injections /project/def-users/bot/shared/host-injections -- ./install_software_layer.sh --build-logs-dir /project/def-users/SHARED/build-logs --shared-fs-path /project/def-users/bot/shared
bot         4640  0.0  0.1 1223036 32088 ?       Sl   17:44   0:00      |   \_ Apptainer runtime parent
bot         4667  0.0  0.0 1152192 29912 ?       Sl   17:44   0:00      |       \_ appinit
bot         4702  0.0  0.1 533640 40320 ?        Sl   17:44   0:00      |       |   \_ cvmfs2 cvmfs-config.cern.ch /dev/fd/3 -f
bot         4703  0.8  0.2 951000 65176 ?        Sl   17:44   1:37      |       |   \_ cvmfs2 software.eessi.io /dev/fd/3 -f
bot         4705  0.7  0.0  27712 27100 ?        S    17:44   1:26      |       |   \_ fuse-overlayfs -o lowerdir=/cvmfs_ro/software.eessi.io -o upperdir=/tmp/overlay-upper -o workdir=/tmp/overlay-work /dev/fd/3 -f
bot         4706  0.0  0.0   3824  2832 ?        S    17:44   0:00      |       |   \_ /bin/bash /project/60006/SHARED/jobs/2024.02/pr_401/event_4577dd40-c128-11ee-9720-d3d6dffc6b6e/run_001/linux_x86_64_intel_haswell/eessi.io-2023.06-software/install_software_layer.sh --build-logs-dir /project/def-users/SHARED/build-logs --shared-fs-path /project/def-users/bot/shared
bot         4720  0.0  0.0   3956  2776 ?        S    17:44   0:00      |       |   |   \_ /bin/bash ./run_in_compat_layer_env.sh ./EESSI-install-software.sh --build-logs-dir /project/def-users/SHARED/build-logs --shared-fs-path /project/def-users/bot/shared
bot         4823  0.0  0.0   7344  3624 ?        S    17:44   0:00      |       |   |       \_ /cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64/bin/bash /cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64/startprefix
bot         4838  0.0  0.0   4320  3132 ?        S    17:44   0:00      |       |   |           \_ /cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64/bin/bash -l
bot         4872  0.0  0.0   4080  2932 ?        S    17:44   0:00      |       |   |               \_ /bin/bash ./EESSI-install-software.sh --build-logs-dir /project/def-users/SHARED/build-logs --shared-fs-path /project/def-users/bot/shared
bot         5087  0.0  0.3 181068 108108 ?       Sl   17:44   0:08      |       |   |                   \_ /cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64/usr/lib/python-exec/python3.11/python -m easybuild.main --easystack /project/60006/SHARED/jobs/2024.02/pr_401/event_4577dd40-c128-11ee-9720-d3d6dffc6b6e/run_001/linux_x86_64_intel_haswell/eessi.io-2023.06-software/easystacks/software.eessi.io/2023.06/eessi-2023.06-eb-4.9.0-2023a.yml --robot
bot        32567  0.0  0.0   6284  3020 ?        S    17:51   0:00      |       |   |                       \_ make check -j 16
bot        32570  0.0  0.0   6700  3464 ?        S    17:51   0:00      |       |   |                           \_ make -f CMakeFiles/Makefile2 check
bot        32574  0.0  0.0   8812  5416 ?        S    17:51   0:00      |       |   |                               \_ make -f CMakeFiles/Makefile2 CMakeFiles/check.dir/all
bot        32764  0.0  0.0   6156  2820 ?        S    17:51   0:00      |       |   |                                   \_ make -f python_packaging/gmxapi/test/CMakeFiles/gmxapi_pytest.dir/build.make python_packaging/gmxapi/test/CMakeFiles/gmxapi_pytest.dir/build
bot        32765  0.0  0.0   2592   628 ?        S    17:51   0:00      |       |   |                                   |   \_ /bin/sh -c cd /tmp/bot/easybuild/build/GROMACS/2023.3/foss-2023a/easybuild_obj/python_packaging/gmxapi/gmxapi_staging && /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/CMake/3.26.3-GCCcore-12.3.0/bin/cmake -E env --unset=OMP_NUM_THREADS /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/Python/3.11.3-GCCcore-12.3.0/bin/python -m pytest -rA -l --log-cli-level ERROR /tmp/bot/easybuild/build/GROMACS/2023.3/foss-2023a/gromacs-2023.3/python_packaging/gmxapi/test
bot        32766  0.0  0.0  24600  8920 ?        S    17:51   0:00      |       |   |                                   |       \_ /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/CMake/3.26.3-GCCcore-12.3.0/bin/cmake -E env --unset=OMP_NUM_THREADS /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/Python/3.11.3-GCCcore-12.3.0/bin/python -m pytest -rA -l --log-cli-level ERROR /tmp/bot/easybuild/build/GROMACS/2023.3/foss-2023a/gromacs-2023.3/python_packaging/gmxapi/test
bot        32770  0.0  0.1 199420 40188 ?        Sl   17:51   0:00      |       |   |                                   |           \_ /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/Python/3.11.3-GCCcore-12.3.0/bin/python -m pytest -rA -l --log-cli-level ERROR /tmp/bot/easybuild/build/GROMACS/2023.3/foss-2023a/gromacs-2023.3/python_packaging/gmxapi/test
bot        32778  0.0  0.0 158016 21880 ?        Ssl  17:51   0:00      |       |   |                                   |               \_ orted --hnp --set-sid --report-uri 14 --singleton-died-pipe 15 -mca state_novm_select 1 -mca ess hnp -mca pmix ^s1,s2,cray,isolated
bot        32774  0.0  0.0   6156  2916 ?        S    17:51   0:00      |       |   |                                   \_ make -f python_packaging/sample_restraint/tests/CMakeFiles/gmxapi_extension_pytest.dir/build.make python_packaging/sample_restraint/tests/CMakeFiles/gmxapi_extension_pytest.dir/build
bot        32775  0.0  0.0   2592   692 ?        S    17:51   0:00      |       |   |                                       \_ /bin/sh -c cd /tmp/bot/easybuild/build/GROMACS/2023.3/foss-2023a/easybuild_obj/python_packaging/gmxapi/gmxapi_staging && /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/CMake/3.26.3-GCCcore-12.3.0/bin/cmake -E env --unset=OMP_NUM_THREADS LD_LIBRARY_PATH= PYTHONPATH=/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/mpi4py/3.1.4-gompi-2023a/lib/python3.11/site-packages:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/networkx/3.1-gfbf-2023a/lib/python3.11/site-packages:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/SciPy-bundle/2023.07-gfbf-2023a/lib/python3.11/site-packages:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/pybind11/2.11.1-GCCcore-12.3.0/lib/python3.11/site-packages:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/Python-bundle-PyPI/2023.06-GCCcore-12.3.0/lib/python3.11/site-packages:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/virtualenv/20.23.1-GCCcore-12.3.0/lib/python3.11/site-packages:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/cryptography/41.0.1-GCCcore-12.3.0/lib/python3.11/site-packages:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/cffi/1.15.1-GCCcore-12.3.0/lib/python3.11/site-packages:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/Python/3.11.3-GCCcore-12.3.0/easybuild/python:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/scikit-build/0.17.6-GCCcore-12.3.0/lib/python3.11/site-packages:/tmp/bot/easybuild/build/GROMACS/2023.3/foss-2023a/easybuild_obj/python_packaging/gmxapi/gmxapi_staging:/tmp/bot/easybuild/build/GROMACS/2023.3/foss-2023a/easybuild_obj/lib /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/Python/3.11.3-GCCcore-12.3.0/bin/python -m pytest --log-cli-level ERROR /tmp/bot/easybuild/build/GROMACS/2023.3/foss-2023a/gromacs-2023.3/python_packaging/sample_restraint/tests
bot        32776  0.0  0.0  24600  8908 ?        S    17:51   0:00      |       |   |                                           \_ /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/CMake/3.26.3-GCCcore-12.3.0/bin/cmake -E env --unset=OMP_NUM_THREADS LD_LIBRARY_PATH= PYTHONPATH=/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/mpi4py/3.1.4-gompi-2023a/lib/python3.11/site-packages:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/networkx/3.1-gfbf-2023a/lib/python3.11/site-packages:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/SciPy-bundle/2023.07-gfbf-2023a/lib/python3.11/site-packages:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/pybind11/2.11.1-GCCcore-12.3.0/lib/python3.11/site-packages:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/Python-bundle-PyPI/2023.06-GCCcore-12.3.0/lib/python3.11/site-packages:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/virtualenv/20.23.1-GCCcore-12.3.0/lib/python3.11/site-packages:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/cryptography/41.0.1-GCCcore-12.3.0/lib/python3.11/site-packages:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/cffi/1.15.1-GCCcore-12.3.0/lib/python3.11/site-packages:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/Python/3.11.3-GCCcore-12.3.0/easybuild/python:/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/scikit-build/0.17.6-GCCcore-12.3.0/lib/python3.11/site-packages:/tmp/bot/easybuild/build/GROMACS/2023.3/foss-2023a/easybuild_obj/python_packaging/gmxapi/gmxapi_staging:/tmp/bot/easybuild/build/GROMACS/2023.3/foss-2023a/easybuild_obj/lib /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/Python/3.11.3-GCCcore-12.3.0/bin/python -m pytest --log-cli-level ERROR /tmp/bot/easybuild/build/GROMACS/2023.3/foss-2023a/gromacs-2023.3/python_packaging/sample_restraint/tests
bot        32777  0.0  0.1 203856 44732 ?        Sl   17:51   0:00      |       |   |                                               \_ /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/intel/haswell/software/Python/3.11.3-GCCcore-12.3.0/bin/python -m pytest --log-cli-level ERROR /tmp/bot/easybuild/build/GROMACS/2023.3/foss-2023a/gromacs-2023.3/python_packaging/sample_restraint/tests
bot        32780  0.0  0.0 158020 18220 ?        Ssl  17:51   0:00      |       |   |                                                   \_ orted --hnp --set-sid --report-uri 14 --singleton-died-pipe 15 -mca state_novm_select 1 -mca ess hnp -mca pmix ^s1,s2,cray,isolated
```

</details>

**Comment by boegel** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1

**Comment by boegel** [comment]
superseded by #499

**Pull request closed without merging**
