### PR TITLE
Split off the LMOD hooks from lmodrc.lua into a seperate SitePackage.lua file

### PR DESCRIPTION
**Pull request by casparvl**
Fixes https://github.com/EESSI/software-layer/issues/491

This PR splits the current `lmodrc.lua` files in two parts: an `lmodrc.lua` containing the stuff that _actually_ belongs there, i.e. the definition of `propT` and `scDescriptT` tables. The second part is a `SitePackage.lua` containing the stuff that _actually_ belongs there, i.e. the Lmod hooks https://lmod.readthedocs.io/en/latest/170_hooks.html

### CODE REVIEW

**Comment by casparvl** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic

**Comment by casparvl** [comment]
From the logs:

```
**Files /project/60006/SHARED/jobs/2024.03/pr_496/event_00e423b0-e09e-11ee-9fcb-e53cb1a7fa7c/run_000/linux_x86_64_generic/eessi.io-2023.06-software/init/eessi_environment_variables and /cvmfs/software.eessi.io/versions/2023.06/init/eessi_environment_variables differ
File /project/60006/SHARED/jobs/2024.03/pr_496/event_00e423b0-e09e-11ee-9fcb-e53cb1a7fa7c/run_000/linux_x86_64_generic/eessi.io-2023.06-software/init/eessi_environment_variables copied to /cvmfs/software.eessi.io/versions/2023.06/init/eessi_environment_variables
```

It does get copied, but looking at the artefacts, it does not end up in the tarball. Pretty sure our `create_tarball.sh`  needs a change to also consider anything in `init`. E.g. for scripts it does:
```
# include scripts that were copied by install_scripts.sh, which we want to ship in EESSI repository
if [ -d ${eessi_version}/scripts ]; then
    find ${eessi_version}/scripts -type f | grep -v '/\.wh\.' >> ${files_list}
fi
```

**Comment by casparvl** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic

**Comment by casparvl** [comment]
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic

**Review by trz42 — APPROVED** [review]
Looks good. Nice work. Walked through this with @casparvl during hackathon on 2024-03-26.

The output of the contents of the tarball in the PR here are misleading. We looked at the contents and it is ok. Also the deployment/ingestion procedure is essentially the same for `init` and `software` tarballs, hence it should work to combine these in a single tarball for now.

**Comment by bedroge** [comment]
bot: build repo:eessi.io-2023.06-software arch:aarch64/generic
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_n1
bot: build repo:eessi.io-2023.06-software arch:aarch64/neoverse_v1
bot: build repo:eessi.io-2023.06-software arch:x86_64/generic
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen2
bot: build repo:eessi.io-2023.06-software arch:x86_64/amd/zen3
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/haswell
bot: build repo:eessi.io-2023.06-software arch:x86_64/intel/skylake_avx512

**Comment by bedroge** [comment]
This should have been built and deployed (in order to get the new `SitePackage.lua` into the repo), but doesn't seem like we can still do that.

**Comment by casparvl** [comment]
Note that this _did_ get deployed in the end, as part of another PR... See the artifacts in https://github.com/EESSI/software-layer/pull/511#issuecomment-2020146748 :)

**Pull request merged**
